import type { Part } from './chapter-one';

export const chapter = {
  id: 'program-structure',
  title: 'Struktur Program',
  number: '02',
};

export const parts: Part[] = [
  {
    id: 'expressions-statements',
    title: 'Ekspresi dan pernyataan',
    description:
      'Program JavaScript tersusun dari potongan kecil yang menghasilkan nilai dan instruksi lengkap yang menjalankan tindakan.',
    highlights: ['ekspresi', 'pernyataan', '=', ';', 'const', '+', '*'],
    core: 'Ekspresi menghasilkan sebuah nilai. Contohnya 2 + 3 menghasilkan 5. Pernyataan adalah instruksi lengkap, misalnya const total = 2 + 3;. Tanda = menyimpan hasil ekspresi di sebelah kanan ke nama di sebelah kiri, sedangkan ; menandai akhir pernyataan.',
    model: ['2 + 3', 'const total = 2 + 3;', 'total → 5'],
    why: 'Bayangkan ekspresi sebagai jawaban, dan pernyataan sebagai kalimat perintah. Sebuah pernyataan dapat memuat beberapa ekspresi. Membedakan keduanya membantu kamu membaca struktur kode dan mengetahui bagian mana yang menghasilkan nilai.',
    example:
      'const price = 12000;\nconst quantity = 3;\nconst subtotal = price * quantity;\nconsole.log(subtotal);',
    mistake:
      'Tanda = bukan berarti “sama dengan” seperti dalam matematika. Di JavaScript, = berarti simpan nilai. Untuk membandingkan dua nilai, kamu akan memakai ===.',
    exercises: [
      {
        id: 'structure-expression-predict', stage: 'Prediksi', mode: 'console',
        title: 'Nilai dari sebuah ekspresi',
        instruction: 'Pilih nilai yang ditampilkan. Kerjakan operasi di dalam kurung terlebih dahulu.',
        starter: 'const result = 4 + 3 * 2;\nconsole.log(result);',
        options: ['10', '14', '9', 'undefined'], answer: '10',
        explanation: 'Perkalian * dikerjakan lebih dahulu: 3 * 2 menghasilkan 6, lalu 4 + 6 menghasilkan 10.',
        tests: [{ name: 'Urutan operasi', inputs: {}, expected: '10' }],
        hints: ['Cari operasi yang memiliki prioritas lebih tinggi.', 'Hitung 3 * 2 lebih dahulu, lalu tambahkan 4.'],
        solution: 'const result = 4 + 3 * 2;\nconsole.log(result);',
      },
      {
        id: 'structure-expression-complete', stage: 'Lengkapi', mode: 'expression',
        title: 'Hitung subtotal',
        instruction: 'Buat ekspresi yang mengalikan price dengan quantity.',
        starter: '// Hitung harga untuk seluruh barang\n0',
        tests: [
          { name: 'Tiga barang', inputs: { price: 8000, quantity: 3 }, expected: 24000 },
          { name: 'Lima barang', inputs: { price: 12500, quantity: 5 }, expected: 62500 },
        ],
        hints: ['Gunakan kedua nama variabel yang sudah tersedia.', 'Pola yang dibutuhkan: price * quantity.'],
        solution: 'price * quantity',
      },
      {
        id: 'structure-expression-build', stage: 'Bangun', mode: 'script',
        title: 'Susun perhitungan belanja',
        instruction: 'Buat subtotal dari price * quantity, tax sebesar subtotal * 0.11, lalu total dari subtotal + tax. Gunakan const untuk ketiganya.',
        starter: '// Buat subtotal, tax, dan total\n', probe: '[subtotal, tax, total]',
        tests: [
          { name: 'Belanja pertama', inputs: { price: 10000, quantity: 2 }, expected: [20000, 2200, 22200] },
          { name: 'Belanja kedua', inputs: { price: 25000, quantity: 4 }, expected: [100000, 11000, 111000] },
        ],
        hints: ['Setiap nilai baru dapat memakai nilai yang dibuat pada baris sebelumnya.', 'Mulai dengan const subtotal = price * quantity;.'],
        solution: 'const subtotal = price * quantity;\nconst tax = subtotal * 0.11;\nconst total = subtotal + tax;',
      },
    ],
  },
  {
    id: 'bindings',
    title: 'Variabel: memberi nama pada nilai',
    description: 'Variabel membuat sebuah nilai mudah disimpan, dibaca, dan dipakai kembali di bagian lain program.',
    highlights: ['const', 'let', '=', 'variabel', 'camelCase'],
    core: 'Gunakan const saat nama tidak perlu diberi nilai baru, dan let saat nilainya memang akan berubah. Pola const city = "Bandung"; membuat variabel city. Nama JavaScript peka terhadap huruf besar-kecil dan biasanya ditulis dengan gaya camelCase, seperti totalPrice.',
    model: ['nilai', 'const name = nilai;', 'name dapat dipakai lagi'],
    why: 'Nama yang jelas menjelaskan maksud data. totalPrice lebih mudah dipahami daripada x. Memilih const sebagai kebiasaan awal juga mencegah perubahan nilai yang tidak disengaja.',
    example: 'const courseName = "JavaScript Dasar";\nlet enrolled = 12;\nenrolled = 13;\nconsole.log(courseName, enrolled);',
    mistake: 'const mencegah pemberian nilai baru pada variabel, bukan berarti seluruh isi sebuah objek selalu beku. Untuk sekarang, pilih const kecuali kamu tahu nilainya perlu berubah; pilih let untuk keadaan yang berubah.',
    exercises: [
      {
        id: 'structure-binding-predict', stage: 'Prediksi', mode: 'console', title: 'Nilai terbaru',
        instruction: 'Pilih nilai yang ditampilkan setelah variabel diperbarui.',
        starter: 'let seats = 20;\nseats = 18;\nconsole.log(seats);',
        options: ['20', '18', 'seats', 'error'], answer: '18',
        explanation: 'let mengizinkan seats menerima nilai baru. Pernyataan seats = 18; mengganti nilai sebelumnya.',
        tests: [{ name: 'Nilai setelah assignment', inputs: {}, expected: '18' }],
        hints: ['Baca kode dari atas ke bawah.', 'Nilai terakhir yang diberikan kepada seats adalah 18.'],
        solution: 'let seats = 20;\nseats = 18;\nconsole.log(seats);',
      },
      {
        id: 'structure-binding-complete', stage: 'Lengkapi', mode: 'script', title: 'Nama lengkap',
        instruction: 'Buat fullName dengan const. Gabungkan firstName, satu spasi, dan lastName menggunakan +.',
        starter: '// Buat variabel fullName\n', probe: 'fullName',
        tests: [
          { name: 'Nama pertama', inputs: { firstName: 'Ayu', lastName: 'Lestari' }, expected: 'Ayu Lestari' },
          { name: 'Nama kedua', inputs: { firstName: 'Bima', lastName: 'Putra' }, expected: 'Bima Putra' },
        ],
        hints: ['Teks spasi ditulis sebagai " ".', 'Pola lengkapnya: const fullName = firstName + " " + lastName;.'],
        solution: 'const fullName = firstName + " " + lastName;',
      },
      {
        id: 'structure-binding-build', stage: 'Bangun', mode: 'script', title: 'Data peserta',
        instruction: 'Buat const participantName berisi "Nadia" dan let points berisi 10. Kemudian ubah points menjadi 15.',
        starter: '// Tulis tiga pernyataan di bawah ini\n', probe: '[participantName, points]',
        tests: [{ name: 'Nama dan poin akhir', inputs: {}, expected: ['Nadia', 15] }],
        hints: ['participantName tidak berubah, jadi gunakan const.', 'Buat let points = 10;, lalu berikan nilai baru dengan points = 15;.'],
        solution: 'const participantName = "Nadia";\nlet points = 10;\npoints = 15;',
      },
    ],
  },
  {
    id: 'assignment-state',
    title: 'Assignment dan perubahan keadaan',
    description: 'Program sering menyimpan keadaan saat ini—seperti skor atau saldo—lalu memperbaruinya seiring waktu.',
    highlights: ['=', '+=', '-=', '++', '--', 'let', 'state'],
    core: 'Assignment dengan = mengganti nilai. Bentuk += menambahkan nilai ke keadaan saat ini, sedangkan -= menguranginya. count++ menambah 1 dan count-- mengurangi 1. Karena nilainya berubah, variabel keadaan dibuat dengan let.',
    model: ['let score = 5', 'score += 3', 'score → 8'],
    why: 'Keadaan atau state adalah potret data pada satu waktu. Setiap assignment menghasilkan keadaan baru. Membaca perubahan baris demi baris membuat alur program lebih mudah dilacak.',
    example: 'let stock = 10;\nstock -= 2;\nstock++;\nconsole.log(stock); // 9',
    mistake: 'score + 1 hanya menghasilkan nilai baru; ia tidak mengubah score. Agar perubahan tersimpan, gunakan score = score + 1 atau bentuk singkat score++.',
    exercises: [
      {
        id: 'structure-state-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti perubahan nilai',
        instruction: 'Lacak nilai count setelah setiap baris, lalu pilih hasil akhirnya.',
        starter: 'let count = 4;\ncount += 3;\ncount--;\nconsole.log(count);',
        options: ['4', '6', '7', '8'], answer: '6',
        explanation: 'count dimulai dari 4, bertambah 3 menjadi 7, lalu -- mengurangi 1 sehingga hasilnya 6.',
        tests: [{ name: 'Keadaan akhir', inputs: {}, expected: '6' }],
        hints: ['Tulis nilai sementara setelah setiap baris.', '4 + 3 = 7, kemudian kurangi 1.'],
        solution: 'let count = 4;\ncount += 3;\ncount--;\nconsole.log(count);',
      },
      {
        id: 'structure-state-complete', stage: 'Lengkapi', mode: 'script', title: 'Perbarui penghitung',
        instruction: 'Buat let total dari start, tambahkan added, lalu kurangi removed. Jangan menuliskan angka contoh secara langsung.',
        starter: 'let total = start;\n// Perbarui total di bawah ini\n', probe: 'total',
        tests: [
          { name: 'Perubahan pertama', inputs: { start: 10, added: 5, removed: 2 }, expected: 13 },
          { name: 'Perubahan kedua', inputs: { start: 30, added: 4, removed: 11 }, expected: 23 },
        ],
        hints: ['Gunakan total += added untuk perubahan pertama.', 'Setelah itu gunakan total -= removed.'],
        solution: 'let total = start;\ntotal += added;\ntotal -= removed;',
      },
      {
        id: 'structure-state-build', stage: 'Bangun', mode: 'script', title: 'Catat saldo akhir',
        instruction: 'Buat let balance dari openingBalance. Tambahkan deposit dan kurangi payment menggunakan operator assignment singkat.',
        starter: '// Buat dan perbarui balance\n', probe: 'balance',
        tests: [
          { name: 'Saldo bertambah', inputs: { openingBalance: 100000, deposit: 50000, payment: 25000 }, expected: 125000 },
          { name: 'Saldo berkurang', inputs: { openingBalance: 80000, deposit: 10000, payment: 45000 }, expected: 45000 },
        ],
        hints: ['Mulai dengan let balance = openingBalance;.', 'Gunakan += untuk deposit dan -= untuk payment.'],
        solution: 'let balance = openingBalance;\nbalance += deposit;\nbalance -= payment;',
      },
    ],
  },
  {
    id: 'conditional-execution',
    title: 'Percabangan dengan if',
    description: 'Percabangan membuat program memilih tindakan berdasarkan kondisi yang sedang terjadi.',
    highlights: ['if', 'else', 'else if', '===', '>=', '<', 'boolean'],
    core: 'if menjalankan blok kode ketika kondisinya true. else menyediakan pilihan ketika kondisi false. Gunakan else if untuk lebih dari dua kemungkinan. Kondisi biasanya berupa perbandingan seperti score >= 75 atau role === "admin".',
    model: ['kondisi', 'true → blok if', 'false → blok else'],
    why: 'Program tidak selalu berjalan dalam satu jalur. Percabangan menghubungkan data dengan keputusan, misalnya menentukan lulus atau belum lulus dari sebuah nilai.',
    example: 'const score = 82;\nlet status;\nif (score >= 75) {\n  status = "Lulus";\n} else {\n  status = "Belum lulus";\n}\nconsole.log(status);',
    mistake: 'Jangan memakai = untuk membandingkan. Gunakan === untuk kesamaan yang ketat. Pastikan juga blok diapit { dan } agar batas instruksinya terlihat jelas.',
    exercises: [
      {
        id: 'structure-if-predict', stage: 'Prediksi', mode: 'console', title: 'Cabang yang dipilih',
        instruction: 'Tentukan blok mana yang dijalankan oleh kondisi.',
        starter: 'const temperature = 31;\nif (temperature >= 30) {\n  console.log("Panas");\n} else {\n  console.log("Sejuk");\n}',
        options: ['Panas', 'Sejuk', 'true', '31'], answer: 'Panas',
        explanation: '31 >= 30 bernilai true, sehingga blok if dijalankan dan menampilkan “Panas”.',
        tests: [{ name: 'Cabang true', inputs: {}, expected: 'Panas' }],
        hints: ['Bandingkan 31 dengan batas 30.', 'Karena kondisinya true, baca isi blok if.'],
        solution: 'const temperature = 31;\nif (temperature >= 30) {\n  console.log("Panas");\n} else {\n  console.log("Sejuk");\n}',
      },
      {
        id: 'structure-if-complete', stage: 'Lengkapi', mode: 'script', title: 'Status suhu',
        instruction: 'Buat let status. Jika temperature >= 30, isi "Panas"; jika tidak, isi "Sejuk".',
        starter: 'let status;\n// Tulis if dan else\n', probe: 'status',
        tests: [
          { name: 'Suhu panas', inputs: { temperature: 34 }, expected: 'Panas' },
          { name: 'Batas panas', inputs: { temperature: 30 }, expected: 'Panas' },
          { name: 'Suhu sejuk', inputs: { temperature: 24 }, expected: 'Sejuk' },
        ],
        hints: ['Mulai dengan if (temperature >= 30) { ... }.', 'Isi status di blok if dan blok else.'],
        solution: 'let status;\nif (temperature >= 30) {\n  status = "Panas";\n} else {\n  status = "Sejuk";\n}',
      },
      {
        id: 'structure-if-build', stage: 'Bangun', mode: 'script', title: 'Tiga tingkat hasil',
        instruction: 'Buat let label. Isi "Baik" jika score >= 80, "Cukup" jika score >= 60, dan "Perlu latihan" untuk nilai lainnya.',
        starter: '// Buat label dengan if, else if, dan else\n', probe: 'label',
        tests: [
          { name: 'Nilai tinggi', inputs: { score: 92 }, expected: 'Baik' },
          { name: 'Nilai tengah', inputs: { score: 70 }, expected: 'Cukup' },
          { name: 'Nilai rendah', inputs: { score: 45 }, expected: 'Perlu latihan' },
        ],
        hints: ['Periksa batas tertinggi terlebih dahulu agar rentangnya tidak tumpang tindih.', 'Gunakan if, lalu else if, dan akhiri dengan else.'],
        solution: 'let label;\nif (score >= 80) {\n  label = "Baik";\n} else if (score >= 60) {\n  label = "Cukup";\n} else {\n  label = "Perlu latihan";\n}',
      },
    ],
  },
  {
    id: 'while-loops',
    title: 'Perulangan while dan do...while',
    description: 'Perulangan menjalankan instruksi berulang kali selama suatu kondisi masih terpenuhi.',
    highlights: ['while', 'do', '++', '--', 'kondisi', 'loop'],
    core: 'while memeriksa kondisi sebelum menjalankan blok. Jika sejak awal kondisinya false, blok tidak berjalan. do...while menjalankan blok satu kali terlebih dahulu, baru memeriksa kondisi. Variabel pengendali harus berubah agar loop berhenti.',
    model: ['periksa kondisi', 'jalankan blok', 'ubah pengendali → ulangi'],
    why: 'Loop menggantikan instruksi yang sama berulang kali. Ia cocok ketika jumlah pengulangan ditentukan oleh kondisi, seperti memproses data sampai habis.',
    example: 'let number = 1;\nlet text = "";\nwhile (number <= 3) {\n  text += number;\n  number++;\n}\nconsole.log(text);',
    mistake: 'Lupa mengubah variabel pengendali dapat membuat loop berjalan tanpa henti. Selalu periksa: kondisi apa yang menghentikan loop, dan baris mana yang mendekatkannya ke kondisi tersebut?',
    exercises: [
      {
        id: 'structure-while-predict', stage: 'Prediksi', mode: 'console', title: 'Jumlah berulang',
        instruction: 'Ikuti nilai total pada setiap putaran, lalu pilih hasil akhirnya.',
        starter: 'let number = 1;\nlet total = 0;\nwhile (number <= 3) {\n  total += number;\n  number++;\n}\nconsole.log(total);',
        options: ['3', '6', '7', '123'], answer: '6',
        explanation: 'Loop menambahkan 1, lalu 2, lalu 3. Total akhirnya adalah 1 + 2 + 3 = 6.',
        tests: [{ name: 'Jumlah loop', inputs: {}, expected: '6' }],
        hints: ['Catat total setelah setiap putaran.', 'Perulangannya memproses angka 1 sampai 3.'],
        solution: 'let number = 1;\nlet total = 0;\nwhile (number <= 3) {\n  total += number;\n  number++;\n}\nconsole.log(total);',
      },
      {
        id: 'structure-while-complete', stage: 'Lengkapi', mode: 'script', title: 'Susun urutan angka',
        instruction: 'Gunakan while untuk membuat text berisi angka 1 sampai limit tanpa spasi, misalnya limit 4 menghasilkan "1234".',
        starter: 'let text = "";\nlet number = 1;\n// Tambahkan while\n', probe: 'text',
        tests: [
          { name: 'Empat angka', inputs: { limit: 4 }, expected: '1234' },
          { name: 'Satu angka', inputs: { limit: 1 }, expected: '1' },
        ],
        hints: ['Ulangi selama number <= limit.', 'Di dalam loop, tambahkan number ke text lalu naikkan number.'],
        solution: 'let text = "";\nlet number = 1;\nwhile (number <= limit) {\n  text += number;\n  number++;\n}',
      },
      {
        id: 'structure-while-build', stage: 'Bangun', mode: 'script', title: 'Hitung mundur',
        instruction: 'Gunakan do...while untuk membuat text hitung mundur dari start hingga 1, dipisahkan tanda "-". Jika start 3, hasilnya "3-2-1".',
        starter: 'let text = "";\nlet number = start;\n// Tulis do...while\n', probe: 'text',
        tests: [
          { name: 'Mulai dari tiga', inputs: { start: 3 }, expected: '3-2-1' },
          { name: 'Mulai dari satu', inputs: { start: 1 }, expected: '1' },
        ],
        hints: ['Tambahkan tanda - hanya jika text sudah berisi nilai.', 'Setelah menambahkan number, kurangi number dan ulangi selama number >= 1.'],
        solution: 'let text = "";\nlet number = start;\ndo {\n  if (text !== "") text += "-";\n  text += number;\n  number--;\n} while (number >= 1);',
      },
    ],
  },
  {
    id: 'for-loops',
    title: 'Perulangan for',
    description: 'for merangkum nilai awal, kondisi, dan perubahan pengendali dalam satu baris yang mudah dipindai.',
    highlights: ['for', 'let', 'i++', '<=', '{', '}'],
    core: 'Bentuk for (let i = 1; i <= 3; i++) memiliki tiga bagian: membuat i, memeriksa i <= 3, dan menambah i setelah setiap putaran. Blok di antara { dan } dijalankan selama kondisi masih true.',
    model: ['let i = 1', 'i <= batas', 'jalankan blok → i++'],
    why: 'for cocok ketika urutan perubahan sudah jelas, terutama untuk menghitung maju atau mundur. Semua aturan loop terlihat di satu tempat.',
    example: 'let total = 0;\nfor (let i = 1; i <= 4; i++) {\n  total += i;\n}\nconsole.log(total);',
    mistake: 'Perhatikan pilihan < atau <=. Kondisi i < 4 berhenti sebelum 4, sedangkan i <= 4 masih memasukkan 4. Kesalahan satu batas sering menghasilkan satu putaran kurang atau lebih.',
    exercises: [
      {
        id: 'structure-for-predict', stage: 'Prediksi', mode: 'console', title: 'Total dari for',
        instruction: 'Tentukan angka yang ditambahkan pada setiap putaran.',
        starter: 'let total = 0;\nfor (let i = 1; i <= 4; i++) {\n  total += i;\n}\nconsole.log(total);',
        options: ['4', '6', '10', '15'], answer: '10',
        explanation: 'i bernilai 1, 2, 3, lalu 4. Jumlahnya adalah 10.',
        tests: [{ name: 'Jumlah 1 sampai 4', inputs: {}, expected: '10' }],
        hints: ['Tanda <= berarti 4 ikut diproses.', 'Hitung 1 + 2 + 3 + 4.'],
        solution: 'let total = 0;\nfor (let i = 1; i <= 4; i++) {\n  total += i;\n}\nconsole.log(total);',
      },
      {
        id: 'structure-for-complete', stage: 'Lengkapi', mode: 'script', title: 'Jumlah sampai batas',
        instruction: 'Gunakan for untuk menambahkan seluruh angka dari 1 sampai limit ke total.',
        starter: 'let total = 0;\n// Tambahkan for\n', probe: 'total',
        tests: [
          { name: 'Sampai lima', inputs: { limit: 5 }, expected: 15 },
          { name: 'Sampai sepuluh', inputs: { limit: 10 }, expected: 55 },
        ],
        hints: ['Mulai i dari 1 dan ulangi selama i <= limit.', 'Di dalam blok, gunakan total += i.'],
        solution: 'let total = 0;\nfor (let i = 1; i <= limit; i++) {\n  total += i;\n}',
      },
      {
        id: 'structure-for-build', stage: 'Bangun', mode: 'script', title: 'Deret perkalian',
        instruction: 'Buat results berupa teks hasil base * 1 sampai base * limit, dipisahkan koma. Contoh base 3 dan limit 3 menghasilkan "3,6,9".',
        starter: 'let results = "";\n// Bangun deret dengan for\n', probe: 'results',
        tests: [
          { name: 'Kelipatan tiga', inputs: { base: 3, limit: 3 }, expected: '3,6,9' },
          { name: 'Kelipatan lima', inputs: { base: 5, limit: 4 }, expected: '5,10,15,20' },
        ],
        hints: ['Tambahkan koma sebelum nilai baru jika results tidak lagi kosong.', 'Pada setiap putaran, nilai yang ditambahkan adalah base * i.'],
        solution: 'let results = "";\nfor (let i = 1; i <= limit; i++) {\n  if (results !== "") results += ",";\n  results += base * i;\n}',
      },
    ],
  },
  {
    id: 'break-continue',
    title: 'Mengendalikan loop',
    description: 'break menghentikan loop sepenuhnya, sedangkan continue melewati sisa putaran saat ini dan lanjut ke putaran berikutnya.',
    highlights: ['break', 'continue', '%', '===', 'for'],
    core: 'Gunakan break ketika jawaban sudah ditemukan sehingga pengulangan tidak perlu diteruskan. Gunakan continue ketika satu nilai ingin dilewati. Operator % menghasilkan sisa pembagian; number % 2 === 0 berarti number habis dibagi 2.',
    model: ['putaran aktif', 'continue → putaran berikutnya', 'break → keluar loop'],
    why: 'Keduanya membuat maksud loop lebih jelas: berhenti saat tujuan tercapai, atau abaikan data yang tidak memenuhi syarat.',
    example: 'for (let i = 1; i <= 5; i++) {\n  if (i === 2) continue;\n  if (i === 5) break;\n  console.log(i);\n}',
    mistake: 'continue tidak menghentikan seluruh loop, dan break tidak hanya melewati satu putaran. Baca tujuan kontrolnya sebelum memilih kata kunci.',
    exercises: [
      {
        id: 'structure-control-predict', stage: 'Prediksi', mode: 'console', title: 'Nilai yang lolos',
        instruction: 'Pilih seluruh keluaran console sesuai urutannya.',
        starter: 'for (let i = 1; i <= 5; i++) {\n  if (i === 2) continue;\n  if (i === 5) break;\n  console.log(i);\n}',
        options: ['1\n3\n4', '1\n2\n3\n4', '1\n3\n4\n5', '2\n5'], answer: '1\n3\n4',
        explanation: '2 dilewati oleh continue. Saat i menjadi 5, break menghentikan loop sebelum console.log dijalankan.',
        tests: [{ name: 'Alur continue dan break', inputs: {}, expected: '1\n3\n4' }],
        hints: ['Coret 2 karena continue.', 'Angka 5 tidak dicetak karena break terjadi lebih dahulu.'],
        solution: 'for (let i = 1; i <= 5; i++) {\n  if (i === 2) continue;\n  if (i === 5) break;\n  console.log(i);\n}',
      },
      {
        id: 'structure-control-complete', stage: 'Lengkapi', mode: 'script', title: 'Temukan kelipatan pertama',
        instruction: 'Cari angka pertama setelah start yang habis dibagi divisor. Simpan ke found lalu hentikan loop dengan break. Cari paling jauh sampai start + 100.',
        starter: 'let found;\nfor (let i = start + 1; i <= start + 100; i++) {\n  // Lengkapi kondisi dan hentikan loop\n}\n', probe: 'found',
        tests: [
          { name: 'Kelipatan lima', inputs: { start: 11, divisor: 5 }, expected: 15 },
          { name: 'Kelipatan tujuh', inputs: { start: 21, divisor: 7 }, expected: 28 },
        ],
        hints: ['Habis dibagi berarti i % divisor === 0.', 'Di dalam if, isi found = i; lalu gunakan break;.'],
        solution: 'let found;\nfor (let i = start + 1; i <= start + 100; i++) {\n  if (i % divisor === 0) {\n    found = i;\n    break;\n  }\n}',
      },
      {
        id: 'structure-control-build', stage: 'Bangun', mode: 'script', title: 'Jumlah angka terpilih',
        instruction: 'Jumlahkan angka ganjil dari 1 sampai limit, tetapi lewati angka bernilai skip. Gunakan continue untuk melewati angka genap dan skip.',
        starter: 'let total = 0;\n// Tulis loop dan continue\n', probe: 'total',
        tests: [
          { name: 'Lewati lima', inputs: { limit: 7, skip: 5 }, expected: 11 },
          { name: 'Lewati tiga', inputs: { limit: 6, skip: 3 }, expected: 6 },
        ],
        hints: ['Lewati putaran jika i % 2 === 0 atau i === skip.', 'Setelah continue, tambahkan i ke total.'],
        solution: 'let total = 0;\nfor (let i = 1; i <= limit; i++) {\n  if (i % 2 === 0 || i === skip) continue;\n  total += i;\n}',
      },
    ],
  },
  {
    id: 'control-flow-challenges',
    title: 'Tantangan alur program',
    description: 'Gabungkan kondisi, perbandingan, dan loop untuk mengubah aturan dalam bahasa sehari-hari menjadi alur program.',
    highlights: ['if', 'else', 'for', '%', '&&', '==='],
    core: 'Pecah masalah menjadi tiga langkah: tentukan data yang berulang, urutkan kondisi dari yang paling khusus, lalu simpan hasil setiap putaran. Operator && berarti kedua kondisi harus true.',
    model: ['aturan', 'kondisi + loop', 'hasil terstruktur'],
    why: 'Tantangan kontrol alur bukan tentang menghafal sintaks. Tujuannya melatih cara menerjemahkan aturan menjadi langkah kecil yang dapat diperiksa.',
    example: 'for (let i = 1; i <= 6; i++) {\n  if (i % 2 === 0) console.log(i + " genap");\n  else console.log(i + " ganjil");\n}',
    mistake: 'Jika beberapa kondisi dapat benar sekaligus, periksa kondisi gabungan terlebih dahulu. Jika tidak, kondisi pertama mungkin mengambil nilai terlalu cepat.',
    exercises: [
      {
        id: 'structure-challenge-predict', stage: 'Prediksi', mode: 'console', title: 'Kondisi paling khusus',
        instruction: 'Pilih label yang ditampilkan untuk angka 12.',
        starter: 'const number = 12;\nif (number % 2 === 0 && number % 3 === 0) {\n  console.log("Keduanya");\n} else if (number % 2 === 0) {\n  console.log("Dua");\n} else {\n  console.log("Lainnya");\n}',
        options: ['Keduanya', 'Dua', 'Lainnya', '12'], answer: 'Keduanya',
        explanation: '12 habis dibagi 2 dan 3. Karena kedua kondisi true, cabang pertama dipilih.',
        tests: [{ name: 'Kondisi gabungan', inputs: {}, expected: 'Keduanya' }],
        hints: ['Periksa sisa 12 dibagi 2 dan 3.', 'Operator && mensyaratkan kedua sisi true.'],
        solution: 'const number = 12;\nif (number % 2 === 0 && number % 3 === 0) {\n  console.log("Keduanya");\n} else if (number % 2 === 0) {\n  console.log("Dua");\n} else {\n  console.log("Lainnya");\n}',
      },
      {
        id: 'structure-challenge-complete', stage: 'Lengkapi', mode: 'script', title: 'Buat pola tangga',
        instruction: 'Gunakan for untuk membuat pattern berupa baris # bertambah dari 1 sampai height. Pisahkan baris dengan karakter baris baru \\n tanpa menambah baris kosong di akhir.',
        starter: 'let pattern = "";\n// Bangun pola dengan for\n', probe: 'pattern',
        tests: [
          { name: 'Tinggi tiga', inputs: { height: 3 }, expected: '#\n##\n###' },
          { name: 'Tinggi satu', inputs: { height: 1 }, expected: '#' },
        ],
        hints: ['String "#".repeat(i) menghasilkan # sebanyak i.', 'Tambahkan "\\n" sebelum baris baru jika pattern sudah terisi.'],
        solution: 'let pattern = "";\nfor (let i = 1; i <= height; i++) {\n  if (pattern !== "") pattern += "\\n";\n  pattern += "#".repeat(i);\n}',
      },
      {
        id: 'structure-challenge-build', stage: 'Bangun', mode: 'script', title: 'Label Tiga dan Lima',
        instruction: 'Buat output untuk angka 1 sampai limit, dipisahkan koma. Kelipatan 3 menjadi "Tiga", kelipatan 5 menjadi "Lima", kelipatan keduanya menjadi "TigaLima", dan angka lain tetap berupa angka.',
        starter: 'let output = "";\n// Tulis solusi lengkap\n', probe: 'output',
        tests: [
          { name: 'Sampai lima', inputs: { limit: 5 }, expected: '1,2,Tiga,4,Lima' },
          { name: 'Mencakup kelipatan bersama', inputs: { limit: 15 }, expected: '1,2,Tiga,4,Lima,Tiga,7,8,Tiga,Lima,11,Tiga,13,14,TigaLima' },
        ],
        hints: ['Periksa kelipatan 3 dan 5 terlebih dahulu.', 'Tentukan label setiap putaran, lalu tambahkan ke output dengan koma.'],
        solution: 'let output = "";\nfor (let i = 1; i <= limit; i++) {\n  let label;\n  if (i % 3 === 0 && i % 5 === 0) label = "TigaLima";\n  else if (i % 3 === 0) label = "Tiga";\n  else if (i % 5 === 0) label = "Lima";\n  else label = String(i);\n  if (output !== "") output += ",";\n  output += label;\n}',
      },
    ],
  },
];
