import type { Part } from './chapter-one';

export const chapter = {
  id: 'objects-arrays',
  title: 'Objek & Array',
  number: '04',
};

export const parts: Part[] = [
  {
    id: 'arrays',
    title: 'Array: daftar nilai',
    description: 'Array menyimpan beberapa nilai dalam satu urutan sehingga data dapat diakses dan diproses sebagai sebuah daftar.',
    highlights: ['array', '[]', 'index', 'length', '[0]'],
    core: 'Array ditulis di antara []. Setiap nilai memiliki index yang dimulai dari 0. Karena itu items[0] mengambil elemen pertama. Properti length memberi jumlah elemen, dan elemen terakhir berada di index length - 1.',
    model: ['["A", "B", "C"]', 'index 0 · 1 · 2', 'length → 3'],
    why: 'Array cocok untuk kumpulan sejenis yang memiliki urutan, seperti daftar nilai, nama peserta, atau langkah proses.',
    example: 'const colors = ["merah", "hijau", "biru"];\nconsole.log(colors[0]);\nconsole.log(colors.length);\nconsole.log(colors[colors.length - 1]);',
    mistake: 'Elemen pertama bukan berada di index 1. JavaScript memulai index array dari 0, sehingga index terakhir selalu satu lebih kecil dari length.',
    exercises: [
      {
        id: 'data-arrays-predict', stage: 'Prediksi', mode: 'console', title: 'Baca index array',
        instruction: 'Pilih nilai yang ditampilkan oleh index 1.',
        starter: 'const cities = ["Jakarta", "Bandung", "Surabaya"];\nconsole.log(cities[1]);',
        options: ['Jakarta', 'Bandung', 'Surabaya', 'undefined'], answer: 'Bandung',
        explanation: 'Index dimulai dari 0. Jakarta berada di 0 dan Bandung berada di 1.',
        tests: [{ name: 'Elemen kedua', inputs: {}, expected: 'Bandung' }],
        hints: ['Hitung posisi mulai dari 0.', 'Urutannya adalah 0: Jakarta, 1: Bandung.'],
        solution: 'const cities = ["Jakarta", "Bandung", "Surabaya"];\nconsole.log(cities[1]);',
      },
      {
        id: 'data-arrays-complete', stage: 'Lengkapi', mode: 'expression', title: 'Ambil elemen terakhir',
        instruction: 'Buat ekspresi yang mengambil elemen terakhir dari array items, berapa pun panjangnya.',
        starter: '// Ambil elemen terakhir\nitems[0]',
        tests: [
          { name: 'Tiga elemen', inputs: { items: ['a', 'b', 'c'] }, expected: 'c' },
          { name: 'Satu elemen', inputs: { items: [42] }, expected: 42 },
        ],
        hints: ['Index terakhir adalah jumlah elemen dikurangi satu.', 'Gunakan items[items.length - 1].'],
        solution: 'items[items.length - 1]',
      },
      {
        id: 'data-arrays-build', stage: 'Bangun', mode: 'function', title: 'Ringkas isi array',
        instruction: 'Buat summarize(items) yang mengembalikan array baru berisi elemen pertama, elemen terakhir, dan jumlah elemen.',
        starter: '// Buat fungsi summarize\n', probe: 'summarize',
        tests: [
          { name: 'Daftar teks', inputs: {}, args: [['pagi', 'siang', 'malam']], expected: ['pagi', 'malam', 3] },
          { name: 'Dua angka', inputs: {}, args: [[8, 13]], expected: [8, 13, 2] },
        ],
        hints: ['Kembalikan sebuah array dengan tiga ekspresi.', 'Elemen terakhir adalah items[items.length - 1].'],
        solution: 'function summarize(items) {\n  return [items[0], items[items.length - 1], items.length];\n}',
      },
    ],
  },
  {
    id: 'objects',
    title: 'Objek: data dengan nama properti',
    description: 'Objek mengelompokkan nilai yang saling berhubungan dan memberi setiap nilai sebuah nama properti.',
    highlights: ['objek', '{}', 'properti', '.', '[]', ':'],
    core: 'Objek ditulis dengan {}. Setiap properti memiliki nama dan nilai yang dipisahkan :. Gunakan titik untuk membaca properti, seperti student.name. Notasi kurung, student["name"], berguna ketika nama properti disimpan dalam variabel.',
    model: ['{ name: "Ayu" }', 'student.name', '"Ayu"'],
    why: 'Objek cocok untuk menggambarkan satu hal dengan beberapa atribut, misalnya seorang mahasiswa dengan nama, semester, dan status aktif.',
    example: 'const student = {\n  name: "Ayu",\n  semester: 2,\n  active: true\n};\nconsole.log(student.name);',
    mistake: 'student.name membaca properti bernama name. student[name] justru mencari nama properti dari nilai variabel name. Gunakan tanda kutip jika menulis nama langsung dalam kurung: student["name"].',
    exercises: [
      {
        id: 'data-objects-predict', stage: 'Prediksi', mode: 'console', title: 'Baca sebuah properti',
        instruction: 'Pilih nilai dari properti level.',
        starter: 'const course = { title: "JavaScript", level: "Dasar" };\nconsole.log(course.level);',
        options: ['course', 'JavaScript', 'Dasar', 'level'], answer: 'Dasar',
        explanation: 'Notasi titik course.level mengambil nilai yang tersimpan pada properti level.',
        tests: [{ name: 'Properti level', inputs: {}, expected: 'Dasar' }],
        hints: ['Lihat pasangan level: nilai di dalam objek.', 'Titik diikuti nama properti yang ingin dibaca.'],
        solution: 'const course = { title: "JavaScript", level: "Dasar" };\nconsole.log(course.level);',
      },
      {
        id: 'data-objects-complete', stage: 'Lengkapi', mode: 'expression', title: 'Properti dinamis',
        instruction: 'Gunakan key untuk membaca properti yang namanya dapat berubah dari objek profile.',
        starter: '// key berisi nama properti\nprofile.key',
        tests: [
          { name: 'Ambil nama', inputs: { profile: { name: 'Nisa', city: 'Bogor' }, key: 'name' }, expected: 'Nisa' },
          { name: 'Ambil kota', inputs: { profile: { name: 'Nisa', city: 'Bogor' }, key: 'city' }, expected: 'Bogor' },
        ],
        hints: ['Notasi titik membaca properti yang benar-benar bernama key.', 'Gunakan profile[key] tanpa tanda kutip di sekitar key.'],
        solution: 'profile[key]',
      },
      {
        id: 'data-objects-build', stage: 'Bangun', mode: 'function', title: 'Buat kartu mahasiswa',
        instruction: 'Buat createStudent(name, semester) yang mengembalikan objek dengan properti name, semester, dan active bernilai true.',
        starter: '// Buat fungsi createStudent\n', probe: 'createStudent',
        tests: [
          { name: 'Mahasiswa pertama', inputs: {}, args: ['Ayu', 2], expected: { name: 'Ayu', semester: 2, active: true } },
          { name: 'Mahasiswa kedua', inputs: {}, args: ['Raka', 5], expected: { name: 'Raka', semester: 5, active: true } },
        ],
        hints: ['Kembalikan objek dengan return { ... };.', 'Pasangan pertamanya adalah name: name, atau cukup name.'],
        solution: 'function createStudent(name, semester) {\n  return { name, semester, active: true };\n}',
      },
    ],
  },
  {
    id: 'modifying-objects',
    title: 'Menambah dan mengubah properti',
    description: 'Isi objek dapat diperbarui dengan assignment, dan properti baru dapat ditambahkan setelah objek dibuat.',
    highlights: ['=', '.', 'delete', 'const', 'properti'],
    core: 'Assignment user.score = 90 mengubah atau menambah properti score. Kata kunci delete user.score menghapus properti tersebut. Variabel objek boleh dibuat dengan const karena yang berubah adalah isinya, bukan variabelnya diarahkan ke objek lain.',
    model: ['objek awal', 'object.key = value', 'objek diperbarui'],
    why: 'Perubahan properti berguna untuk merekam keadaan terbaru, misalnya menambah poin atau menandai tugas selesai.',
    example: 'const task = { title: "Belajar" };\ntask.done = false;\ntask.done = true;\nconsole.log(task.done);',
    mistake: 'const task tidak membuat isi task menjadi tetap. Ia hanya mencegah task = objekBaru. Properti di dalam objek masih dapat diubah.',
    exercises: [
      {
        id: 'data-modify-predict', stage: 'Prediksi', mode: 'console', title: 'Properti yang berubah',
        instruction: 'Pilih nilai terakhir dari properti points.',
        starter: 'const player = { points: 10 };\nplayer.points += 5;\nconsole.log(player.points);',
        options: ['5', '10', '15', 'error'], answer: '15',
        explanation: 'player.points += 5 membaca nilai 10, menambahkan 5, lalu menyimpan 15 pada properti yang sama.',
        tests: [{ name: 'Poin akhir', inputs: {}, expected: '15' }],
        hints: ['const tidak melarang perubahan properti objek.', 'Hitung nilai lama ditambah 5.'],
        solution: 'const player = { points: 10 };\nplayer.points += 5;\nconsole.log(player.points);',
      },
      {
        id: 'data-modify-complete', stage: 'Lengkapi', mode: 'script', title: 'Perbarui profil',
        instruction: 'Ubah profile.city menjadi newCity dan tambahkan profile.verified bernilai true.',
        starter: '// Perbarui objek profile\n', probe: 'profile',
        tests: [
          { name: 'Pindah kota', inputs: { profile: { name: 'Ari', city: 'Solo' }, newCity: 'Malang' }, expected: { name: 'Ari', city: 'Malang', verified: true } },
        ],
        hints: ['Gunakan assignment pada profile.city.', 'Properti baru dibuat dengan profile.verified = true;.'],
        solution: 'profile.city = newCity;\nprofile.verified = true;',
      },
      {
        id: 'data-modify-build', stage: 'Bangun', mode: 'function', title: 'Catat kenaikan stok',
        instruction: 'Buat addStock(product, amount). Tambahkan amount ke product.stock, buat product.available bernilai true jika stok akhirnya > 0, lalu kembalikan product.',
        starter: '// Buat fungsi addStock\n', probe: 'addStock',
        tests: [
          { name: 'Menambah stok kosong', inputs: {}, args: [{ name: 'Buku', stock: 0 }, 4], expected: { name: 'Buku', stock: 4, available: true } },
          { name: 'Jumlah tetap nol', inputs: {}, args: [{ name: 'Pulpen', stock: 0 }, 0], expected: { name: 'Pulpen', stock: 0, available: false } },
        ],
        hints: ['Gunakan product.stock += amount;.', 'Setelah itu isi available dari perbandingan product.stock > 0.'],
        solution: 'function addStock(product, amount) {\n  product.stock += amount;\n  product.available = product.stock > 0;\n  return product;\n}',
      },
    ],
  },
  {
    id: 'mutability-references',
    title: 'Mutability dan referensi',
    description: 'Variabel objek menyimpan referensi menuju objek, sehingga dua variabel dapat menunjuk ke data yang sama.',
    highlights: ['referensi', 'mutability', '===', 'objek', 'array'],
    core: 'Objek dan array bersifat mutable: isinya dapat berubah. Ketika const second = first, keduanya menyimpan referensi yang sama. Perubahan melalui second juga terlihat melalui first. Dua objek terpisah dengan isi serupa tetap tidak sama saat dibandingkan dengan ===.',
    model: ['first ─┐', 'second ─┴→ satu objek', 'ubah lewat salah satu → keduanya melihat'],
    why: 'Memahami referensi mencegah perubahan tak sengaja. Saat fungsi menerima objek, fungsi itu dapat mengubah objek asli milik pemanggil.',
    example: 'const first = { count: 1 };\nconst second = first;\nsecond.count = 2;\nconsole.log(first.count);',
    mistake: '{ value: 1 } === { value: 1 } bernilai false karena keduanya adalah objek berbeda. JavaScript membandingkan identitas referensinya, bukan kesamaan isi.',
    exercises: [
      {
        id: 'data-reference-predict', stage: 'Prediksi', mode: 'console', title: 'Dua nama, satu objek',
        instruction: 'Pilih nilai yang terlihat melalui variabel original.',
        starter: 'const original = { score: 5 };\nconst copy = original;\ncopy.score = 9;\nconsole.log(original.score);',
        options: ['5', '9', 'undefined', 'error'], answer: '9',
        explanation: 'copy dan original menunjuk objek yang sama. Perubahan melalui copy terlihat melalui original.',
        tests: [{ name: 'Referensi yang sama', inputs: {}, expected: '9' }],
        hints: ['Tidak ada objek baru yang dibuat pada const copy = original.', 'Kedua variabel membaca properti dari lokasi data yang sama.'],
        solution: 'const original = { score: 5 };\nconst copy = original;\ncopy.score = 9;\nconsole.log(original.score);',
      },
      {
        id: 'data-reference-complete', stage: 'Lengkapi', mode: 'function', title: 'Periksa referensi',
        instruction: 'Lengkapi sameReference agar mengembalikan hasil perbandingan ketat a === b.',
        starter: 'function sameReference(a, b) {\n  return false;\n}', probe: 'sameReference',
        tests: [
          { name: 'Objek yang sama', inputs: {}, args: (() => { const a = { x: 1 }; return [a, a]; })(), expected: true },
          { name: 'Objek berbeda', inputs: {}, args: [{ x: 1 }, { x: 1 }], expected: false },
        ],
        hints: ['Tidak perlu membandingkan setiap properti.', 'Kembalikan a === b.'],
        solution: 'function sameReference(a, b) {\n  return a === b;\n}',
      },
      {
        id: 'data-reference-build', stage: 'Bangun', mode: 'function', title: 'Perbarui objek dengan sadar',
        instruction: 'Buat markComplete(task). Ubah task.done menjadi true dan kembalikan task yang sama.',
        starter: '// Buat fungsi markComplete\n', probe: 'markComplete',
        tests: [
          { name: 'Tugas belum selesai', inputs: {}, args: [{ title: 'Latihan', done: false }], expected: { title: 'Latihan', done: true } },
          { name: 'Tugas sudah selesai', inputs: {}, args: [{ title: 'Baca', done: true }], expected: { title: 'Baca', done: true } },
        ],
        hints: ['Ubah properti dengan task.done = true;.', 'Kembalikan objek task setelah diperbarui.'],
        solution: 'function markComplete(task) {\n  task.done = true;\n  return task;\n}',
      },
    ],
  },
  {
    id: 'iterating-arrays',
    title: 'Mengulang isi array',
    description: 'Loop memungkinkan setiap elemen array diproses dengan aturan yang sama.',
    highlights: ['for', 'for...of', 'length', 'index', 'of'],
    core: 'for dengan index berguna ketika posisi elemen dibutuhkan. Bentuk for (const item of items) langsung memberikan setiap nilai dan lebih ringkas ketika index tidak diperlukan.',
    model: ['array', 'ambil satu elemen', 'proses → lanjut'],
    why: 'Iterasi mengubah daftar menjadi hasil baru, ringkasan, atau keputusan. Pilih bentuk loop berdasarkan apakah kamu membutuhkan index atau hanya nilainya.',
    example: 'const scores = [80, 90, 70];\nlet total = 0;\nfor (const score of scores) {\n  total += score;\n}\nconsole.log(total);',
    mistake: 'Pada for...of, variabel menerima nilai elemen. Jangan tertukar dengan for...in yang menerima nama properti atau index sebagai teks.',
    exercises: [
      {
        id: 'data-iterate-predict', stage: 'Prediksi', mode: 'console', title: 'Akumulasi nilai',
        instruction: 'Jumlahkan nilai yang diterima score pada setiap putaran.',
        starter: 'const scores = [2, 4, 6];\nlet total = 0;\nfor (const score of scores) {\n  total += score;\n}\nconsole.log(total);',
        options: ['6', '8', '12', '246'], answer: '12',
        explanation: 'for...of mengunjungi 2, 4, dan 6. Semuanya ditambahkan sehingga total menjadi 12.',
        tests: [{ name: 'Jumlah array', inputs: {}, expected: '12' }],
        hints: ['score menerima nilai elemen, bukan index.', 'Hitung 2 + 4 + 6.'],
        solution: 'const scores = [2, 4, 6];\nlet total = 0;\nfor (const score of scores) {\n  total += score;\n}\nconsole.log(total);',
      },
      {
        id: 'data-iterate-complete', stage: 'Lengkapi', mode: 'function', title: 'Jumlahkan semua angka',
        instruction: 'Lengkapi sum(numbers) dengan for...of agar mengembalikan jumlah seluruh elemen.',
        starter: 'function sum(numbers) {\n  let total = 0;\n  // Tambahkan loop\n  return total;\n}', probe: 'sum',
        tests: [
          { name: 'Beberapa angka', inputs: {}, args: [[3, 5, 7]], expected: 15 },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: 0 },
          { name: 'Mengandung negatif', inputs: {}, args: [[10, -4, 2]], expected: 8 },
        ],
        hints: ['Gunakan for (const number of numbers).', 'Di dalam loop, tambahkan number ke total.'],
        solution: 'function sum(numbers) {\n  let total = 0;\n  for (const number of numbers) total += number;\n  return total;\n}',
      },
      {
        id: 'data-iterate-build', stage: 'Bangun', mode: 'function', title: 'Cari nilai terbesar',
        instruction: 'Buat findLargest(numbers). Mulai largest dari numbers[0], periksa elemen lain dengan for...of, lalu kembalikan nilai terbesar.',
        starter: '// Buat fungsi findLargest\n', probe: 'findLargest',
        tests: [
          { name: 'Angka positif', inputs: {}, args: [[4, 12, 7]], expected: 12 },
          { name: 'Semua negatif', inputs: {}, args: [[-8, -2, -11]], expected: -2 },
        ],
        hints: ['Jangan mulai dari 0 karena semua angka bisa negatif.', 'Jika number > largest, perbarui largest.'],
        solution: 'function findLargest(numbers) {\n  let largest = numbers[0];\n  for (const number of numbers) {\n    if (number > largest) largest = number;\n  }\n  return largest;\n}',
      },
    ],
  },
  {
    id: 'array-operations',
    title: 'Operasi dasar array',
    description: 'Method array menyediakan tindakan siap pakai untuk menambah, menghapus, mencari, dan mengambil bagian daftar.',
    highlights: ['push', 'pop', 'includes', 'slice', 'method', '()'],
    core: 'push menambah elemen di akhir dan mengubah array. pop menghapus elemen terakhir. includes memeriksa keberadaan nilai. slice mengambil bagian array sebagai array baru tanpa mengubah sumbernya.',
    model: ['array.method(argumen)', 'method memproses', 'nilai atau array hasil'],
    why: 'Method membuat operasi umum lebih jelas dibanding menulis logikanya dari awal. Periksa apakah sebuah method mengubah array asli atau menghasilkan array baru.',
    example: 'const tasks = ["baca"];\ntasks.push("latihan");\nconst last = tasks.pop();\nconsole.log(last, tasks.length);',
    mistake: 'push mengembalikan panjang array yang baru, bukan arraynya. Jika ingin memakai array setelah push, gunakan kembali variabel array tersebut.',
    exercises: [
      {
        id: 'data-methods-predict', stage: 'Prediksi', mode: 'console', title: 'Hasil push',
        instruction: 'Perhatikan bahwa push mengubah array dan mengembalikan panjang baru.',
        starter: 'const items = ["a", "b"];\nconst result = items.push("c");\nconsole.log(result);\nconsole.log(items.length);',
        options: ['3\n3', 'a,b,c\n3', 'c\n3', '2\n3'], answer: '3\n3',
        explanation: 'Setelah "c" ditambahkan, panjang items menjadi 3. push juga mengembalikan angka 3.',
        tests: [{ name: 'Return push dan length', inputs: {}, expected: '3\n3' }],
        hints: ['push tidak mengembalikan elemen yang ditambahkan.', 'Kedua baris membaca panjang array setelah penambahan.'],
        solution: 'const items = ["a", "b"];\nconst result = items.push("c");\nconsole.log(result);\nconsole.log(items.length);',
      },
      {
        id: 'data-methods-complete', stage: 'Lengkapi', mode: 'function', title: 'Periksa daftar',
        instruction: 'Lengkapi hasItem(items, target) agar mengembalikan boolean dari method includes.',
        starter: 'function hasItem(items, target) {\n  return false;\n}', probe: 'hasItem',
        tests: [
          { name: 'Nilai ditemukan', inputs: {}, args: [['apel', 'jeruk'], 'jeruk'], expected: true },
          { name: 'Nilai tidak ditemukan', inputs: {}, args: [[1, 2, 3], 4], expected: false },
        ],
        hints: ['Panggil method pada items.', 'Kembalikan items.includes(target).'],
        solution: 'function hasItem(items, target) {\n  return items.includes(target);\n}',
      },
      {
        id: 'data-methods-build', stage: 'Bangun', mode: 'function', title: 'Ambil bagian tengah',
        instruction: 'Buat middleItems(items) yang mengembalikan array tanpa elemen pertama dan terakhir menggunakan slice.',
        starter: '// Buat fungsi middleItems\n', probe: 'middleItems',
        tests: [
          { name: 'Empat elemen', inputs: {}, args: [[1, 2, 3, 4]], expected: [2, 3] },
          { name: 'Tiga elemen', inputs: {}, args: [['a', 'b', 'c']], expected: ['b'] },
          { name: 'Dua elemen', inputs: {}, args: [[8, 9]], expected: [] },
        ],
        hints: ['slice menerima index awal dan index akhir yang tidak ikut diambil.', 'Gunakan items.slice(1, -1).'],
        solution: 'function middleItems(items) {\n  return items.slice(1, -1);\n}',
      },
    ],
  },
  {
    id: 'rest-spread',
    title: 'Rest dan spread',
    description: 'Sintaks ... dapat mengumpulkan banyak nilai menjadi satu array atau menyebarkan isi sebuah array ke tempat baru.',
    highlights: ['...', 'rest', 'spread', 'array', 'parameter'],
    core: 'Pada function sum(...numbers), ... adalah rest yang mengumpulkan seluruh argumen menjadi array numbers. Pada const copy = [...items], ... adalah spread yang membuka elemen items ke array baru. Bentuknya sama, perannya ditentukan oleh posisi.',
    model: ['nilai terpisah', '... mengumpulkan / menyebarkan', 'array baru atau parameter'],
    why: 'Rest membuat fungsi menerima jumlah argumen yang fleksibel. Spread memudahkan menggabungkan atau menyalin data tanpa menulis setiap elemen.',
    example: 'function count(...items) { return items.length; }\nconst first = [1, 2];\nconst combined = [...first, 3, 4];\nconsole.log(count(...combined));',
    mistake: 'Spread membuat array luar yang baru, tetapi objek di dalamnya masih dapat berbagi referensi. Ini disebut salinan dangkal, bukan salinan mendalam.',
    exercises: [
      {
        id: 'data-spread-predict', stage: 'Prediksi', mode: 'console', title: 'Sebarkan dua array',
        instruction: 'Pilih urutan elemen pada array baru.',
        starter: 'const first = [1, 2];\nconst second = [3, 4];\nconst all = [...first, 0, ...second];\nconsole.log(all.join(","));',
        options: ['1,2,3,4,0', '1,2,0,3,4', '0,1,2,3,4', 'first,0,second'], answer: '1,2,0,3,4',
        explanation: 'Spread memasukkan elemen first, kemudian 0, lalu elemen second sesuai posisi penulisannya.',
        tests: [{ name: 'Urutan spread', inputs: {}, expected: '1,2,0,3,4' }],
        hints: ['Baca isi [] dari kiri ke kanan.', '...first menjadi 1, 2 dan ...second menjadi 3, 4.'],
        solution: 'const first = [1, 2];\nconst second = [3, 4];\nconst all = [...first, 0, ...second];\nconsole.log(all.join(","));',
      },
      {
        id: 'data-spread-complete', stage: 'Lengkapi', mode: 'function', title: 'Kumpulkan argumen',
        instruction: 'Tambahkan rest parameter agar count menerima berapa pun jumlah argumen dan mengembalikan jumlahnya.',
        starter: 'function count(items) {\n  return items.length;\n}', probe: 'count',
        tests: [
          { name: 'Tiga argumen', inputs: {}, args: ['a', 'b', 'c'], expected: 3 },
          { name: 'Tanpa argumen', inputs: {}, args: [], expected: 0 },
        ],
        hints: ['Tambahkan ... sebelum nama parameter.', 'Daftar parameternya menjadi ...items.'],
        solution: 'function count(...items) {\n  return items.length;\n}',
      },
      {
        id: 'data-spread-build', stage: 'Bangun', mode: 'function', title: 'Gabungkan tanpa mengubah sumber',
        instruction: 'Buat combine(first, second) yang mengembalikan array baru berisi seluruh elemen first, teks "pemisah", lalu seluruh elemen second.',
        starter: '// Buat fungsi combine\n', probe: 'combine',
        tests: [
          { name: 'Dua daftar', inputs: {}, args: [[1, 2], [3, 4]], expected: [1, 2, 'pemisah', 3, 4] },
          { name: 'Daftar kosong', inputs: {}, args: [[], ['x']], expected: ['pemisah', 'x'] },
        ],
        hints: ['Kembalikan array literal baru.', 'Gunakan [...first, "pemisah", ...second].'],
        solution: 'function combine(first, second) {\n  return [...first, "pemisah", ...second];\n}',
      },
    ],
  },
  {
    id: 'destructuring',
    title: 'Destructuring',
    description: 'Destructuring mengambil beberapa nilai dari array atau objek dan memberi mereka nama variabel secara ringkas.',
    highlights: ['destructuring', '[]', '{}', '=', 'properti'],
    core: 'const [first, second] = colors mengambil berdasarkan posisi array. const { name, age } = user mengambil properti dengan nama yang sama. Pola di sebelah kiri = mengikuti bentuk data di sebelah kanan.',
    model: ['data terstruktur', 'pola destructuring', 'variabel terpisah'],
    why: 'Destructuring mengurangi pengulangan ketika hanya beberapa bagian data yang dibutuhkan, terutama pada parameter fungsi.',
    example: 'const point = [4, 7];\nconst [x, y] = point;\nconst user = { name: "Ayu", age: 20 };\nconst { name, age } = user;\nconsole.log(x, y, name, age);',
    mistake: 'Array memakai posisi, sedangkan objek memakai nama properti. Menukar [] dan {} akan menghasilkan cara pengambilan yang berbeda atau error.',
    exercises: [
      {
        id: 'data-destructure-predict', stage: 'Prediksi', mode: 'console', title: 'Lewati posisi array',
        instruction: 'Pilih nilai yang masuk ke variabel third.',
        starter: 'const values = [10, 20, 30];\nconst [, , third] = values;\nconsole.log(third);',
        options: ['10', '20', '30', 'undefined'], answer: '30',
        explanation: 'Dua koma pertama melewati index 0 dan 1. third menerima nilai pada index 2, yaitu 30.',
        tests: [{ name: 'Posisi ketiga', inputs: {}, expected: '30' }],
        hints: ['Setiap koma bergerak ke posisi array berikutnya.', 'third sejajar dengan elemen pada index 2.'],
        solution: 'const values = [10, 20, 30];\nconst [, , third] = values;\nconsole.log(third);',
      },
      {
        id: 'data-destructure-complete', stage: 'Lengkapi', mode: 'function', title: 'Ambil data pengguna',
        instruction: 'Gunakan destructuring objek di parameter fungsi agar formatUser menerima properti name dan city, lalu mengembalikan "name - city".',
        starter: 'function formatUser(user) {\n  return "";\n}', probe: 'formatUser',
        tests: [
          { name: 'Profil pertama', inputs: {}, args: [{ name: 'Sinta', city: 'Medan' }], expected: 'Sinta - Medan' },
          { name: 'Profil kedua', inputs: {}, args: [{ name: 'Bayu', city: 'Solo' }], expected: 'Bayu - Solo' },
        ],
        hints: ['Ganti parameter user dengan { name, city }.', 'Kembalikan name + " - " + city.'],
        solution: 'function formatUser({ name, city }) {\n  return name + " - " + city;\n}',
      },
      {
        id: 'data-destructure-build', stage: 'Bangun', mode: 'function', title: 'Tukar dua posisi',
        instruction: 'Buat swapPair(pair). Gunakan destructuring untuk mengambil first dan second, lalu kembalikan array [second, first].',
        starter: '// Buat fungsi swapPair\n', probe: 'swapPair',
        tests: [
          { name: 'Tukar angka', inputs: {}, args: [[1, 2]], expected: [2, 1] },
          { name: 'Tukar teks', inputs: {}, args: [['kiri', 'kanan']], expected: ['kanan', 'kiri'] },
        ],
        hints: ['Tulis const [first, second] = pair;.', 'Return array baru dengan urutan terbalik.'],
        solution: 'function swapPair(pair) {\n  const [first, second] = pair;\n  return [second, first];\n}',
      },
    ],
  },
  {
    id: 'json',
    title: 'JSON: data dalam bentuk teks',
    description: 'JSON adalah format teks untuk menyimpan atau mengirim data terstruktur antarprogram.',
    highlights: ['JSON.stringify', 'JSON.parse', 'JSON', 'string', 'objek'],
    core: 'JSON.stringify mengubah nilai JavaScript menjadi string JSON. JSON.parse melakukan kebalikannya: membaca string JSON menjadi nilai JavaScript. Nama properti dan string di dalam JSON memakai tanda kutip ganda.',
    model: ['objek JavaScript', 'JSON.stringify', 'teks JSON → JSON.parse → objek'],
    why: 'Jaringan dan penyimpanan sering bekerja dengan teks. JSON menjadi jembatan antara struktur data JavaScript dan format yang mudah dikirim.',
    example: 'const student = { name: "Ayu", active: true };\nconst text = JSON.stringify(student);\nconst restored = JSON.parse(text);\nconsole.log(restored.name);',
    mistake: 'JSON bukan objek; ia adalah teks yang mengikuti aturan tertentu. Kamu perlu JSON.parse sebelum dapat membaca properti dari teks JSON sebagai objek JavaScript.',
    exercises: [
      {
        id: 'data-json-predict', stage: 'Prediksi', mode: 'console', title: 'Dari teks kembali ke objek',
        instruction: 'Pilih nilai properti yang dibaca setelah JSON.parse.',
        starter: 'const text = \'{"course":"JS","parts":4}\';\nconst data = JSON.parse(text);\nconsole.log(data.parts);',
        options: ['4', '"4"', 'parts', 'undefined'], answer: '4',
        explanation: 'JSON.parse mengubah teks menjadi objek. Properti parts di dalam JSON berisi number 4.',
        tests: [{ name: 'Parse angka', inputs: {}, expected: '4' }],
        hints: ['Angka 4 dalam JSON tidak memakai tanda kutip.', 'Setelah parse, data.parts adalah number.'],
        solution: 'const text = \'{"course":"JS","parts":4}\';\nconst data = JSON.parse(text);\nconsole.log(data.parts);',
      },
      {
        id: 'data-json-complete', stage: 'Lengkapi', mode: 'function', title: 'Ubah objek menjadi JSON',
        instruction: 'Lengkapi toJSON(data) agar mengembalikan string JSON dari data.',
        starter: 'function toJSON(data) {\n  return "";\n}', probe: 'toJSON',
        tests: [
          { name: 'Objek sederhana', inputs: {}, args: [{ name: 'Ayu', active: true }], expected: '{"name":"Ayu","active":true}' },
          { name: 'Array angka', inputs: {}, args: [[1, 2, 3]], expected: '[1,2,3]' },
        ],
        hints: ['Gunakan method milik objek global JSON.', 'Kembalikan JSON.stringify(data).'],
        solution: 'function toJSON(data) {\n  return JSON.stringify(data);\n}',
      },
      {
        id: 'data-json-build', stage: 'Bangun', mode: 'function', title: 'Baca dan ringkas JSON',
        instruction: 'Buat summarizeJSON(text). Parse text, lalu kembalikan "name: score" dari properti name dan score.',
        starter: '// Buat fungsi summarizeJSON\n', probe: 'summarizeJSON',
        tests: [
          { name: 'Nilai pertama', inputs: {}, args: ['{"name":"Rani","score":90}'], expected: 'Rani: 90' },
          { name: 'Nilai kedua', inputs: {}, args: ['{"name":"Dito","score":75}'], expected: 'Dito: 75' },
        ],
        hints: ['Mulai dengan const data = JSON.parse(text);.', 'Gabungkan data.name, ": ", dan data.score.'],
        solution: 'function summarizeJSON(text) {\n  const data = JSON.parse(text);\n  return data.name + ": " + data.score;\n}',
      },
    ],
  },
  {
    id: 'data-structure-challenges',
    title: 'Tantangan struktur data',
    description: 'Gabungkan array, objek, loop, dan fungsi untuk mengubah kumpulan data menjadi informasi yang berguna.',
    highlights: ['array', 'objek', 'for...of', 'return', 'properti'],
    core: 'Mulai dengan menentukan bentuk input dan output. Lalu proses satu elemen pada satu waktu: baca properti yang dibutuhkan, perbarui hasil sementara, dan return hasil akhir setelah loop selesai.',
    model: ['array objek', 'iterasi + aturan', 'ringkasan baru'],
    why: 'Program nyata sering bekerja pada daftar objek, misalnya katalog produk atau daftar nilai. Tantangan ini menyatukan konsep yang telah dipelajari.',
    example: 'const products = [{ price: 10000 }, { price: 15000 }];\nlet total = 0;\nfor (const product of products) {\n  total += product.price;\n}\nconsole.log(total);',
    mistake: 'Pastikan nilai awal sesuai jenis hasil: 0 untuk penjumlahan, [] untuk daftar baru, dan {} untuk kumpulan properti. Nilai awal yang salah dapat mengubah seluruh hasil.',
    exercises: [
      {
        id: 'data-challenge-predict', stage: 'Prediksi', mode: 'console', title: 'Jumlah dari daftar objek',
        instruction: 'Jumlahkan properti score dari setiap objek.',
        starter: 'const students = [{ score: 80 }, { score: 70 }, { score: 90 }];\nlet total = 0;\nfor (const student of students) {\n  total += student.score;\n}\nconsole.log(total);',
        options: ['3', '80', '160', '240'], answer: '240',
        explanation: 'Loop membaca score 80, 70, dan 90. Jumlah ketiganya adalah 240.',
        tests: [{ name: 'Total nilai', inputs: {}, expected: '240' }],
        hints: ['Ambil score dari masing-masing student.', 'Hitung 80 + 70 + 90.'],
        solution: 'const students = [{ score: 80 }, { score: 70 }, { score: 90 }];\nlet total = 0;\nfor (const student of students) {\n  total += student.score;\n}\nconsole.log(total);',
      },
      {
        id: 'data-challenge-complete', stage: 'Lengkapi', mode: 'function', title: 'Hitung produk tersedia',
        instruction: 'Lengkapi countAvailable(products). Tambahkan 1 untuk setiap produk yang available bernilai true.',
        starter: 'function countAvailable(products) {\n  let count = 0;\n  // Periksa setiap produk\n  return count;\n}', probe: 'countAvailable',
        tests: [
          { name: 'Sebagian tersedia', inputs: {}, args: [[{ available: true }, { available: false }, { available: true }]], expected: 2 },
          { name: 'Tidak ada yang tersedia', inputs: {}, args: [[{ available: false }]], expected: 0 },
        ],
        hints: ['Gunakan for...of untuk mengunjungi products.', 'Di dalam loop, jika product.available, naikkan count.'],
        solution: 'function countAvailable(products) {\n  let count = 0;\n  for (const product of products) {\n    if (product.available) count++;\n  }\n  return count;\n}',
      },
      {
        id: 'data-challenge-build', stage: 'Bangun', mode: 'function', title: 'Kelompokkan nama berdasarkan status',
        instruction: 'Buat groupStudents(students). Kembalikan objek { active: [], inactive: [] }. Masukkan name ke array yang sesuai berdasarkan properti active.',
        starter: '// Buat fungsi groupStudents\n', probe: 'groupStudents',
        tests: [
          { name: 'Status campuran', inputs: {}, args: [[{ name: 'Ayu', active: true }, { name: 'Bima', active: false }, { name: 'Cici', active: true }]], expected: { active: ['Ayu', 'Cici'], inactive: ['Bima'] } },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: { active: [], inactive: [] } },
        ],
        hints: ['Mulai dengan const groups = { active: [], inactive: [] };.', 'Dalam loop, push student.name ke array sesuai kondisi, lalu return groups.'],
        solution: 'function groupStudents(students) {\n  const groups = { active: [], inactive: [] };\n  for (const student of students) {\n    if (student.active) groups.active.push(student.name);\n    else groups.inactive.push(student.name);\n  }\n  return groups;\n}',
      },
    ],
  },
];
