import type { Part } from './chapter-one';

export const chapter = {
  id: 'bugs-errors',
  title: 'Bug & Error',
  number: '08',
};

export const parts: Part[] = [
  {
    id: 'failure-kinds',
    title: 'Mengenali jenis kegagalan',
    description: 'Bug dapat menghentikan program dengan error atau membiarkannya berjalan sambil menghasilkan nilai yang salah.',
    highlights: ['bug', 'SyntaxError', 'ReferenceError', 'TypeError', 'NaN', 'strict mode'],
    core: 'Syntax error melanggar tata bahasa dan ditemukan sebelum kode berjalan. Runtime error muncul ketika operasi dijalankan, misalnya memanggil nilai yang bukan fungsi. Kegagalan paling sulit adalah hasil salah seperti NaN atau undefined yang terus mengalir tanpa langsung menghentikan program.',
    model: ['gejala terlihat', 'kenali jenis kegagalan', 'cari sumber pertama'],
    why: 'Klasifikasi awal menentukan langkah debugging. Pesan error perlu dibaca, sedangkan hasil salah perlu dilacak mundur sampai titik pertama nilai menyimpang.',
    example: '"use strict";\nfunction priceTotal(price, qty) {\n  return Number(price) * qty;\n}\nconsole.log(priceTotal("x", 2)); // NaN',
    mistake: 'Baris yang melempar error belum tentu sumber bug. Nilai rusak mungkin dibuat lebih awal lalu baru menyebabkan error ketika dipakai oleh fungsi lain.',
    exercises: [
      {
        id: 'errors-kinds-predict', stage: 'Prediksi', mode: 'console', title: 'Error atau nilai salah?',
        instruction: 'Pilih hasil operasi yang tidak melempar, tetapi menghasilkan nilai angka yang tidak valid.',
        starter: 'console.log(Number("apel") * 2);',
        options: ['0', 'NaN', 'TypeError', 'undefined'], answer: 'NaN',
        explanation: 'Number("apel") menghasilkan NaN. Perkalian tetap berjalan dan hasilnya juga NaN.',
        tests: [{ name: 'Nilai tidak valid', inputs: {}, expected: 'NaN' }],
        hints: ['Konversi teks ini tidak menghasilkan angka.', 'JavaScript memakai NaN untuk hasil numerik yang tidak valid.'],
        solution: 'console.log(Number("apel") * 2);',
      },
      {
        id: 'errors-kinds-complete', stage: 'Lengkapi', mode: 'function', title: 'Hentikan nilai rusak',
        instruction: 'Lengkapi parseQuantity(value). Kembalikan angka jika hasil Number(value) finite; selain itu kembalikan null.',
        starter: 'function parseQuantity(value) {\n  const number = Number(value);\n  return number;\n}', probe: 'parseQuantity',
        tests: [
          { name: 'Angka teks', inputs: {}, args: ['12'], expected: 12 },
          { name: 'Teks invalid', inputs: {}, args: ['dua'], expected: null },
          { name: 'Infinity ditolak', inputs: {}, args: [Infinity], expected: null },
        ],
        hints: ['Gunakan Number.isFinite(number).', 'Pilih number atau null berdasarkan pemeriksaan itu.'],
        solution: 'function parseQuantity(value) {\n  const number = Number(value);\n  return Number.isFinite(number) ? number : null;\n}',
      },
      {
        id: 'errors-kinds-build', stage: 'Bangun', mode: 'function', title: 'Klasifikasikan hasil program',
        instruction: 'Buat classify(value). Kembalikan "missing" untuk undefined, "invalid-number" untuk NaN, dan "ok" untuk nilai lain.',
        starter: '// Buat fungsi classify\n', probe: 'classify',
        tests: [
          { name: 'Tidak tersedia', inputs: {}, args: [undefined], expected: 'missing' },
          { name: 'NaN', inputs: {}, args: [NaN], expected: 'invalid-number' },
          { name: 'Nilai normal', inputs: {}, args: [0], expected: 'ok' },
        ],
        hints: ['Periksa value === undefined lebih dahulu.', 'Gunakan Number.isNaN(value) untuk kasus kedua.'],
        solution: 'function classify(value) {\n  if (value === undefined) return "missing";\n  if (Number.isNaN(value)) return "invalid-number";\n  return "ok";\n}',
      },
    ],
  },
  {
    id: 'contracts-validation',
    title: 'Kontrak input dan output',
    description: 'Kontrak fungsi menjelaskan bentuk nilai yang diterima, aturan yang berlaku, dan hasil yang dijanjikan.',
    highlights: ['kontrak', 'validasi', 'typeof', 'Array.isArray', 'Number.isFinite'],
    core: 'JavaScript tidak memeriksa tipe sebelum program berjalan. Karena itu, validasi pada batas fungsi membantu mencegah data buruk masuk lebih jauh. Kontrak yang jelas juga membuat test dan pesan error lebih terarah.',
    model: ['input masuk', 'validasi kontrak', 'proses nilai tepercaya'],
    why: 'Memeriksa data sekali di batas sistem lebih aman daripada membiarkan setiap langkah menebak bentuk data yang diterimanya.',
    example: 'function square(number) {\n  if (!Number.isFinite(number)) throw new TypeError("number harus finite");\n  return number * number;\n}',
    mistake: 'typeof NaN adalah "number" dan typeof null adalah "object". Pemeriksaan tipe dasar sering perlu digabung dengan pemeriksaan yang lebih spesifik.',
    exercises: [
      {
        id: 'errors-contract-predict', stage: 'Prediksi', mode: 'console', title: 'typeof belum cukup',
        instruction: 'Pilih dua hasil pemeriksaan pada NaN.',
        starter: 'console.log(typeof NaN);\nconsole.log(Number.isFinite(NaN));',
        options: ['number\nfalse', 'number\ntrue', 'undefined\nfalse', 'NaN\nfalse'], answer: 'number\nfalse',
        explanation: 'NaN termasuk tipe number, tetapi bukan angka finite yang dapat dipakai untuk perhitungan normal.',
        tests: [{ name: 'Tipe dan validitas NaN', inputs: {}, expected: 'number\nfalse' }],
        hints: ['typeof hanya melihat tipe dasarnya.', 'Number.isFinite menolak NaN.'],
        solution: 'console.log(typeof NaN);\nconsole.log(Number.isFinite(NaN));',
      },
      {
        id: 'errors-contract-complete', stage: 'Lengkapi', mode: 'function', title: 'Rata-rata dengan kontrak',
        instruction: 'Lengkapi average(numbers). Kembalikan null jika input bukan array, kosong, atau memiliki nilai non-finite; selain itu kembalikan rata-rata.',
        starter: 'function average(numbers) {\n  // Validasi sebelum menghitung\n  return 0;\n}', probe: 'average',
        tests: [
          { name: 'Array valid', inputs: {}, args: [[4, 6, 8]], expected: 6 },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: null },
          { name: 'Nilai invalid', inputs: {}, args: [[2, NaN]], expected: null },
          { name: 'Bukan array', inputs: {}, args: ['2,4'], expected: null },
        ],
        hints: ['Gunakan Array.isArray dan numbers.length.', 'Periksa semua elemen dengan every(Number.isFinite).'],
        solution: 'function average(numbers) {\n  if (!Array.isArray(numbers) || numbers.length === 0) return null;\n  if (!numbers.every(Number.isFinite)) return null;\n  return numbers.reduce((sum, number) => sum + number, 0) / numbers.length;\n}',
      },
      {
        id: 'errors-contract-build', stage: 'Bangun', mode: 'function', title: 'Normalisasi pengguna',
        instruction: 'Buat normalizeUser(value). Kembalikan null kecuali value adalah objek dengan name berupa string tidak kosong dan age berupa integer >= 0. Hasil valid adalah objek baru dengan name yang sudah trim dan age.',
        starter: '// Buat fungsi normalizeUser\n', probe: 'normalizeUser',
        tests: [
          { name: 'Profil valid', inputs: {}, args: [{ name: '  Ayu ', age: 20 }], expected: { name: 'Ayu', age: 20 } },
          { name: 'Nama kosong', inputs: {}, args: [{ name: ' ', age: 20 }], expected: null },
          { name: 'Umur salah', inputs: {}, args: [{ name: 'Ayu', age: 2.5 }], expected: null },
          { name: 'Nilai null', inputs: {}, args: [null], expected: null },
        ],
        hints: ['Periksa value !== null dan typeof value === "object".', 'Gunakan name.trim(), Number.isInteger(age), dan age >= 0.'],
        solution: 'function normalizeUser(value) {\n  if (value === null || typeof value !== "object") return null;\n  if (typeof value.name !== "string" || value.name.trim() === "") return null;\n  if (!Number.isInteger(value.age) || value.age < 0) return null;\n  return { name: value.name.trim(), age: value.age };\n}',
      },
    ],
  },
  {
    id: 'automated-testing',
    title: 'Testing otomatis',
    description: 'Test menjalankan perilaku program berulang kali dan membandingkan hasil aktual dengan hasil yang diharapkan.',
    highlights: ['test', 'expected', 'actual', 'regression', 'edge case'],
    core: 'Test yang baik mencakup kasus normal, batas, dan input buruk yang relevan. Ketika perubahan merusak perilaku lama, test menangkap regression dengan cepat. Fungsi murni biasanya paling mudah diuji karena input dan outputnya eksplisit.',
    model: ['siapkan kasus', 'jalankan fungsi', 'bandingkan expected dan actual'],
    why: 'Pengujian manual sulit diulang dengan konsisten. Test otomatis mengubah contoh penting menjadi pemeriksaan yang dapat dijalankan setiap kali kode berubah.',
    example: 'function testEqual(actual, expected) {\n  return Object.is(actual, expected);\n}\nconsole.log(testEqual(Math.max(2, 5), 5));',
    mistake: 'Banyak test tidak otomatis berarti perlindungan yang baik. Test harus memeriksa perilaku penting, termasuk batas yang paling mungkin menimbulkan bug.',
    exercises: [
      {
        id: 'errors-test-predict', stage: 'Prediksi', mode: 'console', title: 'Kasus batas menemukan bug',
        instruction: 'Implementasi ini salah untuk angka negatif ganjil. Pilih hasil test.',
        starter: 'function isEven(n) { return n % 2 === 0; }\nconsole.log(isEven(4));\nconsole.log(isEven(-3));',
        options: ['true\nfalse', 'true\ntrue', 'false\nfalse', 'false\ntrue'], answer: 'true\nfalse',
        explanation: 'Sisa -3 dibagi 2 adalah -1, sehingga perbandingan dengan 0 false. Implementasi ini tetap benar untuk kasus tersebut.',
        tests: [{ name: 'Positif dan negatif', inputs: {}, expected: 'true\nfalse' }],
        hints: ['Hitung 4 % 2 dan -3 % 2.', 'Hanya sisa 0 yang genap.'],
        solution: 'function isEven(n) { return n % 2 === 0; }\nconsole.log(isEven(4));\nconsole.log(isEven(-3));',
      },
      {
        id: 'errors-test-complete', stage: 'Lengkapi', mode: 'function', title: 'Bandingkan hasil dengan aman',
        instruction: 'Lengkapi testCases(fn, cases). Kembalikan array boolean yang membandingkan fn(input) dengan expected memakai Object.is.',
        starter: 'function testCases(fn, cases) {\n  return [];\n}', probe: '(() => testCases(n => Math.min(10, Math.max(0, n)), [{ input: -1, expected: 0 }, { input: 5, expected: 5 }, { input: 12, expected: 10 }]))',
        tests: [{ name: 'Tiga kasus clamp', inputs: {}, expected: [true, true, true] }],
        hints: ['Gunakan cases.map(...).', 'Bandingkan fn(item.input) dengan item.expected.'],
        solution: 'function testCases(fn, cases) {\n  return cases.map(item => Object.is(fn(item.input), item.expected));\n}',
      },
      {
        id: 'errors-test-build', stage: 'Bangun', mode: 'function', title: 'Mini test runner',
        instruction: 'Buat runTests(tests). Setiap test memiliki name, actual, expected. Kembalikan { passed, failed, failures } dengan failures berisi nama test yang tidak sama menurut Object.is.',
        starter: '// Buat fungsi runTests\n', probe: 'runTests',
        tests: [
          { name: 'Ada satu kegagalan', inputs: {}, args: [[{ name: 'a', actual: 2, expected: 2 }, { name: 'b', actual: 3, expected: 4 }]], expected: { passed: 1, failed: 1, failures: ['b'] } },
          { name: 'Semua lulus', inputs: {}, args: [[{ name: 'nan', actual: NaN, expected: NaN }]], expected: { passed: 1, failed: 0, failures: [] } },
        ],
        hints: ['Filter nama test yang actual dan expected-nya tidak Object.is.', 'passed adalah total test dikurangi failures.length.'],
        solution: 'function runTests(tests) {\n  const failures = tests.filter(test => !Object.is(test.actual, test.expected)).map(test => test.name);\n  return { passed: tests.length - failures.length, failed: failures.length, failures };\n}',
      },
    ],
  },
  {
    id: 'debugging-traces',
    title: 'Debugging dengan hipotesis',
    description: 'Debugging yang efektif menguji dugaan dengan mengamati nilai pada titik yang sengaja dipilih.',
    highlights: ['debugging', 'hipotesis', 'trace', 'breakpoint', 'Math.floor'],
    core: 'Mulai dari gejala, bentuk dugaan tentang penyebab, lalu cari bukti. Log atau breakpoint membantu menemukan titik pertama ketika nilai berbeda dari harapan. Hindari perubahan acak karena perubahan itu menambah variabel baru tanpa menjelaskan sumber masalah.',
    model: ['amati gejala', 'buat hipotesis', 'ukur nilai antara', 'perbaiki sumber'],
    why: 'Jejak nilai mengubah dugaan kabur menjadi pertanyaan konkret: pada iterasi mana nilai salah, dan operasi apa yang baru saja terjadi?',
    example: 'function digits(number) {\n  const trace = [];\n  while (number > 0) {\n    trace.push(number);\n    number = Math.floor(number / 10);\n  }\n  return trace;\n}',
    mistake: 'Menambah banyak console.log tanpa pertanyaan yang jelas menghasilkan kebisingan. Catat nilai yang dapat membuktikan atau membantah hipotesismu.',
    exercises: [
      {
        id: 'errors-debug-predict', stage: 'Prediksi', mode: 'console', title: 'Temukan langkah yang menyimpang',
        instruction: 'Perhatikan pembagian yang tidak dibulatkan. Pilih nilai n setelah satu iterasi.',
        starter: 'let n = 13;\nn = n / 10;\nconsole.log(n);',
        options: ['0', '1', '1.3', '3'], answer: '1.3',
        explanation: 'Pembagian biasa mempertahankan pecahan. Algoritma digit biasanya membutuhkan Math.floor agar n menjadi 1.',
        tests: [{ name: 'Nilai setelah pembagian', inputs: {}, expected: '1.3' }],
        hints: ['Operator / tidak membulatkan.', '13 dibagi 10 adalah 1.3.'],
        solution: 'let n = 13;\nn = n / 10;\nconsole.log(n);',
      },
      {
        id: 'errors-debug-complete', stage: 'Lengkapi', mode: 'function', title: 'Ambil digit dengan benar',
        instruction: 'Perbaiki decimalDigits(number) agar membuang bagian pecahan setelah membagi 10 dan mengembalikan digit dari kiri ke kanan.',
        starter: 'function decimalDigits(number) {\n  const result = [];\n  do {\n    result.unshift(number % 10);\n    number = number / 10;\n  } while (number > 0);\n  return result;\n}', probe: 'decimalDigits',
        tests: [
          { name: 'Tiga digit', inputs: {}, args: [307], expected: [3, 0, 7] },
          { name: 'Satu digit', inputs: {}, args: [5], expected: [5] },
          { name: 'Nol', inputs: {}, args: [0], expected: [0] },
        ],
        hints: ['Sisa pembagian juga perlu menjadi integer.', 'Gunakan Math.floor pada number % 10 dan number / 10.'],
        solution: 'function decimalDigits(number) {\n  const result = [];\n  do {\n    result.unshift(Math.floor(number % 10));\n    number = Math.floor(number / 10);\n  } while (number > 0);\n  return result;\n}',
      },
      {
        id: 'errors-debug-build', stage: 'Bangun', mode: 'function', title: 'Jejak binary search',
        instruction: 'Buat traceBinarySearch(items, target). Kembalikan { index, steps }; steps berisi index tengah yang diperiksa. Return index -1 jika tidak ditemukan.',
        starter: '// Buat traceBinarySearch untuk array terurut\n', probe: 'traceBinarySearch',
        tests: [
          { name: 'Ditemukan', inputs: {}, args: [[1, 3, 5, 7, 9], 7], expected: { index: 3, steps: [2, 3] } },
          { name: 'Tidak ditemukan', inputs: {}, args: [[2, 4, 6], 5], expected: { index: -1, steps: [1, 2] } },
        ],
        hints: ['Gunakan low = 0 dan high = items.length - 1.', 'Catat middle sebelum membandingkan, lalu geser low atau high.'],
        solution: 'function traceBinarySearch(items, target) {\n  let low = 0, high = items.length - 1;\n  const steps = [];\n  while (low <= high) {\n    const middle = Math.floor((low + high) / 2);\n    steps.push(middle);\n    if (items[middle] === target) return { index: middle, steps };\n    if (items[middle] < target) low = middle + 1;\n    else high = middle - 1;\n  }\n  return { index: -1, steps };\n}',
      },
    ],
  },
  {
    id: 'failure-as-data',
    title: 'Kegagalan sebagai data',
    description: 'Kegagalan rutin dapat dinyatakan sebagai nilai terstruktur agar pemanggil wajib mempertimbangkannya.',
    highlights: ['result object', 'ok', 'value', 'error', 'sentinel'],
    core: 'Nilai sentinel seperti -1 atau null dapat ambigu. Result object seperti { ok: true, value } dan { ok: false, error } membawa status dan konteks secara eksplisit. Pendekatan ini cocok untuk kegagalan yang normal dan dapat ditangani dekat pemanggil.',
    model: ['operasi', 'sukses atau gagal', 'pemanggil memilih cabang'],
    why: 'Membuat kegagalan terlihat pada bentuk hasil mencegah pemanggil memakai nilai gagal seolah-olah hasil normal.',
    example: 'function safeDivide(a, b) {\n  if (b === 0) return { ok: false, error: "division-by-zero" };\n  return { ok: true, value: a / b };\n}',
    mistake: 'Jangan mencampur beberapa bentuk kegagalan tanpa aturan, misalnya kadang null dan kadang throw untuk situasi rutin yang sama.',
    exercises: [
      {
        id: 'errors-result-predict', stage: 'Prediksi', mode: 'console', title: 'Baca status hasil',
        instruction: 'Pilih pesan yang ditampilkan ketika ok bernilai false.',
        starter: 'const result = { ok: false, error: "not-found" };\nconsole.log(result.ok ? result.value : "Gagal: " + result.error);',
        options: ['not-found', 'Gagal: not-found', 'undefined', 'false'], answer: 'Gagal: not-found',
        explanation: 'Kondisi result.ok false memilih cabang setelah titik dua dan memakai properti error.',
        tests: [{ name: 'Cabang gagal', inputs: {}, expected: 'Gagal: not-found' }],
        hints: ['Lihat nilai result.ok.', 'Ternary memilih cabang false.'],
        solution: 'const result = { ok: false, error: "not-found" };\nconsole.log(result.ok ? result.value : "Gagal: " + result.error);',
      },
      {
        id: 'errors-result-complete', stage: 'Lengkapi', mode: 'function', title: 'Pembagian yang eksplisit',
        instruction: 'Lengkapi safeDivide(a, b). Untuk pembagi nol kembalikan { ok: false, error: "division-by-zero" }; selain itu { ok: true, value: a / b }.',
        starter: 'function safeDivide(a, b) {\n  return { ok: true, value: a / b };\n}', probe: 'safeDivide',
        tests: [
          { name: 'Berhasil', inputs: {}, args: [12, 3], expected: { ok: true, value: 4 } },
          { name: 'Pembagi nol', inputs: {}, args: [12, 0], expected: { ok: false, error: 'division-by-zero' } },
        ],
        hints: ['Tangani b === 0 lebih dahulu.', 'Gunakan return awal untuk hasil gagal.'],
        solution: 'function safeDivide(a, b) {\n  if (b === 0) return { ok: false, error: "division-by-zero" };\n  return { ok: true, value: a / b };\n}',
      },
      {
        id: 'errors-result-build', stage: 'Bangun', mode: 'function', title: 'Parse nomor port',
        instruction: 'Buat parsePort(text). Kembalikan error "not-integer" jika teks bukan bentuk integer murni, "out-of-range" jika di luar 1..65535, atau hasil ok dengan value angka.',
        starter: '// Buat fungsi parsePort\n', probe: 'parsePort',
        tests: [
          { name: 'Port valid', inputs: {}, args: ['8080'], expected: { ok: true, value: 8080 } },
          { name: 'Bukan integer', inputs: {}, args: ['80.5'], expected: { ok: false, error: 'not-integer' } },
          { name: 'Teks campuran', inputs: {}, args: ['80x'], expected: { ok: false, error: 'not-integer' } },
          { name: 'Di luar rentang', inputs: {}, args: ['70000'], expected: { ok: false, error: 'out-of-range' } },
        ],
        hints: ['Uji bentuk teks dengan /^\\d+$/.', 'Setelah Number(text), periksa rentang 1 sampai 65535.'],
        solution: 'function parsePort(text) {\n  if (!/^\\d+$/.test(text)) return { ok: false, error: "not-integer" };\n  const value = Number(text);\n  if (value < 1 || value > 65535) return { ok: false, error: "out-of-range" };\n  return { ok: true, value };\n}',
      },
    ],
  },
  {
    id: 'exceptions',
    title: 'Exception dan try/catch',
    description: 'Exception menghentikan alur normal dan mencari catch terdekat yang dapat menangani masalah.',
    highlights: ['throw', 'Error', 'try', 'catch', 'stack'],
    core: 'throw dapat mengirim Error melewati beberapa lapisan pemanggilan. Stack dibuka sampai sebuah try/catch menangkapnya. Lempar Error, bukan sekadar string, agar message dan stack trace membantu menemukan konteks kegagalan.',
    model: ['throw di dalam', 'stack dibuka', 'catch di batas penanganan'],
    why: 'Exception memisahkan kode alur sukses dari penanganan kegagalan yang tidak dapat diselesaikan secara lokal.',
    example: 'function requireName(name) {\n  if (!name) throw new Error("name required");\n  return name;\n}\ntry { requireName(""); } catch (error) { console.log(error.message); }',
    mistake: 'catch yang mengabaikan semua error dapat menyembunyikan typo dan bug programmer. Tangani hanya masalah yang benar-benar dapat dipulihkan.',
    exercises: [
      {
        id: 'errors-exception-predict', stage: 'Prediksi', mode: 'console', title: 'Stack berpindah ke catch',
        instruction: 'Pilih urutan log ketika fungsi terdalam melempar.',
        starter: 'function inner() { throw new Error("boom"); }\nfunction outer() { console.log("before"); inner(); console.log("after"); }\ntry { outer(); } catch (error) { console.log(error.message); }\nconsole.log("done");',
        options: ['before\nafter\ndone', 'before\nboom\ndone', 'boom\nbefore\ndone', 'before\ndone\nboom'], answer: 'before\nboom\ndone',
        explanation: 'throw melewati sisa outer, jadi "after" tidak dicetak. catch mencetak pesan, lalu program berlanjut ke "done".',
        tests: [{ name: 'Urutan exception', inputs: {}, expected: 'before\nboom\ndone' }],
        hints: ['Kode setelah throw pada jalur yang sama dilewati.', 'Setelah catch selesai, eksekusi berlanjut.'],
        solution: 'function inner() { throw new Error("boom"); }\nfunction outer() { console.log("before"); inner(); console.log("after"); }\ntry { outer(); } catch (error) { console.log(error.message); }\nconsole.log("done");',
      },
      {
        id: 'errors-exception-complete', stage: 'Lengkapi', mode: 'script', title: 'Lempar RangeError',
        instruction: 'Lengkapi requirePositive(n) agar melempar RangeError berpesan "must be positive" untuk n <= 0.',
        starter: 'function requirePositive(n) {\n  return n;\n}', probe: '(() => { try { requirePositive(value); return "ok"; } catch (error) { return [error instanceof RangeError, error.message]; } })()',
        tests: [
          { name: 'Nilai valid', inputs: { value: 4 }, expected: 'ok' },
          { name: 'Nol ditolak', inputs: { value: 0 }, expected: [true, 'must be positive'] },
          { name: 'Negatif ditolak', inputs: { value: -2 }, expected: [true, 'must be positive'] },
        ],
        hints: ['Periksa n <= 0.', 'Tulis throw new RangeError("must be positive").'],
        solution: 'function requirePositive(n) {\n  if (n <= 0) throw new RangeError("must be positive");\n  return n;\n}',
      },
      {
        id: 'errors-exception-build', stage: 'Bangun', mode: 'function', title: 'Tangani pada batas luar',
        instruction: 'Buat processPrice(value). Di dalam try, lempar TypeError("invalid price") kecuali value finite dan >= 0; hasil valid adalah value * 1.1. Di catch, kembalikan { ok: false, error: error.message }; hasil valid berbentuk { ok: true, value }.',
        starter: '// Buat fungsi processPrice\n', probe: 'processPrice',
        tests: [
          { name: 'Harga valid', inputs: {}, args: [100], expected: { ok: true, value: 110 } },
          { name: 'Harga negatif', inputs: {}, args: [-1], expected: { ok: false, error: 'invalid price' } },
          { name: 'NaN', inputs: {}, args: [NaN], expected: { ok: false, error: 'invalid price' } },
        ],
        hints: ['Gunakan satu try/catch di fungsi terluar.', 'Periksa Number.isFinite(value) dan value >= 0.'],
        solution: 'function processPrice(value) {\n  try {\n    if (!Number.isFinite(value) || value < 0) throw new TypeError("invalid price");\n    return { ok: true, value: Math.round(value * 110) / 100 };\n  } catch (error) {\n    return { ok: false, error: error.message };\n  }\n}',
      },
    ],
  },
  {
    id: 'finally-cleanup',
    title: 'Menjaga keadaan dengan finally',
    description: 'Blok finally tetap berjalan setelah try, baik operasi berhasil, return, maupun melempar error.',
    highlights: ['finally', 'cleanup', 'rollback', 'try', 'return'],
    core: 'Alur exception dapat meninggalkan resource atau state dalam keadaan setengah berubah. finally menyediakan tempat untuk cleanup yang selalu dijalankan. Jika beberapa perubahan membentuk satu transaksi, catat keadaan awal atau tahap kemajuan agar kegagalan dapat di-rollback.',
    model: ['simpan keadaan awal', 'coba operasi', 'finally memulihkan atau membersihkan'],
    why: 'Cleanup yang terjamin menjaga invariant program meskipun operasi berhenti di tengah jalan.',
    example: 'let busy = false;\ntry { busy = true; /* work */ } finally { busy = false; }',
    mistake: 'Return di dalam finally menimpa return atau exception dari try. Hindari return dan throw baru di blok cleanup kecuali benar-benar disengaja.',
    exercises: [
      {
        id: 'errors-finally-predict', stage: 'Prediksi', mode: 'console', title: 'Finally selalu mendapat giliran',
        instruction: 'Pilih urutan keluaran ketika try melempar.',
        starter: 'try {\n  console.log("work");\n  throw new Error("stop");\n} catch (error) {\n  console.log("catch");\n} finally {\n  console.log("cleanup");\n}',
        options: ['work\ncatch\ncleanup', 'work\ncleanup', 'catch\ncleanup', 'work\ncleanup\ncatch'], answer: 'work\ncatch\ncleanup',
        explanation: 'catch menangani error, lalu finally tetap berjalan sebagai langkah terakhir.',
        tests: [{ name: 'Catch dan cleanup', inputs: {}, expected: 'work\ncatch\ncleanup' }],
        hints: ['Error ditangani oleh catch.', 'finally berjalan sesudah try/catch.'],
        solution: 'try {\n  console.log("work");\n  throw new Error("stop");\n} catch (error) {\n  console.log("catch");\n} finally {\n  console.log("cleanup");\n}',
      },
      {
        id: 'errors-finally-complete', stage: 'Lengkapi', mode: 'script', title: 'Pulihkan flag',
        instruction: 'Lengkapi withFlag(state, body). Simpan state.busy, set true saat body berjalan, lalu pulihkan nilai awal dengan finally. Kembalikan hasil body.',
        starter: 'function withFlag(state, body) {\n  state.busy = true;\n  return body();\n}', probe: '(() => { const state = { busy: initial }; try { const value = withFlag(state, () => { if (fails) throw new Error("fail"); return "done"; }); return [value, state.busy]; } catch (error) { return [error.message, state.busy]; } })()',
        tests: [
          { name: 'Sukses dari false', inputs: { initial: false, fails: false }, expected: ['done', false] },
          { name: 'Gagal tetap pulih', inputs: { initial: false, fails: true }, expected: ['fail', false] },
          { name: 'Nilai awal true', inputs: { initial: true, fails: false }, expected: ['done', true] },
        ],
        hints: ['Simpan const previous = state.busy.', 'Gunakan try { return body(); } finally { state.busy = previous; }.'],
        solution: 'function withFlag(state, body) {\n  const previous = state.busy;\n  state.busy = true;\n  try {\n    return body();\n  } finally {\n    state.busy = previous;\n  }\n}',
      },
      {
        id: 'errors-finally-build', stage: 'Bangun', mode: 'function', title: 'Transfer atomik',
        instruction: 'Buat transfer(accounts, from, to, amount). Lempar Error("invalid account") jika akun tidak ada dan Error("insufficient") jika saldo kurang. Jangan ubah saldo bila validasi gagal; hasil sukses mengembalikan accounts.',
        starter: '// Buat fungsi transfer\n', probe: 'transfer',
        tests: [
          { name: 'Transfer berhasil', inputs: {}, args: [{ a: 100, b: 20 }, 'a', 'b', 30], expected: { a: 70, b: 50 } },
          { name: 'Akun invalid tidak berubah', inputs: {}, args: [{ a: 100, b: 20 }, 'a', 'x', 30], expected: { a: 100, b: 20 } },
          { name: 'Saldo kurang tidak berubah', inputs: {}, args: [{ a: 10, b: 20 }, 'a', 'b', 30], expected: { a: 10, b: 20 } },
        ],
        hints: ['Agar test kegagalan mengembalikan objek, tangkap error di dalam fungsi setelah validasi.', 'Validasi kedua akun dan saldo sebelum melakukan perubahan pertama.'],
        solution: 'function transfer(accounts, from, to, amount) {\n  try {\n    if (!Object.hasOwn(accounts, from) || !Object.hasOwn(accounts, to)) throw new Error("invalid account");\n    if (accounts[from] < amount) throw new Error("insufficient");\n    accounts[from] -= amount;\n    accounts[to] += amount;\n  } catch (error) {\n    return accounts;\n  }\n  return accounts;\n}',
      },
    ],
  },
  {
    id: 'selective-errors',
    title: 'Error khusus dan assertion',
    description: 'Subclass Error membantu catch membedakan kegagalan yang dapat dipulihkan dari bug yang harus diteruskan.',
    highlights: ['extends Error', 'instanceof', 'rethrow', 'assertion', 'invariant'],
    core: 'Catch menerima semua exception dari blok try. Periksa error dengan instanceof dan lempar kembali error yang tidak dikenal. Assertion adalah pemeriksaan untuk pelanggaran asumsi programmer, bukan pengganti validasi input pengguna.',
    model: ['catch error', 'kenali tipenya', 'pulihkan atau rethrow'],
    why: 'Penanganan selektif mencegah kode menutupi bug yang tidak berkaitan dengan masalah yang ingin ditangani.',
    example: 'class ValidationError extends Error {}\ntry { /* work */ } catch (error) {\n  if (!(error instanceof ValidationError)) throw error;\n}',
    mistake: 'Membandingkan teks message rapuh karena pesan dapat berubah. Gunakan class error, properti code, atau bentuk terstruktur yang stabil.',
    exercises: [
      {
        id: 'errors-selective-predict', stage: 'Prediksi', mode: 'console', title: 'Tangani tipe yang tepat',
        instruction: 'Pilih hasil pemeriksaan dua jenis error.',
        starter: 'class ValidationError extends Error {}\nconsole.log(new ValidationError("x") instanceof Error);\nconsole.log(new TypeError("x") instanceof ValidationError);',
        options: ['true\nfalse', 'true\ntrue', 'false\nfalse', 'false\ntrue'], answer: 'true\nfalse',
        explanation: 'ValidationError mewarisi Error. TypeError berada pada cabang class berbeda dan bukan ValidationError.',
        tests: [{ name: 'Rantai tipe error', inputs: {}, expected: 'true\nfalse' }],
        hints: ['Subclass tetap merupakan instance superclass.', 'TypeError tidak mewarisi ValidationError.'],
        solution: 'class ValidationError extends Error {}\nconsole.log(new ValidationError("x") instanceof Error);\nconsole.log(new TypeError("x") instanceof ValidationError);',
      },
      {
        id: 'errors-selective-complete', stage: 'Lengkapi', mode: 'script', title: 'Catch secara selektif',
        instruction: 'Definisikan ValidationError extends Error dan lengkapi handle(action): kembalikan "invalid" hanya untuk ValidationError; lempar kembali error lain.',
        starter: 'class ValidationError extends Error {}\nfunction handle(action) {\n  try {\n    return action();\n  } catch (error) {\n    return "invalid";\n  }\n}', probe: '(() => { try { return handle(() => { if (kind === "validation") throw new ValidationError("bad"); if (kind === "type") throw new TypeError("bug"); return "ok"; }); } catch (error) { return error.name; } })()',
        tests: [
          { name: 'Berhasil', inputs: { kind: 'ok' }, expected: 'ok' },
          { name: 'Validasi ditangani', inputs: { kind: 'validation' }, expected: 'invalid' },
          { name: 'TypeError diteruskan', inputs: { kind: 'type' }, expected: 'TypeError' },
        ],
        hints: ['Di catch, periksa error instanceof ValidationError.', 'Jika tidak cocok, tulis throw error;.'],
        solution: 'class ValidationError extends Error {}\nfunction handle(action) {\n  try {\n    return action();\n  } catch (error) {\n    if (error instanceof ValidationError) return "invalid";\n    throw error;\n  }\n}',
      },
      {
        id: 'errors-selective-build', stage: 'Bangun', mode: 'script', title: 'Assertion untuk invariant',
        instruction: 'Buat assert(condition, message) yang melempar Error(message) jika condition false. Buat dequeue(queue) yang meng-assert queue.length > 0 dengan pesan "queue is empty", lalu mengembalikan shift().',
        starter: '// Buat assert dan dequeue\n', probe: '(() => { try { const queue = items.slice(); return [dequeue(queue), queue.length]; } catch (error) { return [error instanceof Error, error.message]; } })()',
        tests: [
          { name: 'Antrean berisi', inputs: { items: ['a', 'b'] }, expected: ['a', 1] },
          { name: 'Antrean kosong', inputs: { items: [] }, expected: [true, 'queue is empty'] },
        ],
        hints: ['assert melempar saat !condition.', 'dequeue memeriksa panjang sebelum shift.'],
        solution: 'function assert(condition, message) {\n  if (!condition) throw new Error(message);\n}\nfunction dequeue(queue) {\n  assert(queue.length > 0, "queue is empty");\n  return queue.shift();\n}',
      },
    ],
  },
];
