import type { Part } from './chapter-one';

export const chapter = {
  id: 'higher-order-functions',
  title: 'Higher-Order Functions',
  number: '05',
};

export const parts: Part[] = [
  {
    id: 'abstraction',
    title: 'Abstraksi: berbicara pada level yang tepat',
    description: 'Abstraksi menyembunyikan detail berulang di balik nama yang menjelaskan tujuan sebuah operasi.',
    highlights: ['abstraksi', 'fungsi', 'range', 'sum', 'return'],
    core: 'Kode yang baik tidak hanya benar, tetapi juga menyatakan maksudnya dengan jelas. sum(range(1, 10)) berbicara tentang rentang dan penjumlahan, bukan tentang counter dan perubahan total. Fungsi membangun kosakata baru agar kita dapat memikirkan masalah pada level yang lebih tinggi.',
    model: ['detail langkah demi langkah', 'bungkus dalam fungsi', 'operasi bernama'],
    why: 'Detail tetap ada di dalam fungsi, tetapi cukup ditulis dan diuji sekali. Saat dipakai, nama fungsi membuat alur utama lebih singkat dan lebih mudah diperiksa.',
    example: 'function sum(numbers) {\n  let total = 0;\n  for (const number of numbers) total += number;\n  return total;\n}\nconsole.log(sum([1, 2, 3, 4]));',
    mistake: 'Abstraksi bukan sekadar membuat kode lebih pendek. Nama dan batas fungsi harus mewakili satu konsep yang jelas; fungsi besar bernama process tidak banyak membantu pembaca.',
    exercises: [
      {
        id: 'hof-abstraction-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti operasi bernama',
        instruction: 'Pilih nilai yang dihasilkan setelah array diberikan kepada fungsi sum.',
        starter: 'function sum(numbers) {\n  let total = 0;\n  for (const number of numbers) total += number;\n  return total;\n}\nconsole.log(sum([2, 4, 6]));',
        options: ['3', '6', '12', '2,4,6'], answer: '12',
        explanation: 'sum menyembunyikan detail loop. Ia menambahkan 2, 4, dan 6 sehingga menghasilkan 12.',
        tests: [{ name: 'Jumlah daftar', inputs: {}, expected: '12' }],
        hints: ['Fungsi mengunjungi setiap angka.', 'Hitung 2 + 4 + 6.'],
        solution: 'function sum(numbers) {\n  let total = 0;\n  for (const number of numbers) total += number;\n  return total;\n}\nconsole.log(sum([2, 4, 6]));',
      },
      {
        id: 'hof-abstraction-complete', stage: 'Lengkapi', mode: 'function', title: 'Beri nama pada operasi',
        instruction: 'Lengkapi countPositive(numbers) agar menghitung berapa angka yang lebih besar dari 0.',
        starter: 'function countPositive(numbers) {\n  let count = 0;\n  // Periksa setiap number\n  return count;\n}', probe: 'countPositive',
        tests: [
          { name: 'Nilai campuran', inputs: {}, args: [[-2, 0, 3, 7]], expected: 2 },
          { name: 'Tidak ada positif', inputs: {}, args: [[-4, 0, -1]], expected: 0 },
        ],
        hints: ['Gunakan for...of untuk mengunjungi numbers.', 'Naikkan count jika number > 0.'],
        solution: 'function countPositive(numbers) {\n  let count = 0;\n  for (const number of numbers) {\n    if (number > 0) count++;\n  }\n  return count;\n}',
      },
      {
        id: 'hof-abstraction-build', stage: 'Bangun', mode: 'function', title: 'Buat abstraksi rata-rata',
        instruction: 'Buat average(numbers) yang menjumlahkan seluruh angka dan membaginya dengan panjang array.',
        starter: '// Buat fungsi average\n', probe: 'average',
        tests: [
          { name: 'Empat angka', inputs: {}, args: [[4, 6, 8, 10]], expected: 7 },
          { name: 'Dua angka', inputs: {}, args: [[5, 15]], expected: 10 },
        ],
        hints: ['Mulai total dari 0 dan tambahkan setiap number.', 'Setelah loop, return total / numbers.length.'],
        solution: 'function average(numbers) {\n  let total = 0;\n  for (const number of numbers) total += number;\n  return total / numbers.length;\n}',
      },
    ],
  },
  {
    id: 'function-values',
    title: 'Fungsi sebagai nilai',
    description: 'Fungsi adalah nilai: dapat disimpan, dikirim sebagai argumen, dan dikembalikan oleh fungsi lain.',
    highlights: ['fungsi', 'callback', 'argumen', 'return', '=>'],
    core: 'Higher-order function adalah fungsi yang menerima fungsi lain sebagai argumen atau mengembalikan fungsi baru. Fungsi yang dikirim untuk dijalankan kemudian sering disebut callback. Dengan ini, kita dapat membuat operasi yang memiliki sebuah “ruang kosong” untuk perilaku yang dipilih pemanggil.',
    model: ['fungsi sebagai nilai', 'kirim ke fungsi lain', 'callback dijalankan'],
    why: 'Higher-order function mengabstraksikan tindakan, bukan hanya data. Satu fungsi repeat dapat mencetak index, mengisi array, atau melakukan tindakan lain sesuai callback yang diberikan.',
    example: 'function repeat(n, action) {\n  for (let i = 0; i < n; i++) action(i);\n}\nrepeat(3, index => console.log(index));',
    mistake: 'action dan action() berbeda. action merujuk pada nilai fungsi untuk dikirim. action() langsung memanggilnya dan mengirim hasil pemanggilan, bukan fungsinya.',
    exercises: [
      {
        id: 'hof-values-predict', stage: 'Prediksi', mode: 'console', title: 'Callback dipanggil berulang',
        instruction: 'Tentukan dua baris yang ditampilkan oleh callback.',
        starter: 'function repeat(n, action) {\n  for (let i = 0; i < n; i++) action(i);\n}\nrepeat(2, i => console.log("Unit " + (i + 1)));',
        options: ['Unit 0\nUnit 1', 'Unit 1\nUnit 2', 'Unit 2', '0\n1'], answer: 'Unit 1\nUnit 2',
        explanation: 'repeat memanggil callback dengan index 0 lalu 1. Callback menambahkan 1 sebelum membuat label.',
        tests: [{ name: 'Dua pemanggilan callback', inputs: {}, expected: 'Unit 1\nUnit 2' }],
        hints: ['Nilai i dimulai dari 0.', 'Hitung i + 1 pada tiap putaran.'],
        solution: 'function repeat(n, action) {\n  for (let i = 0; i < n; i++) action(i);\n}\nrepeat(2, i => console.log("Unit " + (i + 1)));',
      },
      {
        id: 'hof-values-complete', stage: 'Lengkapi', mode: 'script', title: 'Jalankan sebuah tindakan',
        instruction: 'Lengkapi applyTwice(value, action) agar action dijalankan dua kali secara berantai: hasil pertama menjadi input kedua.',
        starter: 'function applyTwice(value, action) {\n  return value;\n}', probe: '[applyTwice(3, n => n + 2), applyTwice(4, n => n * 2)]',
        tests: [
          { name: 'Dua jenis callback', inputs: {}, expected: [7, 16] },
        ],
        hints: ['Pemanggilan pertama adalah action(value).', 'Bungkus pemanggilan itu dengan action sekali lagi.'],
        solution: 'function applyTwice(value, action) {\n  return action(action(value));\n}',
      },
      {
        id: 'hof-values-build', stage: 'Bangun', mode: 'function', title: 'Kembalikan fungsi baru',
        instruction: 'Buat greaterThan(limit) yang mengembalikan arrow function. Fungsi hasilnya menerima number dan memeriksa number > limit.',
        starter: '// Buat fungsi greaterThan\n', probe: 'greaterThan(10)',
        tests: [
          { name: 'Lebih besar', inputs: {}, args: [11], expected: true },
          { name: 'Sama dengan batas', inputs: {}, args: [10], expected: false },
          { name: 'Lebih kecil', inputs: {}, args: [4], expected: false },
        ],
        hints: ['Di dalam greaterThan, return sebuah arrow function.', 'Arrow function-nya adalah number => number > limit.'],
        solution: 'function greaterThan(limit) {\n  return number => number > limit;\n}',
      },
    ],
  },
  {
    id: 'foreach',
    title: 'forEach: lakukan untuk setiap elemen',
    description: 'Method forEach memanggil callback satu kali untuk setiap elemen array.',
    highlights: ['forEach', 'callback', 'array', 'return', '=>'],
    core: 'items.forEach(callback) mengirim setiap elemen kepada callback sesuai urutan. Callback juga dapat menerima index sebagai parameter kedua. forEach digunakan untuk melakukan tindakan; method ini mengembalikan undefined dan tidak membangun array hasil.',
    model: ['array.forEach', 'callback(item, index)', 'efek untuk tiap elemen'],
    why: 'forEach cocok untuk menampilkan nilai, memperbarui total, atau menjalankan efek lain saat kita tidak memerlukan array baru sebagai hasilnya.',
    example: 'const names = ["Ayu", "Bima"];\nnames.forEach((name, index) => {\n  console.log(index + 1, name);\n});',
    mistake: 'return di dalam callback forEach hanya mengakhiri pemanggilan callback saat itu. Ia tidak membuat forEach mengembalikan kumpulan nilai; gunakan map jika memerlukan array hasil.',
    exercises: [
      {
        id: 'hof-foreach-predict', stage: 'Prediksi', mode: 'console', title: 'Urutan setiap elemen',
        instruction: 'Pilih keluaran sesuai urutan callback dijalankan.',
        starter: '["A", "B", "C"].forEach((letter, index) => {\n  console.log(index + ":" + letter);\n});',
        options: ['0:A\n1:B\n2:C', '1:A\n2:B\n3:C', 'A,B,C', 'undefined'], answer: '0:A\n1:B\n2:C',
        explanation: 'forEach mengunjungi elemen secara berurutan dan parameter index dimulai dari 0.',
        tests: [{ name: 'Urutan forEach', inputs: {}, expected: '0:A\n1:B\n2:C' }],
        hints: ['Parameter pertama adalah elemen, parameter kedua index.', 'Index array dimulai dari 0.'],
        solution: '["A", "B", "C"].forEach((letter, index) => {\n  console.log(index + ":" + letter);\n});',
      },
      {
        id: 'hof-foreach-complete', stage: 'Lengkapi', mode: 'function', title: 'Jumlahkan dengan forEach',
        instruction: 'Lengkapi sum(numbers) dengan forEach untuk menambahkan setiap number ke total.',
        starter: 'function sum(numbers) {\n  let total = 0;\n  // Gunakan forEach\n  return total;\n}', probe: 'sum',
        tests: [
          { name: 'Tiga angka', inputs: {}, args: [[3, 4, 5]], expected: 12 },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: 0 },
        ],
        hints: ['Panggil numbers.forEach dengan arrow function.', 'Di callback, tulis total += number;.'],
        solution: 'function sum(numbers) {\n  let total = 0;\n  numbers.forEach(number => {\n    total += number;\n  });\n  return total;\n}',
      },
      {
        id: 'hof-foreach-build', stage: 'Bangun', mode: 'function', title: 'Buat daftar berlabel',
        instruction: 'Buat labelItems(items). Gunakan forEach untuk mengisi array labels dengan "1. item", "2. item", dan seterusnya, lalu kembalikan labels.',
        starter: '// Buat fungsi labelItems\n', probe: 'labelItems',
        tests: [
          { name: 'Tiga item', inputs: {}, args: [['baca', 'latihan', 'ulang']], expected: ['1. baca', '2. latihan', '3. ulang'] },
          { name: 'Kosong', inputs: {}, args: [[]], expected: [] },
        ],
        hints: ['Mulai dengan const labels = [];.', 'Callback forEach dapat menerima (item, index). Push label memakai index + 1.'],
        solution: 'function labelItems(items) {\n  const labels = [];\n  items.forEach((item, index) => {\n    labels.push((index + 1) + ". " + item);\n  });\n  return labels;\n}',
      },
    ],
  },
  {
    id: 'filter',
    title: 'filter: pilih elemen yang lolos',
    description: 'Method filter membuat array baru yang hanya berisi elemen yang lolos sebuah pengujian.',
    highlights: ['filter', 'predicate', 'callback', 'true', 'false', 'array'],
    core: 'array.filter(predicate) memanggil predicate untuk setiap elemen. Elemen dimasukkan ke array hasil jika callback mengembalikan nilai truthy. Array asal tidak diubah. Fungsi penguji yang menghasilkan keputusan true atau false sering disebut predicate.',
    model: ['semua elemen', 'predicate → lolos?', 'array baru'],
    why: 'filter memisahkan aturan pemilihan dari cara mengunjungi dan mengumpulkan elemen. Kita cukup menyatakan ciri data yang ingin dipertahankan.',
    example: 'const scores = [55, 82, 70, 91];\nconst passed = scores.filter(score => score >= 75);\nconsole.log(passed);',
    mistake: 'Callback filter harus menghasilkan keputusan. Arrow function score => { score >= 75; } tidak memiliki return, sehingga setiap elemen dianggap tidak lolos.',
    exercises: [
      {
        id: 'hof-filter-predict', stage: 'Prediksi', mode: 'console', title: 'Pilih nilai yang lolos',
        instruction: 'Pilih isi array baru setelah setiap angka diuji.',
        starter: 'const result = [1, 2, 3, 4, 5].filter(n => n % 2 === 0);\nconsole.log(result.join(","));',
        options: ['1,3,5', '2,4', 'true,false,true,false,true', '2,4,5'], answer: '2,4',
        explanation: 'Sisa pembagian dengan 2 bernilai 0 hanya untuk angka genap, yaitu 2 dan 4.',
        tests: [{ name: 'Angka genap', inputs: {}, expected: '2,4' }],
        hints: ['n % 2 adalah sisa pembagian.', 'Elemen dipertahankan saat hasil perbandingan true.'],
        solution: 'const result = [1, 2, 3, 4, 5].filter(n => n % 2 === 0);\nconsole.log(result.join(","));',
      },
      {
        id: 'hof-filter-complete', stage: 'Lengkapi', mode: 'function', title: 'Saring produk tersedia',
        instruction: 'Lengkapi availableProducts(products) agar mengembalikan produk dengan stock > 0 menggunakan filter.',
        starter: 'function availableProducts(products) {\n  return products;\n}', probe: 'availableProducts',
        tests: [
          { name: 'Stok campuran', inputs: {}, args: [[{ name: 'A', stock: 2 }, { name: 'B', stock: 0 }, { name: 'C', stock: 1 }]], expected: [{ name: 'A', stock: 2 }, { name: 'C', stock: 1 }] },
          { name: 'Semua kosong', inputs: {}, args: [[{ name: 'A', stock: 0 }]], expected: [] },
        ],
        hints: ['Kembalikan hasil products.filter(...).', 'Predicate-nya memeriksa product.stock > 0.'],
        solution: 'function availableProducts(products) {\n  return products.filter(product => product.stock > 0);\n}',
      },
      {
        id: 'hof-filter-build', stage: 'Bangun', mode: 'function', title: 'Saring teks panjang',
        instruction: 'Buat longerThan(words, minimum). Kembalikan array baru berisi word yang panjangnya lebih besar dari minimum.',
        starter: '// Buat fungsi longerThan\n', probe: 'longerThan',
        tests: [
          { name: 'Batas tiga', inputs: {}, args: [['api', 'kode', 'fungsi', 'web'], 3], expected: ['kode', 'fungsi'] },
          { name: 'Tidak ada yang lolos', inputs: {}, args: [['a', 'bb'], 2], expected: [] },
        ],
        hints: ['Gunakan words.filter(...).', 'Predicate membaca word.length > minimum.'],
        solution: 'function longerThan(words, minimum) {\n  return words.filter(word => word.length > minimum);\n}',
      },
    ],
  },
  {
    id: 'map',
    title: 'map: ubah setiap elemen',
    description: 'Method map mentransformasi setiap elemen dan mengumpulkan hasilnya dalam array baru.',
    highlights: ['map', 'transformasi', 'callback', 'return', 'array'],
    core: 'array.map(transform) memanggil transform untuk setiap elemen lalu menyimpan nilai return-nya. Array hasil memiliki panjang yang sama dengan array asal, tetapi setiap elemen dapat memiliki bentuk atau tipe yang berbeda.',
    model: ['array asal', 'transform(item)', 'array hasil sama panjang'],
    why: 'map menyatakan bahwa setiap nilai akan diubah dengan aturan yang sama. Ia cocok untuk mengambil properti, mengubah satuan, atau membentuk objek baru.',
    example: 'const products = [{ name: "Buku" }, { name: "Pena" }];\nconst names = products.map(product => product.name);\nconsole.log(names);',
    mistake: 'map bukan untuk membuang elemen. Jika callback tidak return pada suatu cabang, posisi itu tetap ada dengan nilai undefined. Gunakan filter untuk memilih elemen.',
    exercises: [
      {
        id: 'hof-map-predict', stage: 'Prediksi', mode: 'console', title: 'Transformasi setiap angka',
        instruction: 'Pilih hasil setelah callback diterapkan pada ketiga elemen.',
        starter: 'const result = [2, 3, 4].map(n => n * n);\nconsole.log(result.join(","));',
        options: ['2,3,4', '4,6,8', '4,9,16', '9'], answer: '4,9,16',
        explanation: 'map mengkuadratkan setiap elemen: 2², 3², dan 4².',
        tests: [{ name: 'Array kuadrat', inputs: {}, expected: '4,9,16' }],
        hints: ['Callback dijalankan untuk setiap n.', 'Hitung 2 * 2, 3 * 3, dan 4 * 4.'],
        solution: 'const result = [2, 3, 4].map(n => n * n);\nconsole.log(result.join(","));',
      },
      {
        id: 'hof-map-complete', stage: 'Lengkapi', mode: 'function', title: 'Ambil nama dari objek',
        instruction: 'Lengkapi getNames(users) agar mengembalikan array nama menggunakan map.',
        starter: 'function getNames(users) {\n  return users;\n}', probe: 'getNames',
        tests: [
          { name: 'Dua pengguna', inputs: {}, args: [[{ name: 'Ayu', age: 20 }, { name: 'Bima', age: 22 }]], expected: ['Ayu', 'Bima'] },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: [] },
        ],
        hints: ['Kembalikan users.map(...).', 'Callback mengembalikan user.name.'],
        solution: 'function getNames(users) {\n  return users.map(user => user.name);\n}',
      },
      {
        id: 'hof-map-build', stage: 'Bangun', mode: 'function', title: 'Bentuk data baru',
        instruction: 'Buat addTax(prices, rate). Gunakan map untuk mengembalikan setiap price ditambah price * rate.',
        starter: '// Buat fungsi addTax\n', probe: 'addTax',
        tests: [
          { name: 'Pajak sepuluh persen', inputs: {}, args: [[100, 200], 0.1], expected: [110, 220] },
          { name: 'Tanpa pajak', inputs: {}, args: [[50, 75], 0], expected: [50, 75] },
        ],
        hints: ['Gunakan prices.map dengan parameter price.', 'Return price + price * rate dari callback.'],
        solution: 'function addTax(prices, rate) {\n  return prices.map(price => price + price * rate);\n}',
      },
    ],
  },
  {
    id: 'reduce',
    title: 'reduce: ringkas menjadi satu nilai',
    description: 'Method reduce menggabungkan seluruh elemen array menjadi satu nilai akhir.',
    highlights: ['reduce', 'accumulator', 'callback', 'nilai awal', 'return'],
    core: 'array.reduce(combine, start) membawa accumulator dari satu elemen ke elemen berikutnya. Callback menerima accumulator dan elemen saat ini, lalu harus mengembalikan accumulator baru. Nilai start menentukan bentuk hasil awal, misalnya 0 untuk jumlah atau {} untuk objek.',
    model: ['nilai awal', 'combine(accumulator, item)', 'satu hasil akhir'],
    why: 'reduce mewakili pola peringkasan: jumlah, nilai terbesar, pengelompokan, atau bentuk hasil lain yang dibangun bertahap.',
    example: 'const total = [1, 2, 3, 4].reduce((sum, number) => {\n  return sum + number;\n}, 0);\nconsole.log(total);',
    mistake: 'Jangan lupa mengembalikan accumulator dari callback. Tanpa return, accumulator berikutnya menjadi undefined. Menuliskan nilai awal juga membuat perilaku pada array kosong lebih jelas.',
    exercises: [
      {
        id: 'hof-reduce-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti accumulator',
        instruction: 'Mulai dari 10, lalu gabungkan setiap elemen sesuai callback.',
        starter: 'const result = [1, 2, 3].reduce((total, n) => total + n, 10);\nconsole.log(result);',
        options: ['6', '10', '16', '12310'], answer: '16',
        explanation: 'Accumulator dimulai dari 10 lalu bertambah 1, 2, dan 3 sehingga hasilnya 16.',
        tests: [{ name: 'Reduce dengan nilai awal', inputs: {}, expected: '16' }],
        hints: ['Nilai awal bukan 0, melainkan 10.', 'Hitung 10 + 1 + 2 + 3.'],
        solution: 'const result = [1, 2, 3].reduce((total, n) => total + n, 10);\nconsole.log(result);',
      },
      {
        id: 'hof-reduce-complete', stage: 'Lengkapi', mode: 'function', title: 'Jumlahkan dengan reduce',
        instruction: 'Lengkapi sum(numbers) agar memakai reduce dengan nilai awal 0.',
        starter: 'function sum(numbers) {\n  return 0;\n}', probe: 'sum',
        tests: [
          { name: 'Empat angka', inputs: {}, args: [[1, 2, 3, 4]], expected: 10 },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: 0 },
          { name: 'Nilai negatif', inputs: {}, args: [[5, -2, 1]], expected: 4 },
        ],
        hints: ['Panggil numbers.reduce(callback, 0).', 'Callback mengembalikan total + number.'],
        solution: 'function sum(numbers) {\n  return numbers.reduce((total, number) => total + number, 0);\n}',
      },
      {
        id: 'hof-reduce-build', stage: 'Bangun', mode: 'function', title: 'Cari nilai terbesar',
        instruction: 'Buat largest(numbers). Gunakan reduce tanpa nilai awal untuk mengembalikan angka terbesar.',
        starter: '// numbers selalu memiliki minimal satu elemen\n// Buat fungsi largest\n', probe: 'largest',
        tests: [
          { name: 'Angka positif', inputs: {}, args: [[4, 12, 7]], expected: 12 },
          { name: 'Semua negatif', inputs: {}, args: [[-8, -2, -11]], expected: -2 },
        ],
        hints: ['Pada setiap langkah, bandingkan largestSoFar dengan number.', 'Kembalikan number jika lebih besar; selain itu kembalikan largestSoFar.'],
        solution: 'function largest(numbers) {\n  return numbers.reduce((largestSoFar, number) => {\n    return number > largestSoFar ? number : largestSoFar;\n  });\n}',
      },
    ],
  },
  {
    id: 'composition',
    title: 'Komposisi: rangkai operasi',
    description: 'Operasi higher-order dapat dirangkai menjadi alur data yang terbaca dari kiri ke kanan.',
    highlights: ['filter', 'map', 'reduce', 'pipeline', 'komposisi'],
    core: 'Hasil filter adalah array, sehingga dapat langsung dilanjutkan dengan map atau reduce. Rangkaian ini membentuk pipeline: pilih data yang relevan, ubah bentuknya, lalu ringkas. Setiap langkah menyatakan satu tujuan.',
    model: ['filter: pilih', 'map: ubah', 'reduce: ringkas'],
    why: 'Komposisi membuat nilai antara memiliki makna yang jelas. Untuk data berukuran biasa, keterbacaan ini sering lebih penting daripada menggabungkan semuanya ke satu loop yang rumit.',
    example: 'const orders = [{ paid: true, total: 20 }, { paid: false, total: 50 }, { paid: true, total: 30 }];\nconst paidTotal = orders\n  .filter(order => order.paid)\n  .map(order => order.total)\n  .reduce((sum, total) => sum + total, 0);\nconsole.log(paidTotal);',
    mistake: 'Urutan operasi memengaruhi hasil dan biaya. filter sebelum map biasanya menghindari transformasi data yang akhirnya dibuang. Pecah pipeline ke beberapa baris jika rangkaiannya sulit dibaca.',
    exercises: [
      {
        id: 'hof-compose-predict', stage: 'Prediksi', mode: 'console', title: 'Baca sebuah pipeline',
        instruction: 'Ikuti filter lebih dahulu, lalu map, kemudian reduce.',
        starter: 'const result = [1, 2, 3, 4, 5]\n  .filter(n => n % 2 === 1)\n  .map(n => n * 2)\n  .reduce((sum, n) => sum + n, 0);\nconsole.log(result);',
        options: ['9', '12', '18', '30'], answer: '18',
        explanation: 'filter memilih 1, 3, 5; map mengubahnya menjadi 2, 6, 10; reduce menjumlahkannya menjadi 18.',
        tests: [{ name: 'Hasil pipeline', inputs: {}, expected: '18' }],
        hints: ['Tuliskan array setelah filter.', 'Setelah map, jumlahkan 2 + 6 + 10.'],
        solution: 'const result = [1, 2, 3, 4, 5]\n  .filter(n => n % 2 === 1)\n  .map(n => n * 2)\n  .reduce((sum, n) => sum + n, 0);\nconsole.log(result);',
      },
      {
        id: 'hof-compose-complete', stage: 'Lengkapi', mode: 'function', title: 'Total nilai yang lulus',
        instruction: 'Lengkapi passedTotal(scores): filter nilai minimal 75, lalu reduce menjadi jumlah dengan nilai awal 0.',
        starter: 'function passedTotal(scores) {\n  return scores;\n}', probe: 'passedTotal',
        tests: [
          { name: 'Nilai campuran', inputs: {}, args: [[60, 75, 80, 40]], expected: 155 },
          { name: 'Tidak ada yang lulus', inputs: {}, args: [[20, 50]], expected: 0 },
        ],
        hints: ['Mulai dengan scores.filter(score => score >= 75).', 'Lanjutkan .reduce((total, score) => total + score, 0).'],
        solution: 'function passedTotal(scores) {\n  return scores\n    .filter(score => score >= 75)\n    .reduce((total, score) => total + score, 0);\n}',
      },
      {
        id: 'hof-compose-build', stage: 'Bangun', mode: 'function', title: 'Ringkas pesanan aktif',
        instruction: 'Buat activeOrderTotal(orders). Pilih order dengan active true, ambil subtotal dengan map, lalu jumlahkan memakai reduce dan nilai awal 0.',
        starter: '// Buat fungsi activeOrderTotal\n', probe: 'activeOrderTotal',
        tests: [
          { name: 'Status campuran', inputs: {}, args: [[{ active: true, subtotal: 25000 }, { active: false, subtotal: 90000 }, { active: true, subtotal: 15000 }]], expected: 40000 },
          { name: 'Tanpa order aktif', inputs: {}, args: [[{ active: false, subtotal: 10000 }]], expected: 0 },
        ],
        hints: ['Rangkai filter, map, lalu reduce.', 'Callback map mengembalikan order.subtotal.'],
        solution: 'function activeOrderTotal(orders) {\n  return orders\n    .filter(order => order.active)\n    .map(order => order.subtotal)\n    .reduce((total, subtotal) => total + subtotal, 0);\n}',
      },
    ],
  },
  {
    id: 'search-and-test',
    title: 'some, every, dan find',
    description: 'Array menyediakan higher-order method untuk menguji keberadaan, menguji semua elemen, dan mencari satu elemen.',
    highlights: ['some', 'every', 'find', 'predicate', 'true', 'false', 'undefined'],
    core: 'some menghasilkan true jika setidaknya satu elemen lolos predicate. every menghasilkan true jika semua elemen lolos; untuk array kosong hasilnya true. find mengembalikan elemen pertama yang lolos, atau undefined jika tidak ditemukan. Ketiganya dapat berhenti lebih awal saat jawabannya sudah diketahui.',
    model: ['array + predicate', 'uji sampai jawaban diketahui', 'boolean atau satu elemen'],
    why: 'Method ini langsung menyatakan pertanyaan yang diajukan: “adakah?”, “apakah semuanya?”, atau “yang pertama mana?”. Itu lebih jelas daripada loop dengan flag dan kondisi berhenti manual.',
    example: 'const numbers = [3, 7, 12];\nconsole.log(numbers.some(n => n % 2 === 0));\nconsole.log(numbers.every(n => n > 0));\nconsole.log(numbers.find(n => n > 5));',
    mistake: 'find mengembalikan elemen, bukan boolean atau index. Jika elemen yang dicari memang dapat bernilai undefined, hasil “ditemukan” dan “tidak ditemukan” perlu dibedakan dengan cara lain.',
    exercises: [
      {
        id: 'hof-search-predict', stage: 'Prediksi', mode: 'console', title: 'Tiga pertanyaan pada array',
        instruction: 'Tentukan hasil some, every, lalu find sesuai urutan.',
        starter: 'const values = [2, 5, 8];\nconsole.log(values.some(n => n > 6));\nconsole.log(values.every(n => n > 0));\nconsole.log(values.find(n => n % 2 === 1));',
        options: ['true\ntrue\n5', 'true\nfalse\n5', '8\ntrue\n5', 'true\ntrue\n8'], answer: 'true\ntrue\n5',
        explanation: 'Ada nilai > 6, semua nilai positif, dan angka ganjil pertama adalah 5.',
        tests: [{ name: 'some, every, find', inputs: {}, expected: 'true\ntrue\n5' }],
        hints: ['some dan every menghasilkan boolean.', 'find mengembalikan elemen pertama yang cocok.'],
        solution: 'const values = [2, 5, 8];\nconsole.log(values.some(n => n > 6));\nconsole.log(values.every(n => n > 0));\nconsole.log(values.find(n => n % 2 === 1));',
      },
      {
        id: 'hof-search-complete', stage: 'Lengkapi', mode: 'script', title: 'Implementasikan every',
        instruction: 'Lengkapi every(array, test) menggunakan some dan negasi. Hasilnya true jika tidak ada elemen yang gagal.',
        starter: 'function every(array, test) {\n  return false;\n}', probe: '[every([1, 3, 5], n => n < 10), every([2, 4, 16], n => n < 10), every([], n => n < 10)]',
        tests: [
          { name: 'Semua, sebagian, dan array kosong', inputs: {}, expected: [true, false, true] },
        ],
        hints: ['Cari apakah ada elemen yang tidak lolos test.', 'Gunakan !array.some(element => !test(element)).'],
        solution: 'function every(array, test) {\n  return !array.some(element => !test(element));\n}',
      },
      {
        id: 'hof-search-build', stage: 'Bangun', mode: 'function', title: 'Cari pengguna berdasarkan id',
        instruction: 'Buat findUser(users, id) yang memakai find untuk mengembalikan pengguna pertama dengan user.id === id, atau undefined jika tidak ada.',
        starter: '// Buat fungsi findUser\n', probe: 'findUser',
        tests: [
          { name: 'Pengguna ditemukan', inputs: {}, args: [[{ id: 1, name: 'Ayu' }, { id: 2, name: 'Bima' }], 2], expected: { id: 2, name: 'Bima' } },
          { name: 'Tidak ditemukan', inputs: {}, args: [[{ id: 1, name: 'Ayu' }], 9], expected: undefined },
        ],
        hints: ['Kembalikan users.find(...).', 'Predicate membandingkan user.id === id.'],
        solution: 'function findUser(users, id) {\n  return users.find(user => user.id === id);\n}',
      },
    ],
  },
];
