import type { Part } from './chapter-one';

export const chapter = {
  id: 'asynchronous-programming',
  title: 'Pemrograman Asinkron',
  number: '11',
};

export const parts: Part[] = [
  {
    id: 'sync-and-async',
    title: 'Sinkron dan asinkron: dua cara menunggu',
    description: 'Operasi asinkron membiarkan program melanjutkan pekerjaan lain sambil menunggu hasil yang belum tersedia.',
    highlights: ['sinkron', 'asinkron', 'menunggu', 'I/O', 'urutan'],
    core: 'Pada alur sinkron, pemanggilan baru selesai ketika hasilnya sudah ada. Pada alur asinkron, operasi dimulai lalu hasil disampaikan kemudian. Perbedaannya penting untuk pekerjaan lambat seperti membaca berkas atau meminta data, karena JavaScript tidak perlu membekukan seluruh program selama menunggu.',
    model: ['mulai pekerjaan', 'lanjutkan kode lain', 'terima hasil kemudian'],
    why: 'Memisahkan waktu mulai dari waktu selesai membantu kita memilih kapan pekerjaan harus berurutan dan kapan beberapa pekerjaan boleh berlangsung bersama.',
    example: 'console.log("mulai");\nPromise.resolve("data siap").then(console.log);\nconsole.log("lanjut");',
    mistake: 'Asinkron tidak berarti dua potongan JavaScript selalu berjalan tepat bersamaan. Kode callback tetap mendapat giliran satu per satu; yang dapat bertumpang tindih terutama adalah waktu menunggu operasinya.',
    exercises: [
      {
        id: 'async-model-predict', stage: 'Prediksi', mode: 'console', title: 'Kode lanjut sebelum hasil tiba',
        instruction: 'Pilih urutan keluaran. Handler then baru mendapat giliran setelah kode sinkron selesai.',
        starter: 'console.log("A");\nPromise.resolve().then(() => console.log("C"));\nconsole.log("B");',
        options: ['A\nB\nC', 'A\nC\nB', 'C\nA\nB', 'B\nA\nC'], answer: 'A\nB\nC',
        explanation: 'A dan B dicetak oleh pekerjaan saat ini. Handler Promise berjalan pada giliran microtask berikutnya, sehingga C muncul terakhir.',
        tests: [{ name: 'Urutan sinkron dan Promise', inputs: {}, expected: 'A\nB\nC' }],
        hints: ['Promise yang sudah fulfilled tetap memanggil then kemudian.', 'Selesaikan semua console.log sinkron lebih dahulu.'],
        solution: 'console.log("A");\nPromise.resolve().then(() => console.log("C"));\nconsole.log("B");',
      },
      {
        id: 'async-model-complete', stage: 'Lengkapi', mode: 'function', title: 'Kembalikan hasil yang dijanjikan',
        instruction: 'Lengkapi futureDouble(number) agar mengembalikan Promise yang fulfilled dengan number * 2.',
        starter: 'function futureDouble(number) {\n  // Kembalikan Promise\n}', probe: 'futureDouble',
        tests: [
          { name: 'Menggandakan angka positif', inputs: {}, args: [6], expected: 12 },
          { name: 'Menggandakan nol', inputs: {}, args: [0], expected: 0 },
        ],
        hints: ['Gunakan Promise.resolve(...).', 'Nilai di dalam Promise adalah number * 2.'],
        solution: 'function futureDouble(number) {\n  return Promise.resolve(number * 2);\n}',
      },
      {
        id: 'async-model-build', stage: 'Bangun', mode: 'function', title: 'Modelkan biaya waktu',
        instruction: 'Buat compareTime(durations). Kembalikan objek {sequential, concurrent}; sequential adalah jumlah semua durasi dan concurrent adalah durasi terbesar. Untuk array kosong, keduanya 0.',
        starter: '// Buat fungsi compareTime\n', probe: 'compareTime',
        tests: [
          { name: 'Tiga pekerjaan', inputs: {}, args: [[30, 10, 20]], expected: { sequential: 60, concurrent: 30 } },
          { name: 'Tanpa pekerjaan', inputs: {}, args: [[]], expected: { sequential: 0, concurrent: 0 } },
        ],
        hints: ['Jumlahkan durasi untuk alur berurutan.', 'Waktu bersama dimodelkan oleh nilai terbesar.'],
        solution: 'function compareTime(durations) {\n  return {\n    sequential: durations.reduce((sum, time) => sum + time, 0),\n    concurrent: durations.length ? Math.max(...durations) : 0,\n  };\n}',
      },
    ],
  },
  {
    id: 'callbacks',
    title: 'Callback: titipkan langkah berikutnya',
    description: 'Callback adalah fungsi yang diberikan agar dipanggil ketika sebuah operasi mencapai tahap tertentu.',
    highlights: ['callback', 'kelanjutan', 'argumen', 'error-first', 'nesting'],
    core: 'Fungsi asinkron bergaya callback biasanya memulai pekerjaan, lalu memanggil fungsi yang diterimanya ketika hasil tersedia. Callback menyimpan kelanjutan perhitungan. Jika banyak langkah saling bergantung, callback dapat bertumpuk dan jalur error mudah terlewat.',
    model: ['kirim callback', 'operasi selesai', 'callback menerima hasil'],
    why: 'Memahami callback menjelaskan asal berbagai API berbasis peristiwa dan alasan Promise menyediakan komposisi yang lebih teratur.',
    example: 'function deliver(value, callback) {\n  callback(value);\n}\ndeliver(4, value => console.log(value * 2));',
    mistake: 'Menulis action() saat API meminta action akan menjalankan fungsi terlalu awal. Kirim nilai fungsinya tanpa tanda kurung agar penerima dapat memanggilnya pada waktu yang tepat.',
    exercises: [
      {
        id: 'async-callback-predict', stage: 'Prediksi', mode: 'console', title: 'Callback menerima hasil',
        instruction: 'Pilih keluaran saat send memanggil callback dengan nilai yang sudah diubah.',
        starter: 'function send(value, done) {\n  done(value + 1);\n}\nconsole.log("mulai");\nsend(4, result => console.log(result));',
        options: ['mulai\n4', 'mulai\n5', '5\nmulai', 'mulai\nundefined'], answer: 'mulai\n5',
        explanation: 'send menambahkan 1 lalu memberikan 5 kepada callback. Contoh ini sinkron, tetapi bentuk pengiriman kelanjutannya sama.',
        tests: [{ name: 'Nilai callback', inputs: {}, expected: 'mulai\n5' }],
        hints: ['done dipanggil dengan value + 1.', 'Callback mencetak parameter result.'],
        solution: 'function send(value, done) {\n  done(value + 1);\n}\nconsole.log("mulai");\nsend(4, result => console.log(result));',
      },
      {
        id: 'async-callback-complete', stage: 'Lengkapi', mode: 'script', title: 'Teruskan hasil ke callback',
        instruction: 'Lengkapi calculate(value, transform, done): jalankan transform pada value, lalu kirim hasilnya ke done. Callback disediakan di probe, bukan sebagai input test.',
        starter: 'function calculate(value, transform, done) {\n  // Jalankan kedua callback pada urutan yang benar\n}', probe: '(() => { const output = []; calculate(5, n => n * 3, value => output.push(value)); return output; })()',
        tests: [{ name: 'Transformasi lalu penyelesaian', inputs: {}, expected: [15] }],
        hints: ['Hitung transform(value) lebih dahulu.', 'Berikan hasil tersebut kepada done(...).'],
        solution: 'function calculate(value, transform, done) {\n  done(transform(value));\n}',
      },
      {
        id: 'async-callback-build', stage: 'Bangun', mode: 'script', title: 'Pisahkan sukses dan gagal',
        instruction: 'Buat parseAmount(text, done). Panggil done(null, number) jika text berisi angka valid; jika tidak, panggil done("bukan angka").',
        starter: '// Buat fungsi parseAmount\n', probe: '(() => { const results = []; parseAmount("42", (error, value) => results.push(error ?? value)); parseAmount("halo", (error, value) => results.push(error ?? value)); return results; })()',
        tests: [{ name: 'Jalur berhasil dan gagal', inputs: {}, expected: [42, 'bukan angka'] }],
        hints: ['Ubah text memakai Number(text).', 'Periksa hasil dengan Number.isNaN.'],
        solution: 'function parseAmount(text, done) {\n  const number = Number(text);\n  if (Number.isNaN(number)) done("bukan angka");\n  else done(null, number);\n}',
      },
    ],
  },
  {
    id: 'promise-chains',
    title: 'Promise dan rantai transformasi',
    description: 'Promise mewakili hasil masa depan, sedangkan then merangkai pekerjaan yang bergantung pada hasil tersebut.',
    highlights: ['Promise', 'pending', 'fulfilled', 'then', 'chain'],
    core: 'then mendaftarkan handler dan selalu menghasilkan Promise baru. Nilai biasa yang dikembalikan handler menjadi fulfillment tahap berikutnya. Jika handler mengembalikan Promise, rantai menunggu Promise itu sebelum bergerak lagi.',
    model: ['Promise awal', 'then mengubah nilai', 'Promise hasil'],
    why: 'Rantai Promise membuat hubungan antarhasil lebih jelas daripada callback bertingkat dan memungkinkan fungsi mengembalikan pekerjaan yang belum selesai.',
    example: 'Promise.resolve(3)\n  .then(number => number + 2)\n  .then(number => number * 4);',
    mistake: 'Lupa return di dalam handler membuat tahap berikutnya menerima undefined. Setiap transformasi harus mengembalikan nilai atau Promise yang memang ingin diteruskan.',
    exercises: [
      {
        id: 'async-chain-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti nilai di sepanjang rantai',
        instruction: 'Pilih nilai yang akhirnya dicetak.',
        starter: 'Promise.resolve(2)\n  .then(n => n + 3)\n  .then(n => n * 4)\n  .then(console.log);',
        options: ['5', '8', '20', 'undefined'], answer: '20',
        explanation: 'Tahap pertama menghasilkan 5 dan tahap kedua mengubahnya menjadi 20.',
        tests: [{ name: 'Hasil rantai Promise', inputs: {}, expected: '20' }],
        hints: ['Setiap then menerima hasil then sebelumnya.', 'Hitung (2 + 3) * 4.'],
        solution: 'Promise.resolve(2)\n  .then(n => n + 3)\n  .then(n => n * 4)\n  .then(console.log);',
      },
      {
        id: 'async-chain-complete', stage: 'Lengkapi', mode: 'function', title: 'Teruskan nilai antartahap',
        instruction: 'Lengkapi prepareName(name). Mulai dengan Promise.resolve(name), hilangkan spasi tepi, lalu ubah menjadi huruf besar melalui dua then.',
        starter: 'function prepareName(name) {\n  return Promise.resolve(name);\n}', probe: 'prepareName',
        tests: [
          { name: 'Nama dengan spasi', inputs: {}, args: ['  Nara  '], expected: 'NARA' },
          { name: 'Huruf campuran', inputs: {}, args: ['RaKa'], expected: 'RAKA' },
        ],
        hints: ['then pertama mengembalikan text.trim().', 'then kedua mengembalikan text.toUpperCase().'],
        solution: 'function prepareName(name) {\n  return Promise.resolve(name)\n    .then(text => text.trim())\n    .then(text => text.toUpperCase());\n}',
      },
      {
        id: 'async-chain-build', stage: 'Bangun', mode: 'function', title: 'Rangkai nilai dan Promise',
        instruction: 'Buat invoiceTotal(prices). Mulai dari Promise.resolve(prices), jumlahkan isinya pada then pertama, lalu kembalikan Promise.resolve(total * 1.1) pada then kedua.',
        starter: '// Buat fungsi invoiceTotal\n', probe: 'invoiceTotal',
        tests: [
          { name: 'Dua harga', inputs: {}, args: [[100, 50]], expected: 165 },
          { name: 'Daftar kosong', inputs: {}, args: [[]], expected: 0 },
        ],
        hints: ['Gunakan reduce dengan nilai awal 0.', 'Return Promise.resolve(total * 1.1) dari then kedua.'],
        solution: 'function invoiceTotal(prices) {\n  return Promise.resolve(prices)\n    .then(items => items.reduce((sum, price) => sum + price, 0))\n    .then(total => Promise.resolve(total * 1.1));\n}',
      },
    ],
  },
  {
    id: 'rejection-and-catch',
    title: 'Rejection dan pemulihan kegagalan',
    description: 'Promise yang gagal membawa alasan rejection melewati rantai sampai ada handler yang menanganinya.',
    highlights: ['reject', 'catch', 'throw', 'error', 'recovery'],
    core: 'Error yang dilempar di dalam then mengubah Promise hasil menjadi rejected. Handler sukses berikutnya dilewati sampai catch menangani kegagalan. catch dapat mengembalikan nilai pengganti sehingga rantai kembali ke jalur fulfilled, atau melempar lagi untuk mempertahankan kegagalan.',
    model: ['operasi gagal', 'rejection merambat', 'catch menangani'],
    why: 'Satu jalur propagasi membuat kegagalan dari banyak tahap dapat ditangani pada batas yang tepat tanpa pemeriksaan error di setiap baris.',
    example: 'Promise.resolve("data")\n  .then(() => { throw new Error("rusak"); })\n  .catch(() => "cadangan");',
    mistake: 'catch yang hanya mencetak error dianggap berhasil dengan nilai undefined. Jika pemanggil masih harus mengetahui kegagalan, lempar kembali error tersebut.',
    exercises: [
      {
        id: 'async-rejection-predict', stage: 'Prediksi', mode: 'console', title: 'Catch mengembalikan alur',
        instruction: 'Pilih dua baris yang dicetak. then sebelum catch dilewati karena Promise rejected.',
        starter: 'Promise.reject("gagal")\n  .then(() => console.log("tidak"))\n  .catch(reason => {\n    console.log(reason);\n    return "pulih";\n  })\n  .then(console.log);',
        options: ['tidak\ngagal', 'gagal\npulih', 'gagal\ntidak', 'pulih'], answer: 'gagal\npulih',
        explanation: 'Rejection melewati handler sukses. catch mencetak alasan dan mengembalikan nilai biasa, sehingga then terakhir menerima "pulih".',
        tests: [{ name: 'Propagasi dan pemulihan', inputs: {}, expected: 'gagal\npulih' }],
        hints: ['then pertama hanya menangani fulfillment.', 'Nilai return dari catch menjadi hasil fulfilled.'],
        solution: 'Promise.reject("gagal")\n  .then(() => console.log("tidak"))\n  .catch(reason => {\n    console.log(reason);\n    return "pulih";\n  })\n  .then(console.log);',
      },
      {
        id: 'async-rejection-complete', stage: 'Lengkapi', mode: 'function', title: 'Sediakan nilai cadangan',
        instruction: 'Lengkapi safeDivide(a, b). Reject dengan "nol" jika b === 0, jika tidak resolve a / b. Tangani rejection dengan catch dan kembalikan null.',
        starter: 'function safeDivide(a, b) {\n  const result = b === 0 ? Promise.reject("nol") : Promise.resolve(a / b);\n  return result;\n}', probe: 'safeDivide',
        tests: [
          { name: 'Pembagian valid', inputs: {}, args: [12, 3], expected: 4 },
          { name: 'Pembagi nol', inputs: {}, args: [12, 0], expected: null },
        ],
        hints: ['Rangkaikan .catch(...) pada result.', 'Handler catch mengembalikan null.'],
        solution: 'function safeDivide(a, b) {\n  const result = b === 0 ? Promise.reject("nol") : Promise.resolve(a / b);\n  return result.catch(() => null);\n}',
      },
      {
        id: 'async-rejection-build', stage: 'Bangun', mode: 'function', title: 'Validasi dalam rantai',
        instruction: 'Buat normalizeScore(value). Resolve value, lempar Error jika bukan number atau di luar 0..100, lalu ubah score valid menjadi score / 100. Catch harus mengembalikan -1.',
        starter: '// Buat fungsi normalizeScore\n', probe: 'normalizeScore',
        tests: [
          { name: 'Skor valid', inputs: {}, args: [80], expected: 0.8 },
          { name: 'Skor terlalu besar', inputs: {}, args: [120], expected: -1 },
          { name: 'Tipe salah', inputs: {}, args: ['80'], expected: -1 },
        ],
        hints: ['Lakukan validasi di dalam then dan gunakan throw.', 'Tambahkan catch terakhir yang return -1.'],
        solution: 'function normalizeScore(value) {\n  return Promise.resolve(value)\n    .then(score => {\n      if (typeof score !== "number" || score < 0 || score > 100) {\n        throw new Error("skor tidak valid");\n      }\n      return score / 100;\n    })\n    .catch(() => -1);\n}',
      },
    ],
  },
  {
    id: 'async-await',
    title: 'async dan await: jeda yang eksplisit',
    description: 'async/await menuliskan rangkaian Promise dengan bentuk yang menyerupai alur biasa.',
    highlights: ['async', 'await', 'try', 'catch', 'Promise'],
    core: 'Pemanggilan fungsi async selalu menghasilkan Promise. await mengambil fulfillment sebuah Promise dan melanjutkan fungsi setelah nilainya tersedia. Jika Promise rejected, await melempar pada titik itu sehingga try/catch biasa dapat digunakan.',
    model: ['panggil fungsi async', 'await menjeda fungsi', 'lanjut dengan hasil'],
    why: 'Bentuk linear memudahkan loop, percabangan, dan beberapa langkah yang memang harus saling menunggu tanpa menghilangkan sifat asinkron hasil akhirnya.',
    example: 'async function label() {\n  const value = await Promise.resolve(7);\n  return "Nilai: " + value;\n}',
    mistake: 'await hanya valid di konteks yang mendukungnya dan tidak otomatis membuat pekerjaan paralel. Dua await berturut-turut biasanya memulai pekerjaan kedua setelah yang pertama selesai.',
    exercises: [
      {
        id: 'async-await-predict', stage: 'Prediksi', mode: 'console', title: 'Fungsi berhenti sementara',
        instruction: 'Pilih urutan keluaran ketika fungsi async mencapai await.',
        starter: 'async function task() {\n  console.log("dalam-1");\n  await Promise.resolve();\n  console.log("dalam-2");\n}\nconsole.log("luar-1");\ntask();\nconsole.log("luar-2");',
        options: ['luar-1\ndalam-1\nluar-2\ndalam-2', 'luar-1\ndalam-1\ndalam-2\nluar-2', 'dalam-1\ndalam-2\nluar-1\nluar-2', 'luar-1\nluar-2\ndalam-1\ndalam-2'], answer: 'luar-1\ndalam-1\nluar-2\ndalam-2',
        explanation: 'task langsung berjalan sampai await. Kelanjutannya dijadwalkan sebagai microtask setelah kode utama mencetak luar-2.',
        tests: [{ name: 'Jeda pada await', inputs: {}, expected: 'luar-1\ndalam-1\nluar-2\ndalam-2' }],
        hints: ['Bagian sebelum await masih berjalan langsung.', 'Bagian setelah await menunggu kode sinkron selesai.'],
        solution: 'async function task() {\n  console.log("dalam-1");\n  await Promise.resolve();\n  console.log("dalam-2");\n}\nconsole.log("luar-1");\ntask();\nconsole.log("luar-2");',
      },
      {
        id: 'async-await-complete', stage: 'Lengkapi', mode: 'function', title: 'Ambil dua hasil berurutan',
        instruction: 'Lengkapi sumFuture(a, b). Await Promise.resolve(a), lalu await Promise.resolve(b), dan kembalikan jumlahnya.',
        starter: 'async function sumFuture(a, b) {\n  // Tunggu kedua nilai\n}', probe: 'sumFuture',
        tests: [
          { name: 'Dua angka', inputs: {}, args: [8, 5], expected: 13 },
          { name: 'Dengan angka negatif', inputs: {}, args: [4, -9], expected: -5 },
        ],
        hints: ['Simpan setiap hasil await dalam const.', 'Return hasil penjumlahan kedua nilai.'],
        solution: 'async function sumFuture(a, b) {\n  const first = await Promise.resolve(a);\n  const second = await Promise.resolve(b);\n  return first + second;\n}',
      },
      {
        id: 'async-await-build', stage: 'Bangun', mode: 'function', title: 'Tangani rejection dengan try/catch',
        instruction: 'Buat async function readStatus(ok). Await Promise.resolve("siap") saat ok true atau Promise.reject("offline") saat false. Kembalikan hasil sukses; pada catch kembalikan "cadangan".',
        starter: '// Buat async function readStatus\n', probe: 'readStatus',
        tests: [
          { name: 'Layanan siap', inputs: {}, args: [true], expected: 'siap' },
          { name: 'Layanan gagal', inputs: {}, args: [false], expected: 'cadangan' },
        ],
        hints: ['Buat Promise pilihan di dalam try.', 'catch dapat langsung return "cadangan".'],
        solution: 'async function readStatus(ok) {\n  try {\n    return await (ok ? Promise.resolve("siap") : Promise.reject("offline"));\n  } catch {\n    return "cadangan";\n  }\n}',
      },
    ],
  },
  {
    id: 'promise-all',
    title: 'Promise.all dan pekerjaan bersama',
    description: 'Promise.all menunggu sekumpulan pekerjaan dan menghasilkan nilai sesuai urutan input.',
    highlights: ['Promise.all', 'konkurensi', 'array', 'urutan', 'fail-fast'],
    core: 'Dengan membentuk semua Promise lebih dahulu, beberapa waktu tunggu dapat bertumpang tindih. Promise.all menggabungkannya menjadi satu Promise berisi array hasil. Posisi hasil mengikuti posisi input, bukan urutan selesai. Satu rejection membuat Promise gabungan ikut rejected.',
    model: ['buat banyak Promise', 'tunggu semuanya', 'array hasil terurut'],
    why: 'Pola ini cocok untuk pekerjaan independen yang semuanya diperlukan sebelum tahap berikutnya dimulai.',
    example: 'const jobs = [1, 2, 3].map(n => Promise.resolve(n * 10));\nPromise.all(jobs).then(console.log);',
    mistake: 'await di dalam loop sebelum Promise berikutnya dibuat menghilangkan konkurensi. Namun jangan memakai Promise.all jika urutan operasi, batas layanan, atau penggunaan sumber daya menuntut pembatasan.',
    exercises: [
      {
        id: 'async-all-predict', stage: 'Prediksi', mode: 'console', title: 'Urutan input tetap terjaga',
        instruction: 'Pilih keluaran Promise.all. Semua Promise di sini selesai melalui microtask yang deterministik.',
        starter: 'const jobs = [\n  Promise.resolve("pertama"),\n  Promise.resolve("kedua"),\n  Promise.resolve("ketiga"),\n];\nPromise.all(jobs).then(values => console.log(values.join(" | ")));',
        options: ['pertama | kedua | ketiga', 'ketiga | kedua | pertama', 'pertama', 'Promise'], answer: 'pertama | kedua | ketiga',
        explanation: 'Promise.all menyimpan urutan posisi input ketika membentuk array hasil.',
        tests: [{ name: 'Hasil terurut', inputs: {}, expected: 'pertama | kedua | ketiga' }],
        hints: ['Lihat urutan Promise di array jobs.', 'Urutan hasil tidak diubah oleh Promise.all.'],
        solution: 'const jobs = [\n  Promise.resolve("pertama"),\n  Promise.resolve("kedua"),\n  Promise.resolve("ketiga"),\n];\nPromise.all(jobs).then(values => console.log(values.join(" | ")));',
      },
      {
        id: 'async-all-complete', stage: 'Lengkapi', mode: 'function', title: 'Tunggu semua transformasi',
        instruction: 'Lengkapi futureSquares(numbers). Ubah setiap number menjadi Promise.resolve(number * number), lalu kembalikan Promise.all dari array tersebut.',
        starter: 'function futureSquares(numbers) {\n  const jobs = numbers.map(number => Promise.resolve(number * number));\n  return jobs;\n}', probe: 'futureSquares',
        tests: [
          { name: 'Tiga kuadrat', inputs: {}, args: [[2, 3, 4]], expected: [4, 9, 16] },
          { name: 'Array kosong', inputs: {}, args: [[]], expected: [] },
        ],
        hints: ['jobs adalah array Promise.', 'Gabungkan dengan Promise.all(jobs).'],
        solution: 'function futureSquares(numbers) {\n  const jobs = numbers.map(number => Promise.resolve(number * number));\n  return Promise.all(jobs);\n}',
      },
      {
        id: 'async-all-build', stage: 'Bangun', mode: 'function', title: 'Gabungkan pekerjaan independen',
        instruction: 'Buat async function summarize(words). Bentuk semua Promise lebih dahulu; masing-masing menghasilkan {word, length}. Await Promise.all, lalu kembalikan objek dengan items dan total panjang.',
        starter: '// Buat async function summarize\n', probe: 'summarize',
        tests: [
          { name: 'Dua kata', inputs: {}, args: [['api', 'kode']], expected: { items: [{ word: 'api', length: 3 }, { word: 'kode', length: 4 }], total: 7 } },
          { name: 'Kosong', inputs: {}, args: [[]], expected: { items: [], total: 0 } },
        ],
        hints: ['Gunakan words.map(word => Promise.resolve({...})).', 'Jumlahkan length setelah await Promise.all.'],
        solution: 'async function summarize(words) {\n  const jobs = words.map(word => Promise.resolve({ word, length: word.length }));\n  const items = await Promise.all(jobs);\n  const total = items.reduce((sum, item) => sum + item.length, 0);\n  return { items, total };\n}',
      },
    ],
  },
  {
    id: 'event-loop',
    title: 'Event loop: stack, microtask, dan timer',
    description: 'Event loop memberi giliran pada kelanjutan asinkron setelah pekerjaan JavaScript saat ini selesai.',
    highlights: ['event loop', 'call stack', 'microtask', 'timer', 'queue'],
    core: 'Satu giliran JavaScript berjalan sampai tuntas. Reaksi Promise masuk antrean microtask dan diproses setelah stack kosong. Callback timer masuk antrean task dan berjalan sesudah microtask yang sudah menunggu. Karena itu timer nol milidetik bukan berarti langsung.',
    model: ['jalankan stack', 'kuras microtask', 'ambil task berikutnya'],
    why: 'Model antrean membuat urutan keluaran dapat diprediksi dan menjelaskan mengapa pekerjaan CPU yang panjang menunda penanganan peristiwa.',
    example: 'setTimeout(() => console.log("timer"), 0);\nPromise.resolve().then(() => console.log("microtask"));\nconsole.log("sinkron");',
    mistake: 'try/catch di sekitar setTimeout tidak menangkap error yang baru dilempar callback nanti, karena stack try/catch sudah selesai ketika callback mendapat giliran.',
    exercises: [
      {
        id: 'async-loop-predict', stage: 'Prediksi', mode: 'console', title: 'Microtask mendahului timer',
        instruction: 'Pilih urutan keluaran dari stack saat ini, microtask Promise, lalu timer 0 ms.',
        starter: 'setTimeout(() => console.log("timer"), 0);\nPromise.resolve().then(() => console.log("microtask"));\nconsole.log("sekarang");',
        options: ['sekarang\nmicrotask\ntimer', 'timer\nmicrotask\nsekarang', 'sekarang\ntimer\nmicrotask', 'microtask\nsekarang\ntimer'], answer: 'sekarang\nmicrotask\ntimer',
        explanation: 'Log sinkron berjalan dahulu, antrean microtask dikuras, kemudian callback timer mendapat giliran task.',
        tests: [{ name: 'Tiga jenis giliran', inputs: {}, expected: 'sekarang\nmicrotask\ntimer' }],
        hints: ['Timer 0 ms tetap menunggu stack kosong.', 'Microtask Promise didahulukan sebelum task timer.'],
        solution: 'setTimeout(() => console.log("timer"), 0);\nPromise.resolve().then(() => console.log("microtask"));\nconsole.log("sekarang");',
      },
      {
        id: 'async-loop-complete', stage: 'Lengkapi', mode: 'script', title: 'Buat jejak microtask',
        instruction: 'Lengkapi eventOrder() agar menambahkan "sync" langsung, menjadwalkan "micro" lewat Promise.resolve().then(...), lalu mengembalikan Promise yang menghasilkan trace setelah microtask selesai.',
        starter: 'function eventOrder() {\n  const trace = [];\n  trace.push("sync");\n  // Jadwalkan micro dan kembalikan Promise hasil\n}', probe: 'eventOrder()',
        tests: [{ name: 'Urutan jejak', inputs: {}, expected: ['sync', 'micro'] }],
        hints: ['Return Promise.resolve().then(...).', 'Di handler, push "micro" lalu return trace.'],
        solution: 'function eventOrder() {\n  const trace = [];\n  trace.push("sync");\n  return Promise.resolve().then(() => {\n    trace.push("micro");\n    return trace;\n  });\n}',
      },
      {
        id: 'async-loop-build', stage: 'Bangun', mode: 'script', title: 'Modelkan antrean secara sinkron',
        instruction: 'Buat drainQueues(sync, microtasks, tasks). Kembalikan array baru berisi sync, lalu semua microtasks, lalu semua tasks. Input berupa data saja; fungsi ini adalah model deterministik event loop.',
        starter: '// Buat fungsi drainQueues\n', probe: '[drainQueues(["A"], ["B", "C"], ["D"]), drainQueues([], ["m"], ["t1", "t2"])]',
        tests: [{ name: 'Dua model antrean', inputs: {}, expected: [['A', 'B', 'C', 'D'], ['m', 't1', 't2']] }],
        hints: ['Jangan ubah array asal.', 'Gunakan spread untuk menggabungkan tiga array.'],
        solution: 'function drainQueues(sync, microtasks, tasks) {\n  return [...sync, ...microtasks, ...tasks];\n}',
      },
    ],
  },
  {
    id: 'generators-and-gaps',
    title: 'Generator dan celah asinkron',
    description: 'Generator menyimpan posisi eksekusi saat yield; await juga menciptakan jeda tempat keadaan lain dapat berubah.',
    highlights: ['function*', 'yield', 'iterator', 'await gap', 'shared state'],
    core: 'Pemanggilan generator menghasilkan iterator yang dapat dilanjutkan dengan next. Setiap yield memberikan nilai sekaligus menyimpan lingkungan lokal. Fungsi async memiliki gagasan jeda serupa, tetapi kelanjutannya dikendalikan Promise. Di sekitar await, mutasi terhadap data bersama perlu diperiksa dengan hati-hati.',
    model: ['jalankan hingga yield/await', 'simpan keadaan lokal', 'lanjutkan kemudian'],
    why: 'Mengenali titik jeda membantu kita menulis iterator ringkas dan menghindari bug ketika beberapa tugas membaca lalu menulis variabel yang sama.',
    example: 'function* steps() {\n  yield "satu";\n  yield "dua";\n}\nconsole.log([...steps()]);',
    mistake: 'Ekspresi seperti shared += await job() membaca shared sebelum jeda lalu menulis sesudahnya. Tugas lain dapat mengubah shared di antara kedua saat tersebut dan pembaruan dapat hilang.',
    exercises: [
      {
        id: 'async-generator-predict', stage: 'Prediksi', mode: 'console', title: 'Generator berhenti pada yield',
        instruction: 'Pilih tiga baris hasil pemanggilan next berturut-turut.',
        starter: 'function* letters() {\n  yield "A";\n  yield "B";\n}\nconst iterator = letters();\nconsole.log(iterator.next().value);\nconsole.log(iterator.next().value);\nconsole.log(iterator.next().done);',
        options: ['A\nB\ntrue', 'A\nB\nfalse', 'A\nA\ntrue', 'undefined\nA\nfalse'], answer: 'A\nB\ntrue',
        explanation: 'Dua next pertama berhenti pada yield A dan B. Pemanggilan ketiga mencapai akhir generator sehingga done bernilai true.',
        tests: [{ name: 'Tiga langkah iterator', inputs: {}, expected: 'A\nB\ntrue' }],
        hints: ['Setiap next melanjutkan dari posisi terakhir.', 'Setelah yield kedua tidak ada kode lagi.'],
        solution: 'function* letters() {\n  yield "A";\n  yield "B";\n}\nconst iterator = letters();\nconsole.log(iterator.next().value);\nconsole.log(iterator.next().value);\nconsole.log(iterator.next().done);',
      },
      {
        id: 'async-generator-complete', stage: 'Lengkapi', mode: 'script', title: 'Hasilkan rentang dengan generator',
        instruction: 'Lengkapi generator countTo(limit) agar yield angka 1 sampai limit. Probe mengubah iterator menjadi array.',
        starter: 'function* countTo(limit) {\n  // yield 1 sampai limit\n}', probe: '[[...countTo(3)], [...countTo(0)]]',
        tests: [{ name: 'Rentang dan batas kosong', inputs: {}, expected: [[1, 2, 3], []] }],
        hints: ['Gunakan for dengan i mulai dari 1.', 'Di setiap putaran tulis yield i.'],
        solution: 'function* countTo(limit) {\n  for (let i = 1; i <= limit; i++) {\n    yield i;\n  }\n}',
      },
      {
        id: 'async-gaps-build', stage: 'Bangun', mode: 'function', title: 'Hindari mutasi melintasi await',
        instruction: 'Buat async function stableLines(records). Untuk tiap record {name, text}, buat Promise yang menghasilkan "name: panjang" tanpa mengubah string bersama. Await Promise.all lalu kembalikan hasil dengan join("\\n").',
        starter: '// Buat async function stableLines\n', probe: 'stableLines',
        tests: [
          { name: 'Dua catatan', inputs: {}, args: [[{ name: 'a', text: 'halo' }, { name: 'b', text: 'js' }]], expected: 'a: 4\nb: 2' },
          { name: 'Tanpa catatan', inputs: {}, args: [[]], expected: '' },
        ],
        hints: ['map harus mengembalikan satu Promise per record.', 'Gabungkan array hasil setelah await Promise.all, bukan lewat variabel bersama.'],
        solution: 'async function stableLines(records) {\n  const jobs = records.map(record => {\n    return Promise.resolve(record.text).then(text => record.name + ": " + text.length);\n  });\n  const lines = await Promise.all(jobs);\n  return lines.join("\\n");\n}',
      },
    ],
  },
];
