import type { Part } from './chapter-one';

export const chapter = {
  id: 'modules',
  title: 'Modul',
  number: '10',
};

export const parts: Part[] = [
  {
    id: 'module-contracts',
    title: 'Memecah program dengan kontrak',
    description: 'Modul mengelompokkan kode, menyatakan dependensi, dan membuka antarmuka kecil untuk bagian program lain.',
    highlights: ['module', 'interface', 'dependency', 'public', 'private'],
    core: 'Program modular dibagi menjadi bagian dengan tanggung jawab jelas. Setiap modul menyebutkan apa yang dibutuhkan dan apa yang disediakan. Detail yang tidak termasuk antarmuka tetap privat sehingga perubahan internal tidak menyebar ke seluruh program.',
    model: ['dependensi masuk', 'detail internal', 'interface keluar'],
    why: 'Batas modul mengurangi jumlah hal yang harus dipahami sekaligus. Kita dapat menguji, mengganti, dan menggunakan ulang satu bagian selama kontraknya tetap sama.',
    example: 'function createPriceModule(taxRate) {\n  function tax(price) { return price * taxRate; }\n  return { total: price => price + tax(price) };\n}',
    mistake: 'Memindahkan setiap fungsi ke file berbeda belum tentu modular. Modul yang baik memiliki tujuan kohesif dan antarmuka yang lebih kecil daripada detail internalnya.',
    exercises: [
      {
        id: 'modules-contract-predict', stage: 'Prediksi', mode: 'console', title: 'Lihat antarmuka publik',
        instruction: 'Pilih nama properti yang dapat diakses pemakai modul.',
        starter: 'function createModule() {\n  function helper() { return 2; }\n  return { calculate: value => value * helper() };\n}\nconsole.log(Object.keys(createModule()).join(","));',
        options: ['helper', 'calculate', 'helper,calculate', ''], answer: 'calculate',
        explanation: 'Hanya calculate dimasukkan ke objek yang dikembalikan. helper tetap berada di dalam closure.',
        tests: [{ name: 'Interface publik', inputs: {}, expected: 'calculate' }],
        hints: ['Periksa objek setelah return.', 'Nama lokal tidak otomatis menjadi properti publik.'],
        solution: 'function createModule() {\n  function helper() { return 2; }\n  return { calculate: value => value * helper() };\n}\nconsole.log(Object.keys(createModule()).join(","));',
      },
      {
        id: 'modules-contract-complete', stage: 'Lengkapi', mode: 'script', title: 'Buka fungsi yang diperlukan',
        instruction: 'Lengkapi createCartModule agar interface hanya memiliki total, sementara sum tetap privat.',
        starter: 'function createCartModule() {\n  function sum(items) { return items.reduce((total, item) => total + item.price, 0); }\n  function total(items) { return sum(items); }\n  return {};\n}', probe: '(() => { const api = createCartModule(); return [Object.keys(api), api.total([{ price: 10 }, { price: 5 }])]; })()',
        tests: [{ name: 'API kecil', inputs: {}, expected: [['total'], 15] }],
        hints: ['Kembalikan objek dengan satu shorthand property.', 'Tulis return { total };.'],
        solution: 'function createCartModule() {\n  function sum(items) { return items.reduce((total, item) => total + item.price, 0); }\n  function total(items) { return sum(items); }\n  return { total };\n}',
      },
      {
        id: 'modules-contract-build', stage: 'Bangun', mode: 'script', title: 'Modul diskon terfokus',
        instruction: 'Buat createDiscountModule(rate). Kembalikan interface dengan apply(price) dan describe(). apply memberi price - price * rate; describe menghasilkan teks persentase bulat seperti "20%".',
        starter: '// Buat createDiscountModule\n', probe: '(() => { const module = createDiscountModule(rate); return [Object.keys(module), module.apply(price), module.describe()]; })()',
        tests: [
          { name: 'Diskon dua puluh persen', inputs: { rate: 0.2, price: 100 }, expected: [['apply', 'describe'], 80, '20%'] },
          { name: 'Diskon seperempat', inputs: { rate: 0.25, price: 200 }, expected: [['apply', 'describe'], 150, '25%'] },
        ],
        hints: ['Kembalikan objek dengan dua method publik.', 'Kedua method menutup nilai rate dari factory.'],
        solution: 'function createDiscountModule(rate) {\n  return {\n    apply(price) { return price - price * rate; },\n    describe() { return Math.round(rate * 100) + "%"; }\n  };\n}',
      },
    ],
  },
  {
    id: 'closure-modules',
    title: 'Ruang privat dengan closure',
    description: 'Factory dan closure dapat menyimpan state privat yang hanya dapat diubah melalui operasi publik.',
    highlights: ['closure', 'factory', 'private state', 'IIFE', 'encapsulation'],
    core: 'Binding lokal tetap hidup selama fungsi publik masih merujuk kepadanya. Ini memungkinkan modul menyimpan state tanpa variabel global. Pemakai hanya dapat melakukan perubahan melalui method yang sengaja diekspos.',
    model: ['factory dipanggil', 'state privat dibuat', 'method menutup state'],
    why: 'State privat menjaga invariant dan mencegah bagian program lain mengubah data tanpa melalui aturan modul.',
    example: 'function createCounter() {\n  let count = 0;\n  return { increment: () => ++count, value: () => count };\n}',
    mistake: 'Mengembalikan objek atau array state secara langsung dapat membocorkan referensi yang dapat dimutasi. Kembalikan salinan atau nilai ringkasan bila perlu.',
    exercises: [
      {
        id: 'modules-closure-predict', stage: 'Prediksi', mode: 'console', title: 'Setiap instance punya state',
        instruction: 'Pilih hasil dua counter yang dibuat oleh factory yang sama.',
        starter: 'function counter() { let n = 0; return () => ++n; }\nconst a = counter();\nconst b = counter();\nconsole.log(a(), a(), b());',
        options: ['1 2 1', '1 2 3', '1 1 1', '2 2 1'], answer: '1 2 1',
        explanation: 'a dan b dibuat oleh pemanggilan berbeda sehingga masing-masing memiliki binding n sendiri.',
        tests: [{ name: 'State terpisah', inputs: {}, expected: '1 2 1' }],
        hints: ['Factory dipanggil dua kali.', 'Pemanggilan b adalah perubahan pertama untuk state b.'],
        solution: 'function counter() { let n = 0; return () => ++n; }\nconst a = counter();\nconst b = counter();\nconsole.log(a(), a(), b());',
      },
      {
        id: 'modules-closure-complete', stage: 'Lengkapi', mode: 'script', title: 'Counter dengan API',
        instruction: 'Lengkapi createCounter agar count privat dan API menyediakan increment() serta value().',
        starter: 'function createCounter() {\n  let count = 0;\n  return {};\n}', probe: '(() => { const counter = createCounter(); return [counter.increment(), counter.increment(), counter.value(), Object.hasOwn(counter, "count")]; })()',
        tests: [{ name: 'State privat', inputs: {}, expected: [1, 2, 2, false] }],
        hints: ['Kembalikan dua method.', 'increment menaikkan count lalu mengembalikannya.'],
        solution: 'function createCounter() {\n  let count = 0;\n  return { increment() { return ++count; }, value() { return count; } };\n}',
      },
      {
        id: 'modules-closure-build', stage: 'Bangun', mode: 'script', title: 'Keranjang privat',
        instruction: 'Buat createCart() dengan items privat dan method add(item), remove(name), summary(). summary mengembalikan salinan nama item dan total harga.',
        starter: '// Buat createCart\n', probe: '(() => { const cart = createCart(); cart.add({ name: "Buku", price: 30 }); cart.add({ name: "Pena", price: 10 }); cart.remove("Pena"); return cart.summary(); })()',
        tests: [{ name: 'Tambah dan hapus', inputs: {}, expected: { names: ['Buku'], total: 30 } }],
        hints: ['Simpan const items = [] di dalam factory.', 'remove dapat mencari index lalu splice; summary memakai map dan reduce.'],
        solution: 'function createCart() {\n  const items = [];\n  return {\n    add(item) { items.push(item); },\n    remove(name) { const index = items.findIndex(item => item.name === name); if (index >= 0) items.splice(index, 1); },\n    summary() { return { names: items.map(item => item.name), total: items.reduce((sum, item) => sum + item.price, 0) }; }\n  };\n}',
      },
    ],
  },
  {
    id: 'es-modules',
    title: 'Membaca ES modules',
    description: 'ES modules memakai export untuk interface dan import untuk dependensi yang dianalisis secara statis.',
    highlights: ['export', 'import', 'default', 'named export', 'alias'],
    core: 'Setiap file module memiliki scope sendiri. Named export memiliki nama eksplisit, default export menyediakan satu nilai utama, dan import dapat memberi alias lokal. Deklarasi import/export berada di top level agar graph dependensi dapat diketahui sebelum program dijalankan.',
    model: ['module sumber export', 'import menghubungkan', 'binding lokal tersedia'],
    why: 'Dependensi eksplisit memudahkan alat build, editor, dan pembaca mengetahui hubungan antarmodule tanpa menebak global yang dipakai.',
    example: '// math.js\nexport function sum(a, b) { return a + b; }\n// app.js\nimport { sum } from "./math.js";',
    mistake: 'Named import harus memakai nama export yang tepat kecuali diberi alias. Default import tidak memakai kurung kurawal.',
    exercises: [
      {
        id: 'modules-esm-predict', stage: 'Prediksi', mode: 'console', title: 'Petakan alias import',
        instruction: 'Kode module ditampilkan sebagai teks. Pilih nama lokal yang digunakan konsumen.',
        starter: 'const source = `import { formatPrice as format } from "./money.js";`;\nconsole.log(source.includes("as format") ? "format" : "formatPrice");',
        options: ['format', 'formatPrice', 'money', 'default'], answer: 'format',
        explanation: 'as format memberi binding lokal bernama format, sedangkan nama asalnya tetap formatPrice.',
        tests: [{ name: 'Alias lokal', inputs: {}, expected: 'format' }],
        hints: ['Nama setelah as adalah nama lokal.', 'Nama sebelum as adalah export sumber.'],
        solution: 'const source = `import { formatPrice as format } from "./money.js";`;\nconsole.log(source.includes("as format") ? "format" : "formatPrice");',
      },
      {
        id: 'modules-esm-complete', stage: 'Lengkapi', mode: 'function', title: 'Bentuk named import',
        instruction: 'Lengkapi namedImport(names, path). Kembalikan string seperti import { sum, average } from "./math.js";.',
        starter: 'function namedImport(names, path) {\n  return "";\n}', probe: 'namedImport',
        tests: [
          { name: 'Dua nama', inputs: {}, args: [['sum', 'average'], './math.js'], expected: 'import { sum, average } from "./math.js";' },
          { name: 'Satu nama', inputs: {}, args: [['parse'], './parser.js'], expected: 'import { parse } from "./parser.js";' },
        ],
        hints: ['Gabungkan names dengan ", ".', 'Gunakan template literal untuk seluruh deklarasi.'],
        solution: 'function namedImport(names, path) {\n  return `import { ${names.join(", ")} } from "${path}";`;\n}',
      },
      {
        id: 'modules-esm-build', stage: 'Bangun', mode: 'function', title: 'Model graph module',
        instruction: 'Buat dependencyGraph(modules). Setiap item memiliki name dan imports. Kembalikan objek yang memetakan setiap name ke salinan array imports.',
        starter: '// Buat dependencyGraph\n', probe: 'dependencyGraph',
        tests: [
          { name: 'Tiga module', inputs: {}, args: [[{ name: 'app', imports: ['ui', 'data'] }, { name: 'ui', imports: [] }, { name: 'data', imports: ['api'] }]], expected: { app: ['ui', 'data'], ui: [], data: ['api'] } },
          { name: 'Kosong', inputs: {}, args: [[]], expected: {} },
        ],
        hints: ['Mulai dari objek kosong.', 'Untuk setiap module, simpan module.imports.slice().'],
        solution: 'function dependencyGraph(modules) {\n  const graph = {};\n  for (const module of modules) graph[module.name] = module.imports.slice();\n  return graph;\n}',
      },
    ],
  },
  {
    id: 'dependency-injection',
    title: 'Dependensi yang dapat diganti',
    description: 'Memberikan dependensi melalui parameter membuat hubungan terlihat dan komponen lebih mudah diuji.',
    highlights: ['dependency injection', 'coupling', 'parameter', 'stub', 'pure function'],
    core: 'Fungsi yang diam-diam membaca global sulit dipindahkan dan diuji. Dependency injection mengirim layanan, konfigurasi, atau fungsi yang dibutuhkan melalui parameter. Test dapat menggantinya dengan implementasi kecil dan deterministik.',
    model: ['dependensi dibuat di luar', 'dikirim ke module', 'perilaku mudah diganti'],
    why: 'Komponen tidak perlu mengetahui cara dependensi dibuat. Ia hanya bergantung pada operasi yang dijanjikan interface.',
    example: 'function createReport(formatMoney) {\n  return total => "Total: " + formatMoney(total);\n}',
    mistake: 'Injection tidak harus memakai framework atau class. Parameter fungsi biasa sering merupakan bentuk paling sederhana dan jelas.',
    exercises: [
      {
        id: 'modules-di-predict', stage: 'Prediksi', mode: 'console', title: 'Ganti dependensi saat test',
        instruction: 'Pilih hasil ketika formatter palsu dikirim ke factory.',
        starter: 'function report(format) { return value => "Total " + format(value); }\nconst fake = value => "[" + value + "]";\nconsole.log(report(fake)(25));',
        options: ['Total 25', 'Total [25]', '[Total 25]', '25'], answer: 'Total [25]',
        explanation: 'Factory memakai fungsi yang diberikan. fake membungkus angka dengan kurung siku.',
        tests: [{ name: 'Formatter terinjeksi', inputs: {}, expected: 'Total [25]' }],
        hints: ['Hitung fake(25) lebih dahulu.', 'Gabungkan hasilnya dengan "Total ".'],
        solution: 'function report(format) { return value => "Total " + format(value); }\nconst fake = value => "[" + value + "]";\nconsole.log(report(fake)(25));',
      },
      {
        id: 'modules-di-complete', stage: 'Lengkapi', mode: 'script', title: 'Laporan yang mudah diuji',
        instruction: 'Lengkapi createReport(formatMoney) agar menghasilkan API invoice(total) dengan hasil "Invoice: " diikuti formatter.',
        starter: 'function createReport(formatMoney) {\n  return {};\n}', probe: 'createReport(value => "IDR-" + value).invoice(5000)',
        tests: [{ name: 'Formatter palsu', inputs: {}, expected: 'Invoice: IDR-5000' }],
        hints: ['Kembalikan objek dengan method invoice.', 'Method memanggil formatMoney(total).'],
        solution: 'function createReport(formatMoney) {\n  return { invoice(total) { return "Invoice: " + formatMoney(total); } };\n}',
      },
      {
        id: 'modules-di-build', stage: 'Bangun', mode: 'script', title: 'Layanan ongkir terkonfigurasi',
        instruction: 'Buat createShipping(zones, round). API cost(zone, weight) menghitung zones[zone] * weight lalu memanggil round. Kembalikan null untuk zona yang tidak tersedia.',
        starter: '// Buat createShipping\n', probe: '(() => { const service = createShipping({ west: 7, east: 10 }, Math.ceil); return [service.cost("west", 2.2), service.cost("none", 2)]; })()',
        tests: [{ name: 'Konfigurasi lokal', inputs: {}, expected: [16, null] }],
        hints: ['Simpan zones dan round melalui closure.', 'Periksa Object.hasOwn(zones, zone).'],
        solution: 'function createShipping(zones, round) {\n  return { cost(zone, weight) {\n    if (!Object.hasOwn(zones, zone)) return null;\n    return round(zones[zone] * weight);\n  } };\n}',
      },
    ],
  },
  {
    id: 'commonjs-loader',
    title: 'CommonJS dan loader lokal',
    description: 'CommonJS memakai require saat runtime dan objek exports untuk membentuk antarmuka module.',
    highlights: ['CommonJS', 'require', 'exports', 'factory', 'runtime'],
    core: 'Sebelum ES modules tersedia luas, Node.js memopulerkan CommonJS. Module dijalankan sebagai fungsi yang menerima require dan exports. require dapat dipanggil saat runtime, sehingga loader perlu mencari, menjalankan, dan menyimpan hasil module.',
    model: ['require nama', 'jalankan factory', 'kembalikan exports'],
    why: 'Memahami model historis ini membantu membaca package lama dan menjelaskan mengapa cache merupakan bagian penting dari module loader.',
    example: 'function moduleFactory(require, exports) {\n  exports.double = number => number * 2;\n}',
    mistake: 'exports = value hanya mengganti binding lokal pada wrapper umum. CommonJS biasanya memakai exports.name = value atau module.exports = value.',
    exercises: [
      {
        id: 'modules-cjs-predict', stage: 'Prediksi', mode: 'console', title: 'Exports adalah interface',
        instruction: 'Pilih daftar properti setelah factory mengisi exports.',
        starter: 'const exports = {};\n(function (exports) {\n  const secret = 2;\n  exports.double = n => n * secret;\n})(exports);\nconsole.log(Object.keys(exports).join(","));',
        options: ['secret', 'double', 'secret,double', ''], answer: 'double',
        explanation: 'secret adalah binding lokal. Hanya double ditambahkan sebagai properti exports.',
        tests: [{ name: 'Interface CommonJS', inputs: {}, expected: 'double' }],
        hints: ['Object.keys hanya melihat properti objek.', 'Periksa assignment exports.double.'],
        solution: 'const exports = {};\n(function (exports) {\n  const secret = 2;\n  exports.double = n => n * secret;\n})(exports);\nconsole.log(Object.keys(exports).join(","));',
      },
      {
        id: 'modules-cjs-complete', stage: 'Lengkapi', mode: 'script', title: 'Isi objek exports',
        instruction: 'Lengkapi defineMath(exports) agar exports memiliki square yang mengembalikan kuadrat.',
        starter: 'function defineMath(exports) {\n  // Isi interface\n}', probe: '(() => { const exports = {}; defineMath(exports); return [Object.keys(exports), exports.square(6)]; })()',
        tests: [{ name: 'Named export lokal', inputs: {}, expected: [['square'], 36] }],
        hints: ['Tetapkan exports.square.', 'Nilainya sebuah function atau arrow function.'],
        solution: 'function defineMath(exports) {\n  exports.square = number => number * number;\n}',
      },
      {
        id: 'modules-cjs-build', stage: 'Bangun', mode: 'script', title: 'Registry module mini',
        instruction: 'Buat define(name, factory) dan requireLocal(name). Factory menerima exports dan hanya boleh dijalankan sekali; require kedua mengembalikan objek cache yang sama.',
        starter: 'const registry = {};\nconst cache = {};\n// Buat define dan requireLocal\n', probe: '(() => { let runs = 0; define("math", exports => { runs++; exports.value = 42; }); const first = requireLocal("math"); const second = requireLocal("math"); return [first.value, first === second, runs]; })()',
        tests: [{ name: 'Factory dicache', inputs: {}, expected: [42, true, 1] }],
        hints: ['define menyimpan factory di registry.', 'requireLocal mengecek cache, membuat exports, menjalankan factory, lalu mengembalikannya.'],
        solution: 'const registry = {};\nconst cache = {};\nfunction define(name, factory) { registry[name] = factory; }\nfunction requireLocal(name) {\n  if (Object.hasOwn(cache, name)) return cache[name];\n  const exports = {};\n  cache[name] = exports;\n  registry[name](exports);\n  return exports;\n}',
      },
    ],
  },
  {
    id: 'cache-cycles',
    title: 'Cache dan dependensi melingkar',
    description: 'Loader menyimpan interface sebelum evaluasi agar siklus module tidak memulai evaluasi tanpa akhir.',
    highlights: ['cache', 'cycle', 'loading', 'loaded', 'partial interface'],
    core: 'Jika A membutuhkan B dan B membutuhkan A, loader harus menaruh objek exports A di cache sebelum menjalankan A. Ketika B meminta A, ia menerima interface A yang mungkin belum lengkap. Siklus dapat berjalan, tetapi membaca export terlalu awal tetap berisiko.',
    model: ['buat exports', 'cache sebelum factory', 'factory mengisi bertahap'],
    why: 'Urutan cache menjelaskan bagaimana loader menghentikan recursion dan mengapa desain graph tanpa siklus biasanya lebih mudah dipahami.',
    example: 'const exports = {};\ncache[name] = exports; // sebelum factory\nfactory(requireLocal, exports);',
    mistake: 'Cache bukan hanya optimasi. Ia juga memastikan satu module memiliki satu instance state dan membantu loader menghadapi dependensi melingkar.',
    exercises: [
      {
        id: 'modules-cache-predict', stage: 'Prediksi', mode: 'console', title: 'Module dijalankan sekali',
        instruction: 'Pilih jumlah eksekusi factory setelah dua require.',
        starter: 'let runs = 0;\nconst cache = {};\nfunction requireOnce(name) {\n  if (!cache[name]) cache[name] = { value: ++runs };\n  return cache[name];\n}\nrequireOnce("a");\nrequireOnce("a");\nconsole.log(runs);',
        options: ['0', '1', '2', 'undefined'], answer: '1',
        explanation: 'Pemanggilan kedua menemukan nilai cache dan tidak menjalankan inisialisasi lagi.',
        tests: [{ name: 'Cache satu instance', inputs: {}, expected: '1' }],
        hints: ['Setelah require pertama cache.a tersedia.', 'Cabang inisialisasi dilewati pada require kedua.'],
        solution: 'let runs = 0;\nconst cache = {};\nfunction requireOnce(name) {\n  if (!cache[name]) cache[name] = { value: ++runs };\n  return cache[name];\n}\nrequireOnce("a");\nrequireOnce("a");\nconsole.log(runs);',
      },
      {
        id: 'modules-cache-complete', stage: 'Lengkapi', mode: 'script', title: 'Cache sebelum factory',
        instruction: 'Lengkapi requireLocal dengan menaruh exports di cache sebelum factory dipanggil.',
        starter: 'const factories = { a(require, exports) { exports.name = "A"; exports.fromB = require("b").name; }, b(require, exports) { exports.name = "B"; exports.fromA = require("a").name; } };\nconst cache = {};\nfunction requireLocal(name) {\n  if (cache[name]) return cache[name];\n  const exports = {};\n  factories[name](requireLocal, exports);\n  return exports;\n}', probe: '(() => { const a = requireLocal("a"); return [a.name, a.fromB, cache.b.fromA]; })()',
        tests: [{ name: 'Siklus berhenti', inputs: {}, expected: ['A', 'B', 'A'] }],
        hints: ['Tambahkan cache[name] = exports.', 'Baris itu harus muncul sebelum factories[name](...).'],
        solution: 'const factories = { a(require, exports) { exports.name = "A"; exports.fromB = require("b").name; }, b(require, exports) { exports.name = "B"; exports.fromA = require("a").name; } };\nconst cache = {};\nfunction requireLocal(name) {\n  if (cache[name]) return cache[name];\n  const exports = {};\n  cache[name] = exports;\n  factories[name](requireLocal, exports);\n  return exports;\n}',
      },
      {
        id: 'modules-cache-build', stage: 'Bangun', mode: 'script', title: 'Lacak status module',
        instruction: 'Buat loader(factories) yang mengembalikan require(name) dan status(name). Status berubah "missing" → "loading" → "loaded". Factory menerima require dan exports.',
        starter: '// Buat loader\n', probe: '(() => { const system = loader({ value(require, exports) { exports.n = 7; } }); const before = system.status("value"); const value = system.require("value"); return [before, system.status("value"), value.n]; })()',
        tests: [{ name: 'Transisi status', inputs: {}, expected: ['missing', 'loaded', 7] }],
        hints: ['Simpan cache berisi { status, exports }.', 'Masukkan loading sebelum factory dan ubah menjadi loaded setelahnya.'],
        solution: 'function loader(factories) {\n  const cache = {};\n  function require(name) {\n    if (cache[name]) return cache[name].exports;\n    const entry = { status: "loading", exports: {} };\n    cache[name] = entry;\n    factories[name](require, entry.exports);\n    entry.status = "loaded";\n    return entry.exports;\n  }\n  return { require, status(name) { return cache[name]?.status ?? "missing"; } };\n}',
      },
    ],
  },
  {
    id: 'packages-build-tools',
    title: 'Package dan alat build',
    description: 'Package mendistribusikan module bersama metadata; build tools menyiapkan source untuk lingkungan tujuan.',
    highlights: ['package', 'npm', 'version', 'license', 'bundle', 'compile', 'minify'],
    core: 'Package memiliki nama, versi, dependensi, dan lisensi. Package manager membantu memasang graph dependensi. Compiler mengubah bentuk source, bundler menggabungkan graph module, dan minifier mengecilkan output. Setiap dependensi juga membawa biaya pemeliharaan dan keamanan.',
    model: ['source + package metadata', 'install dan build', 'artifact untuk dijalankan'],
    why: 'Memeriksa kualitas, lisensi, ukuran, dan kebutuhan package mencegah proyek bergantung pada kode yang tidak sesuai atau tidak dipelihara.',
    example: 'const pkg = { name: "tiny-tool", version: "1.2.0", license: "MIT", dependencies: {} };',
    mistake: 'Jangan menambah package hanya karena tersedia. Bandingkan biaya dependensi dengan kompleksitas fungsi yang digantikan.',
    exercises: [
      {
        id: 'modules-tools-predict', stage: 'Prediksi', mode: 'console', title: 'Kenali tahap build',
        instruction: 'Pilih nama proses yang menggabungkan banyak module menjadi satu atau beberapa file output.',
        starter: 'const process = "combine dependency graph into output files";\nconsole.log(process.includes("dependency graph") ? "bundle" : "minify");',
        options: ['compile', 'bundle', 'minify', 'install'], answer: 'bundle',
        explanation: 'Bundler menelusuri graph dependensi dan menggabungkan module menjadi artifact output.',
        tests: [{ name: 'Klasifikasi bundling', inputs: {}, expected: 'bundle' }],
        hints: ['Minify berfokus mengecilkan source.', 'Kata kuncinya adalah dependency graph.'],
        solution: 'const process = "combine dependency graph into output files";\nconsole.log(process.includes("dependency graph") ? "bundle" : "minify");',
      },
      {
        id: 'modules-tools-complete', stage: 'Lengkapi', mode: 'function', title: 'Pilih package yang diizinkan',
        instruction: 'Lengkapi allowedPackages(packages, licenses). Kembalikan nama package yang license-nya ada dalam licenses dan deprecated bukan true.',
        starter: 'function allowedPackages(packages, licenses) {\n  return [];\n}', probe: 'allowedPackages',
        tests: [
          { name: 'Filter metadata', inputs: {}, args: [[{ name: 'a', license: 'MIT' }, { name: 'b', license: 'GPL' }, { name: 'c', license: 'MIT', deprecated: true }], ['MIT']], expected: ['a'] },
          { name: 'Tidak ada', inputs: {}, args: [[{ name: 'x', license: '' }], ['MIT']], expected: [] },
        ],
        hints: ['Gunakan filter lalu map.', 'Syarat kedua adalah pkg.deprecated !== true.'],
        solution: 'function allowedPackages(packages, licenses) {\n  return packages.filter(pkg => licenses.includes(pkg.license) && pkg.deprecated !== true).map(pkg => pkg.name);\n}',
      },
      {
        id: 'modules-tools-build', stage: 'Bangun', mode: 'function', title: 'Audit metadata package',
        instruction: 'Buat auditPackages(packages). Kembalikan { duplicateNames, missingLicenses, missingDependencies }. missingDependencies berisi "package->dependency" jika dependency tidak ada dalam daftar nama.',
        starter: '// Buat auditPackages\n', probe: 'auditPackages',
        tests: [
          { name: 'Temukan tiga masalah', inputs: {}, args: [[{ name: 'app', license: 'MIT', dependencies: ['lib', 'ghost'] }, { name: 'lib', license: '', dependencies: [] }, { name: 'lib', license: 'MIT', dependencies: [] }]], expected: { duplicateNames: ['lib'], missingLicenses: ['lib'], missingDependencies: ['app->ghost'] } },
          { name: 'Metadata bersih', inputs: {}, args: [[{ name: 'app', license: 'MIT', dependencies: [] }]], expected: { duplicateNames: [], missingLicenses: [], missingDependencies: [] } },
        ],
        hints: ['Buat Set names dan Set seen untuk duplikasi.', 'Periksa setiap dependency terhadap names.'],
        solution: 'function auditPackages(packages) {\n  const names = new Set(packages.map(pkg => pkg.name));\n  const seen = new Set(), duplicates = new Set();\n  const missingLicenses = [];\n  const missingDependencies = [];\n  for (const pkg of packages) {\n    if (seen.has(pkg.name)) duplicates.add(pkg.name);\n    seen.add(pkg.name);\n    if (!pkg.license) missingLicenses.push(pkg.name);\n    for (const dependency of pkg.dependencies ?? []) if (!names.has(dependency)) missingDependencies.push(pkg.name + "->" + dependency);\n  }\n  return { duplicateNames: [...duplicates], missingLicenses, missingDependencies };\n}',
      },
    ],
  },
  {
    id: 'api-design',
    title: 'Desain API dan komposisi',
    description: 'Module yang fokus dan memakai bentuk data biasa lebih mudah digabungkan, diuji, dan diganti.',
    highlights: ['API', 'composition', 'cohesion', 'adapter', 'integration'],
    core: 'API yang baik konsisten dengan kosakata platform, meminimalkan state tersembunyi, dan mengembalikan data yang mudah diproses. Module kecil dapat dirangkai menjadi pipeline parse, validate, transform, dan summarize.',
    model: ['module fokus', 'data biasa sebagai penghubung', 'komposisi alur'],
    why: 'Komposisi lewat data dan interface sederhana mengurangi coupling. Satu tahap dapat diganti tanpa menulis ulang seluruh alur.',
    example: 'const run = text => summarize(validate(parse(text)));',
    mistake: 'API yang terlalu umum sering sulit dipahami. Pilih operasi yang benar-benar dibutuhkan dan beri nama berdasarkan domain masalah.',
    exercises: [
      {
        id: 'modules-api-predict', stage: 'Prediksi', mode: 'console', title: 'Rangkai fungsi murni',
        instruction: 'Pilih hasil pipeline parse lalu summarize.',
        starter: 'const parse = text => text.split(",").map(Number);\nconst summarize = values => values.reduce((a, b) => a + b, 0);\nconsole.log(summarize(parse("2,3,5")));',
        options: ['235', '10', '[2,3,5]', 'NaN'], answer: '10',
        explanation: 'parse menghasilkan array angka [2, 3, 5], lalu summarize menjumlahkannya.',
        tests: [{ name: 'Komposisi data', inputs: {}, expected: '10' }],
        hints: ['split menghasilkan tiga teks.', 'map(Number) mengubahnya menjadi angka sebelum reduce.'],
        solution: 'const parse = text => text.split(",").map(Number);\nconst summarize = values => values.reduce((a, b) => a + b, 0);\nconsole.log(summarize(parse("2,3,5")));',
      },
      {
        id: 'modules-api-complete', stage: 'Lengkapi', mode: 'function', title: 'Adaptor bentuk data',
        instruction: 'Lengkapi toWeightMap(edges). Setiap edge [from, to, weight] menjadi properti "from->to" pada objek baru. Jangan ubah input.',
        starter: 'function toWeightMap(edges) {\n  return {};\n}', probe: 'toWeightMap',
        tests: [
          { name: 'Dua sisi', inputs: {}, args: [[['A', 'B', 4], ['B', 'C', 7]]], expected: { 'A->B': 4, 'B->C': 7 } },
          { name: 'Kosong', inputs: {}, args: [[]], expected: {} },
        ],
        hints: ['Mulai dengan const result = {}.', 'Gunakan destructuring dalam loop.'],
        solution: 'function toWeightMap(edges) {\n  const result = {};\n  for (const [from, to, weight] of edges) result[from + "->" + to] = weight;\n  return result;\n}',
      },
      {
        id: 'modules-api-build', stage: 'Bangun', mode: 'script', title: 'Pipeline jadwal mini',
        instruction: 'Buat createScheduleApp({ parse, validate, summarize }). Method run(text) merangkai ketiganya. Jika validate(items) false, kembalikan { ok: false, error: "invalid" }; jika true, { ok: true, value: summarize(items) }.',
        starter: '// Buat createScheduleApp\n', probe: 'createScheduleApp({ parse: text => text.split(",").filter(Boolean), validate: items => items.every(item => item.includes(":")), summarize: items => items.length }).run(text)',
        tests: [
          { name: 'Jadwal valid', inputs: { text: '09:00 standup,13:00 review' }, expected: { ok: true, value: 2 } },
          { name: 'Jadwal invalid', inputs: { text: 'standup,13:00 review' }, expected: { ok: false, error: 'invalid' } },
          { name: 'Jadwal kosong', inputs: { text: '' }, expected: { ok: true, value: 0 } },
        ],
        hints: ['Kembalikan objek dengan method run.', 'Panggil parse, periksa validate, lalu panggil summarize hanya untuk data valid.'],
        solution: 'function createScheduleApp({ parse, validate, summarize }) {\n  return { run(text) {\n    const items = parse(text);\n    if (!validate(items)) return { ok: false, error: "invalid" };\n    return { ok: true, value: summarize(items) };\n  } };\n}',
      },
    ],
  },
];
