import type { Part } from './chapter-one';

export const chapter = {
  id: 'object-oriented-programming',
  title: 'Kehidupan Rahasia Objek',
  number: '06',
};

export const parts: Part[] = [
  {
    id: 'interfaces-methods-this',
    title: 'Antarmuka, method, dan this',
    description: 'Method memberi objek perilaku, sedangkan this menghubungkan perilaku itu dengan objek penerima panggilan.',
    highlights: ['method', 'this', 'call', 'arrow function', 'antarmuka'],
    core: 'Method adalah properti yang nilainya fungsi. Pada panggilan object.method(), this merujuk ke object. Nilainya ditentukan oleh cara fungsi dipanggil, bukan tempat fungsi ditulis. Method call dapat memberi penerima secara eksplisit, sedangkan arrow function tidak membuat this baru.',
    model: ['objek.method()', 'this → objek penerima', 'hasil'],
    why: 'Antarmuka yang kecil membuat pemakai cukup memahami operasi publik. Detail data dan langkah kerja tetap berada di dalam objek sehingga bagian program lain tidak perlu ikut mengaturnya.',
    example: 'const meter = {\n  value: 2,\n  add(amount) {\n    this.value += amount;\n    return this.value;\n  }\n};\nconsole.log(meter.add(3));',
    mistake: 'Mengambil method lalu memanggilnya sebagai fungsi biasa dapat menghilangkan penerima this. Jangan mengganti method yang membutuhkan this dengan arrow function karena arrow function mewarisi this dari lingkup luar.',
    exercises: [
      {
        id: 'oop-methods-predict', stage: 'Prediksi', mode: 'console', title: 'Siapa penerima method?',
        instruction: 'Pilih dua baris keluaran ketika method dipanggil biasa lalu dengan call.',
        starter: 'const badge = { label: "A", show() { console.log(this.label); } };\nconst other = { label: "B" };\nbadge.show();\nbadge.show.call(other);',
        options: ['A\nA', 'A\nB', 'B\nA', 'undefined\nB'], answer: 'A\nB',
        explanation: 'Panggilan pertama menerima badge sebagai this. call memberi other sebagai this pada panggilan kedua.',
        tests: [{ name: 'Penerima panggilan', inputs: {}, expected: 'A\nB' }],
        hints: ['Lihat objek di sebelah kiri titik.', 'Argumen pertama call menjadi this.'],
        solution: 'const badge = { label: "A", show() { console.log(this.label); } };\nconst other = { label: "B" };\nbadge.show();\nbadge.show.call(other);',
      },
      {
        id: 'oop-methods-complete', stage: 'Lengkapi', mode: 'script', title: 'Perbarui keadaan lewat method',
        instruction: 'Lengkapi method add agar menambah amount ke value dan mengembalikan nilai terbaru.',
        starter: 'const counter = {\n  value: 4,\n  add(amount) {\n    // Gunakan this\n  }\n};', probe: '[counter.add(3), counter.add(2), counter.value]',
        tests: [{ name: 'Dua penambahan', inputs: {}, expected: [7, 9, 9] }],
        hints: ['Ubah this.value dengan amount.', 'Kembalikan this.value setelah diperbarui.'],
        solution: 'const counter = {\n  value: 4,\n  add(amount) {\n    this.value += amount;\n    return this.value;\n  }\n};',
      },
      {
        id: 'oop-methods-build', stage: 'Bangun', mode: 'function', title: 'Buat akun poin',
        instruction: 'Buat createPoints(start) yang mengembalikan objek dengan value serta method earn(amount) dan spend(amount). Keduanya mengubah lalu mengembalikan value.',
        starter: '// Buat fungsi createPoints\n', probe: '(start, earned, spent) => { const p = createPoints(start); return [p.earn(earned), p.spend(spent), p.value]; }',
        tests: [
          { name: 'Perubahan berurutan', inputs: {}, args: [10, 5, 3], expected: [15, 12, 12] },
          { name: 'Mulai nol', inputs: {}, args: [0, 7, 2], expected: [7, 5, 5] },
        ],
        hints: ['Kembalikan object literal.', 'Di dalam method, akses value sebagai this.value.'],
        solution: 'function createPoints(start) {\n  return {\n    value: start,\n    earn(amount) { this.value += amount; return this.value; },\n    spend(amount) { this.value -= amount; return this.value; }\n  };\n}',
      },
    ],
  },
  {
    id: 'prototype-chain',
    title: 'Rantai prototipe dan properti sendiri',
    description: 'Objek dapat mewarisi properti dari objek lain tanpa menyalin properti bersama ke setiap instance.',
    highlights: ['prototype', 'Object.create', 'Object.getPrototypeOf', 'Object.hasOwn', 'in'],
    core: 'Jika properti tidak ditemukan pada objek, JavaScript mencarinya sepanjang rantai prototipe. Object.create(proto) membuat objek dengan proto tertentu. Penugasan biasanya membuat properti sendiri yang menutupi nama sama pada prototipe.',
    model: ['objek sendiri', 'prototype', 'Object.prototype', 'null'],
    why: 'Prototipe menjadi tempat efisien untuk perilaku bersama, sedangkan setiap objek tetap menyimpan keadaan khususnya sendiri.',
    example: 'const shared = { kind: "catatan" };\nconst item = Object.create(shared);\nitem.title = "Belajar";\nconsole.log(item.kind, Object.hasOwn(item, "kind"));',
    mistake: 'Operator in juga melihat properti warisan. Gunakan Object.hasOwn ketika aturan benar-benar membutuhkan properti yang tersimpan langsung pada objek.',
    exercises: [
      {
        id: 'oop-prototype-predict', stage: 'Prediksi', mode: 'console', title: 'Properti yang menutupi warisan',
        instruction: 'Pilih keluaran setelah satu objek menutupi nilai dari prototipenya.',
        starter: 'const defaults = { color: "biru" };\nconst card = Object.create(defaults);\nconsole.log(card.color);\ncard.color = "merah";\nconsole.log(card.color + ":" + defaults.color);',
        options: ['biru\nmerah:biru', 'biru\nmerah:merah', 'undefined\nmerah:biru', 'merah\nbiru:merah'], answer: 'biru\nmerah:biru',
        explanation: 'Pembacaan awal naik ke defaults. Penugasan membuat color milik card dan tidak mengubah defaults.',
        tests: [{ name: 'Shadowing properti', inputs: {}, expected: 'biru\nmerah:biru' }],
        hints: ['card mula-mula tidak punya color sendiri.', 'Penugasan dilakukan pada card.'],
        solution: 'const defaults = { color: "biru" };\nconst card = Object.create(defaults);\nconsole.log(card.color);\ncard.color = "merah";\nconsole.log(card.color + ":" + defaults.color);',
      },
      {
        id: 'oop-prototype-complete', stage: 'Lengkapi', mode: 'function', title: 'Kenali sumber properti',
        instruction: 'Lengkapi propertySource(object, key): kembalikan "own", "inherited", atau "missing".',
        starter: 'function propertySource(object, key) {\n  // Periksa properti sendiri, lalu rantai prototipe\n}', probe: 'propertySource',
        tests: [
          { name: 'Properti sendiri', inputs: {}, args: [{ x: 1 }, 'x'], expected: 'own' },
          { name: 'Properti warisan standar', inputs: {}, args: [{}, 'toString'], expected: 'inherited' },
          { name: 'Tidak ditemukan', inputs: {}, args: [{}, 'missingKey'], expected: 'missing' },
        ],
        hints: ['Mulai dengan Object.hasOwn(object, key).', 'Jika bukan milik sendiri, key in object masih dapat true.'],
        solution: 'function propertySource(object, key) {\n  if (Object.hasOwn(object, key)) return "own";\n  if (key in object) return "inherited";\n  return "missing";\n}',
      },
      {
        id: 'oop-prototype-build', stage: 'Bangun', mode: 'function', title: 'Profil berbagi perilaku',
        instruction: 'Buat createProfile(name) memakai Object.create(profileMethods). profileMethods harus memiliki greet() yang menghasilkan "Halo, NAME".',
        starter: 'const profileMethods = {\n  // Tambahkan greet\n};\n\nfunction createProfile(name) {\n  // Buat dan isi profil\n}', probe: '(a, b) => { const first = createProfile(a); const second = createProfile(b); return [first.greet(), second.greet(), Object.getPrototypeOf(first) === Object.getPrototypeOf(second)]; }',
        tests: [
          { name: 'Dua profil', inputs: {}, args: ['Ayu', 'Bima'], expected: ['Halo, Ayu', 'Halo, Bima', true] },
          { name: 'Nama lain', inputs: {}, args: ['Nara', 'Raka'], expected: ['Halo, Nara', 'Halo, Raka', true] },
        ],
        hints: ['Gunakan Object.create(profileMethods).', 'Simpan name pada objek baru sebelum dikembalikan.'],
        solution: 'const profileMethods = {\n  greet() { return "Halo, " + this.name; }\n};\n\nfunction createProfile(name) {\n  const profile = Object.create(profileMethods);\n  profile.name = name;\n  return profile;\n}',
      },
    ],
  },
  {
    id: 'classes-private-state',
    title: 'Class, instance, dan data privat',
    description: 'Class menyatukan pembuatan instance, method bersama, dan aturan akses terhadap keadaan internal.',
    highlights: ['class', 'constructor', 'new', '#private', 'instance'],
    core: 'Constructor mengisi properti khusus tiap instance saat new dipakai. Method class ditempatkan pada prototype. Field dengan awalan # hanya dapat diakses dari tubuh class, sehingga perubahan data dapat diarahkan melalui method publik.',
    model: ['new Class(data)', 'constructor', 'instance.method()'],
    why: 'Enkapsulasi menjaga invariant: pengguna meminta operasi, bukan mengubah representasi internal sesuka hati.',
    example: 'class Ticket {\n  #used = false;\n  use() {\n    if (this.#used) return false;\n    this.#used = true;\n    return true;\n  }\n}',
    mistake: 'Class harus dipanggil dengan new. Field privat juga wajib dideklarasikan di dalam class sebelum digunakan.',
    exercises: [
      {
        id: 'oop-class-predict', stage: 'Prediksi', mode: 'console', title: 'Method dibagi oleh instance',
        instruction: 'Pilih keluaran pemeriksaan instance dan lokasi method.',
        starter: 'class Note { show() { return "ok"; } }\nconst note = new Note();\nconsole.log(note instanceof Note);\nconsole.log(Object.hasOwn(note, "show"));',
        options: ['true\nfalse', 'true\ntrue', 'false\ntrue', 'false\nfalse'], answer: 'true\nfalse',
        explanation: 'note adalah instance Note, tetapi show berada pada Note.prototype, bukan sebagai properti note sendiri.',
        tests: [{ name: 'Instance dan prototype', inputs: {}, expected: 'true\nfalse' }],
        hints: ['new menghubungkan instance ke prototype class.', 'Method class tidak disalin ke instance.'],
        solution: 'class Note { show() { return "ok"; } }\nconst note = new Note();\nconsole.log(note instanceof Note);\nconsole.log(Object.hasOwn(note, "show"));',
      },
      {
        id: 'oop-class-complete', stage: 'Lengkapi', mode: 'script', title: 'Lengkapi sebuah class',
        instruction: 'Lengkapi constructor dan toggle() agar lamp menyimpan label dan membalik nilai on.',
        starter: 'class Lamp {\n  constructor(label) {\n    // Simpan label dan mulai dalam keadaan mati\n  }\n  toggle() {\n    // Balik nilai on dan kembalikan nilainya\n  }\n}\nconst lamp = new Lamp("Meja");', probe: '[lamp.label, lamp.toggle(), lamp.toggle(), lamp.on]',
        tests: [{ name: 'Keadaan lampu', inputs: {}, expected: ['Meja', true, false, false] }],
        hints: ['Isi this.label dan this.on di constructor.', 'Gunakan this.on = !this.on.'],
        solution: 'class Lamp {\n  constructor(label) {\n    this.label = label;\n    this.on = false;\n  }\n  toggle() {\n    this.on = !this.on;\n    return this.on;\n  }\n}\nconst lamp = new Lamp("Meja");',
      },
      {
        id: 'oop-class-build', stage: 'Bangun', mode: 'function', title: 'Dompet dengan saldo privat',
        instruction: 'Buat class Wallet dengan #balance, deposit(amount), spend(amount), dan getter balance. Tolak amount <= 0; spend juga gagal jika saldo kurang. Operasi mengembalikan boolean.',
        starter: '// Buat class Wallet\n', probe: '(start, deposit, spend) => { const wallet = new Wallet(start); return [wallet.deposit(deposit), wallet.spend(spend), wallet.balance]; }',
        tests: [
          { name: 'Operasi valid', inputs: {}, args: [10, 5, 8], expected: [true, true, 7] },
          { name: 'Nominal ditolak', inputs: {}, args: [4, -2, 8], expected: [false, false, 4] },
        ],
        hints: ['Deklarasikan #balance; sebelum constructor.', 'Periksa amount sebelum mengubah saldo.'],
        solution: 'class Wallet {\n  #balance;\n  constructor(start) { this.#balance = start; }\n  deposit(amount) {\n    if (amount <= 0) return false;\n    this.#balance += amount;\n    return true;\n  }\n  spend(amount) {\n    if (amount <= 0 || amount > this.#balance) return false;\n    this.#balance -= amount;\n    return true;\n  }\n  get balance() { return this.#balance; }\n}',
      },
    ],
  },
  {
    id: 'maps-keyed-data',
    title: 'Map untuk data berkunci',
    description: 'Map menyimpan pasangan key–value tanpa jebakan properti warisan dan tanpa membatasi key pada string.',
    highlights: ['Map', 'set', 'get', 'has', 'size', 'key'],
    core: 'Map menyediakan set, get, has, delete, dan size. Berbeda dari object literal, key Map dapat berupa nilai apa pun dan nama seperti toString tidak muncul kecuali memang dimasukkan.',
    model: ['key', 'Map', 'value'],
    why: 'Pilih Map ketika data benar-benar merupakan kamus dinamis, terutama saat key bukan string atau perlu dibedakan dari properti bawaan objek.',
    example: 'const stock = new Map();\nstock.set("apel", 3);\nstock.set("apel", stock.get("apel") + 1);\nconsole.log(stock.get("apel"));',
    mistake: 'map[key] tidak memakai penyimpanan internal Map. Gunakan map.get(key) dan map.set(key, value).',
    exercises: [
      {
        id: 'oop-map-predict', stage: 'Prediksi', mode: 'console', title: 'Key yang tidak pernah dimasukkan',
        instruction: 'Bandingkan operator in pada objek biasa dengan has pada Map kosong.',
        starter: 'const objectTable = {};\nconst mapTable = new Map();\nconsole.log("toString" in objectTable);\nconsole.log(mapTable.has("toString"));',
        options: ['true\nfalse', 'false\nfalse', 'true\ntrue', 'false\ntrue'], answer: 'true\nfalse',
        explanation: 'Objek biasa mewarisi toString. Map hanya melaporkan key yang benar-benar tersimpan.',
        tests: [{ name: 'Objek dan Map', inputs: {}, expected: 'true\nfalse' }],
        hints: ['Objek literal memiliki prototype.', 'Map kosong belum mempunyai key apa pun.'],
        solution: 'const objectTable = {};\nconst mapTable = new Map();\nconsole.log("toString" in objectTable);\nconsole.log(mapTable.has("toString"));',
      },
      {
        id: 'oop-map-complete', stage: 'Lengkapi', mode: 'function', title: 'Hitung frekuensi dengan Map',
        instruction: 'Lengkapi countWords(words) agar mengembalikan Map frekuensi setiap kata.',
        starter: 'function countWords(words) {\n  const counts = new Map();\n  // Isi counts\n  return counts;\n}', probe: '(words) => Array.from(countWords(words).entries())',
        tests: [
          { name: 'Kata berulang', inputs: {}, args: [['js', 'web', 'js']], expected: [['js', 2], ['web', 1]] },
          { name: 'Kosong', inputs: {}, args: [[]], expected: [] },
        ],
        hints: ['Ambil nilai lama dengan counts.get(word) ?? 0.', 'Simpan nilai baru memakai set.'],
        solution: 'function countWords(words) {\n  const counts = new Map();\n  for (const word of words) {\n    counts.set(word, (counts.get(word) ?? 0) + 1);\n  }\n  return counts;\n}',
      },
      {
        id: 'oop-map-build', stage: 'Bangun', mode: 'function', title: 'Index produk',
        instruction: 'Buat indexProducts(products) yang mengembalikan fungsi pencari berdasarkan id. Gunakan Map di dalamnya; pencarian id yang tidak ada menghasilkan null.',
        starter: '// Buat fungsi indexProducts\n', probe: '(products, ids) => { const findProduct = indexProducts(products); return ids.map(id => findProduct(id)); }',
        tests: [
          { name: 'Cari beberapa id', inputs: {}, args: [[{ id: 'a', price: 5 }, { id: 'b', price: 8 }], ['b', 'x']], expected: [{ id: 'b', price: 8 }, null] },
          { name: 'Index kosong', inputs: {}, args: [[], ['a']], expected: [null] },
        ],
        hints: ['Isi Map dari setiap product.id.', 'Kembalikan arrow function yang memakai map.get(id) ?? null.'],
        solution: 'function indexProducts(products) {\n  const byId = new Map();\n  for (const product of products) byId.set(product.id, product);\n  return id => byId.get(id) ?? null;\n}',
      },
    ],
  },
  {
    id: 'polymorphic-interfaces',
    title: 'Polimorfisme melalui antarmuka',
    description: 'Kode umum dapat memakai berbagai bentuk objek selama semuanya memenuhi operasi yang sama.',
    highlights: ['polimorfisme', 'antarmuka', 'method', 'toString', 'duck typing'],
    core: 'Polimorfisme berarti pemanggil bergantung pada kemampuan, bukan identitas class. Jika setiap nilai menyediakan method yang disepakati, fungsi umum dapat menggunakannya tanpa rangkaian pemeriksaan tipe.',
    model: ['tipe berbeda', 'method sama', 'fungsi umum'],
    why: 'Ketergantungan pada antarmuka kecil memudahkan penambahan tipe baru tanpa mengubah algoritma yang sudah ada.',
    example: 'function labels(items) {\n  return items.map(item => item.toText());\n}\nconst item = { toText() { return "Satu"; } };\nconsole.log(labels([item]));',
    mistake: 'Polimorfisme bukan berarti semua objek aman dipakai. Antarmuka tetap sebuah kontrak: method harus ada dan menghasilkan bentuk yang dijanjikan.',
    exercises: [
      {
        id: 'oop-polymorphism-predict', stage: 'Prediksi', mode: 'console', title: 'Satu fungsi, dua perilaku',
        instruction: 'Pilih keluaran fungsi yang hanya memanggil antarmuka describe().',
        starter: 'function describe(item) { return item.describe(); }\nconst text = { describe() { return "teks"; } };\nconst number = { describe() { return "angka"; } };\nconsole.log(describe(text) + "," + describe(number));',
        options: ['teks,angka', 'object,object', 'describe,describe', 'undefined,undefined'], answer: 'teks,angka',
        explanation: 'describe tidak perlu mengetahui bentuk internal objek; masing-masing menyediakan method yang sama.',
        tests: [{ name: 'Dua implementasi', inputs: {}, expected: 'teks,angka' }],
        hints: ['Perhatikan return dari tiap method.', 'Fungsi umum hanya meneruskan panggilan.'],
        solution: 'function describe(item) { return item.describe(); }\nconst text = { describe() { return "teks"; } };\nconst number = { describe() { return "angka"; } };\nconsole.log(describe(text) + "," + describe(number));',
      },
      {
        id: 'oop-polymorphism-complete', stage: 'Lengkapi', mode: 'script', title: 'Jumlahkan luas berbagai bentuk',
        instruction: 'Lengkapi totalArea agar menjumlahkan hasil area() tanpa memeriksa class objek.',
        starter: 'function totalArea(shapes) {\n  // Gunakan antarmuka area()\n}\nconst square = { area() { return 9; } };\nconst rectangle = { area() { return 8; } };', probe: 'totalArea([square, rectangle])',
        tests: [{ name: 'Dua bentuk', inputs: {}, expected: 17 }],
        hints: ['Panggil shape.area() untuk setiap elemen.', 'Gunakan loop dan total, atau reduce.'],
        solution: 'function totalArea(shapes) {\n  let total = 0;\n  for (const shape of shapes) total += shape.area();\n  return total;\n}\nconst square = { area() { return 9; } };\nconst rectangle = { area() { return 8; } };',
      },
      {
        id: 'oop-polymorphism-build', stage: 'Bangun', mode: 'script', title: 'Pengirim pesan yang dapat ditukar',
        instruction: 'Buat class UpperChannel dan LowerChannel dengan send(text). Buat deliver(channel, texts) yang memanggil antarmuka itu untuk setiap teks.',
        starter: '// Buat dua class dan fungsi deliver\n', probe: '[deliver(new UpperChannel(), ["Halo", "Web"]), deliver(new LowerChannel(), ["Halo", "Web"])]',
        tests: [{ name: 'Dua channel', inputs: {}, expected: [['HALO', 'WEB'], ['halo', 'web']] }],
        hints: ['send pada tiap class mengubah kapitalisasi teks.', 'deliver dapat memakai texts.map(text => channel.send(text)).'],
        solution: 'class UpperChannel {\n  send(text) { return text.toUpperCase(); }\n}\nclass LowerChannel {\n  send(text) { return text.toLowerCase(); }\n}\nfunction deliver(channel, texts) {\n  return texts.map(text => channel.send(text));\n}',
      },
    ],
  },
  {
    id: 'getters-setters-statics',
    title: 'Getter, setter, dan method statis',
    description: 'Akses properti dapat menjalankan perhitungan, sedangkan method statis menyediakan operasi milik tipe.',
    highlights: ['get', 'set', 'static', 'factory', 'constructor'],
    core: 'Getter dipanggil saat properti dibaca dan setter saat properti ditulis. Keduanya dapat menjaga satu representasi internal. Method static berada pada constructor, bukan pada instance, dan sering dipakai sebagai factory bernama.',
    model: ['baca/tulis properti', 'konversi internal', 'static factory'],
    why: 'Antarmuka terasa sederhana tanpa menyimpan data turunan dua kali, dan factory statis menjelaskan cara alternatif membuat instance.',
    example: 'class Length {\n  constructor(meters) { this.meters = meters; }\n  get centimeters() { return this.meters * 100; }\n  static fromCentimeters(value) { return new Length(value / 100); }\n}',
    mistake: 'Memanggil getter dengan tanda kurung adalah salah karena getter dibaca seperti properti. Method static dipanggil pada class, bukan instance.',
    exercises: [
      {
        id: 'oop-accessors-predict', stage: 'Prediksi', mode: 'console', title: 'Satu nilai, dua satuan',
        instruction: 'Pilih keluaran setelah setter mengubah nilai internal.',
        starter: 'class Temperature {\n  constructor(c) { this.c = c; }\n  get f() { return this.c * 1.8 + 32; }\n  set f(value) { this.c = (value - 32) / 1.8; }\n}\nconst t = new Temperature(0);\nconsole.log(t.f);\nt.f = 68;\nconsole.log(t.c);',
        options: ['32\n20', '0\n68', '32\n68', '20\n32'], answer: '32\n20',
        explanation: 'Getter mengubah 0°C menjadi 32°F. Setter 68°F menyimpan kembali 20°C.',
        tests: [{ name: 'Konversi dua arah', inputs: {}, expected: '32\n20' }],
        hints: ['Gunakan rumus pada getter untuk baris pertama.', 'Gunakan rumus setter untuk nilai kedua.'],
        solution: 'class Temperature {\n  constructor(c) { this.c = c; }\n  get f() { return this.c * 1.8 + 32; }\n  set f(value) { this.c = (value - 32) / 1.8; }\n}\nconst t = new Temperature(0);\nconsole.log(t.f);\nt.f = 68;\nconsole.log(t.c);',
      },
      {
        id: 'oop-accessors-complete', stage: 'Lengkapi', mode: 'script', title: 'Durasi sebagai properti',
        instruction: 'Tambahkan getter durationMinutes yang menghitung selisih end dan start dalam menit.',
        starter: 'class Session {\n  constructor(start, end) {\n    this.start = start;\n    this.end = end;\n  }\n  // Tambahkan getter\n}\nconst session = new Session(30, 150);', probe: 'session.durationMinutes',
        tests: [{ name: 'Selisih waktu', inputs: {}, expected: 120 }],
        hints: ['Tulis get durationMinutes().', 'Kembalikan this.end - this.start.'],
        solution: 'class Session {\n  constructor(start, end) {\n    this.start = start;\n    this.end = end;\n  }\n  get durationMinutes() { return this.end - this.start; }\n}\nconst session = new Session(30, 150);',
      },
      {
        id: 'oop-accessors-build', stage: 'Bangun', mode: 'function', title: 'Jarak dengan factory',
        instruction: 'Buat class Distance yang menyimpan meters, memiliki getter/setter kilometers, dan static fromKilometers(value).',
        starter: '// Buat class Distance\n', probe: '(km, replacement) => { const d = Distance.fromKilometers(km); const before = [d.meters, d.kilometers]; d.kilometers = replacement; return [...before, d.meters]; }',
        tests: [
          { name: 'Konversi kilometer', inputs: {}, args: [2, 1.5], expected: [2000, 2, 1500] },
          { name: 'Pecahan kecil', inputs: {}, args: [0.5, 3], expected: [500, 0.5, 3000] },
        ],
        hints: ['Satu kilometer adalah 1000 meter.', 'Factory mengembalikan new Distance(value * 1000).'],
        solution: 'class Distance {\n  constructor(meters) { this.meters = meters; }\n  get kilometers() { return this.meters / 1000; }\n  set kilometers(value) { this.meters = value * 1000; }\n  static fromKilometers(value) { return new Distance(value * 1000); }\n}',
      },
    ],
  },
  {
    id: 'symbols-iterators',
    title: 'Symbol dan protokol iterator',
    description: 'Symbol menyediakan key unik, dan Symbol.iterator membuat objek dapat digunakan oleh for...of serta spread.',
    highlights: ['Symbol', 'Symbol.iterator', 'next', 'value', 'done', 'for...of'],
    core: 'Iterable memiliki method bernama Symbol.iterator yang mengembalikan iterator. Setiap next() menghasilkan objek {value, done}; done menjadi true ketika tidak ada nilai lagi. Key Symbol.iterator tidak bertabrakan dengan properti teks biasa.',
    model: ['iterable[Symbol.iterator]()', 'iterator.next()', '{ value, done }'],
    why: 'Dengan mengikuti protokol standar, struktur data buatan sendiri langsung cocok dengan for...of, spread, dan API lain yang menerima iterable.',
    example: 'const two = {\n  *[Symbol.iterator]() { yield 1; yield 2; }\n};\nconsole.log([...two]);',
    mistake: 'Iterator harus maju pada setiap next() dan akhirnya melaporkan done: true. Jika posisi tidak berubah, loop dapat berjalan tanpa akhir.',
    exercises: [
      {
        id: 'oop-iterator-predict', stage: 'Prediksi', mode: 'console', title: 'Baca langkah iterator',
        instruction: 'Pilih keluaran done dari tiga langkah iterator dua elemen.',
        starter: 'const iterator = ["A", "B"][Symbol.iterator]();\nconsole.log(iterator.next().done);\nconsole.log(iterator.next().done);\nconsole.log(iterator.next().done);',
        options: ['false\nfalse\ntrue', 'false\ntrue\ntrue', 'true\nfalse\nfalse', 'A\nB\ntrue'], answer: 'false\nfalse\ntrue',
        explanation: 'Dua langkah pertama menghasilkan nilai. Langkah ketiga menandai bahwa iterasi selesai.',
        tests: [{ name: 'Tiga langkah', inputs: {}, expected: 'false\nfalse\ntrue' }],
        hints: ['Ada tepat dua elemen.', 'done baru true setelah keduanya diambil.'],
        solution: 'const iterator = ["A", "B"][Symbol.iterator]();\nconsole.log(iterator.next().done);\nconsole.log(iterator.next().done);\nconsole.log(iterator.next().done);',
      },
      {
        id: 'oop-iterator-complete', stage: 'Lengkapi', mode: 'script', title: 'Rentang yang iterable',
        instruction: 'Lengkapi next() agar Range menghasilkan bilangan start sampai end secara inklusif.',
        starter: 'class Range {\n  constructor(start, end) { this.start = start; this.end = end; }\n  [Symbol.iterator]() {\n    let current = this.start;\n    const end = this.end;\n    return {\n      next() {\n        // Kembalikan langkah dan majukan current\n      }\n    };\n  }\n}', probe: '[...new Range(2, 5)]',
        tests: [{ name: 'Rentang inklusif', inputs: {}, expected: [2, 3, 4, 5] }],
        hints: ['Jika current > end, kembalikan {done: true}.', 'Simpan value sebelum menaikkan current.'],
        solution: 'class Range {\n  constructor(start, end) { this.start = start; this.end = end; }\n  [Symbol.iterator]() {\n    let current = this.start;\n    const end = this.end;\n    return {\n      next() {\n        if (current > end) return { done: true };\n        return { value: current++, done: false };\n      }\n    };\n  }\n}',
      },
      {
        id: 'oop-iterator-build', stage: 'Bangun', mode: 'script', title: 'Playlist buatan sendiri',
        instruction: 'Buat class Playlist yang menerima titles dan iterable secara manual. Jangan kembalikan iterator array secara langsung.',
        starter: '// Buat class Playlist\n', probe: '[...new Playlist(["Pagi", "Siang", "Malam"])]',
        tests: [{ name: 'Urutan judul', inputs: {}, expected: ['Pagi', 'Siang', 'Malam'] }],
        hints: ['[Symbol.iterator]() dapat menyimpan index lokal.', 'next() membaca this.titles melalui variabel lokal playlist.'],
        solution: 'class Playlist {\n  constructor(titles) { this.titles = titles; }\n  [Symbol.iterator]() {\n    let index = 0;\n    const titles = this.titles;\n    return {\n      next() {\n        if (index >= titles.length) return { done: true };\n        return { value: titles[index++], done: false };\n      }\n    };\n  }\n}',
      },
    ],
  },
  {
    id: 'inheritance-instanceof',
    title: 'Pewarisan secukupnya dan instanceof',
    description: 'Subclass dapat mengkhususkan perilaku superclass, tetapi hubungan itu perlu dipakai dengan sengaja agar desain tidak terlalu terikat.',
    highlights: ['extends', 'super', 'override', 'instanceof', 'komposisi'],
    core: 'extends menghubungkan prototype subclass ke superclass. Constructor turunan memanggil super sebelum memakai this. Method dapat dioverride, dan super.method() mengakses implementasi induk. instanceof mengikuti rantai prototype.',
    model: ['Superclass', 'extends', 'Subclass instance'],
    why: 'Pewarisan berguna ketika subtype sungguh dapat dipakai sebagai tipe induknya. Jika hanya ingin memakai sebuah kemampuan, menyimpan helper sebagai properti sering lebih longgar.',
    example: 'class Message { text() { return "pesan"; } }\nclass UrgentMessage extends Message {\n  text() { return super.text().toUpperCase() + "!"; }\n}',
    mistake: 'Lupa memanggil super() pada constructor turunan membuat this belum tersedia. Hindari hierarki panjang yang memaksa subclass mengetahui terlalu banyak detail induk.',
    exercises: [
      {
        id: 'oop-inheritance-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti rantai tipe',
        instruction: 'Pilih hasil tiga pemeriksaan instanceof.',
        starter: 'class Item {}\nclass Book extends Item {}\nconst book = new Book();\nconsole.log(book instanceof Book);\nconsole.log(book instanceof Item);\nconsole.log(new Item() instanceof Book);',
        options: ['true\ntrue\nfalse', 'true\nfalse\nfalse', 'true\ntrue\ntrue', 'false\ntrue\nfalse'], answer: 'true\ntrue\nfalse',
        explanation: 'Instance Book juga berada dalam rantai Item, tetapi instance Item bukan Book.',
        tests: [{ name: 'Rantai instanceof', inputs: {}, expected: 'true\ntrue\nfalse' }],
        hints: ['Subclass mewarisi superclass.', 'Arah hubungan tidak berlaku sebaliknya.'],
        solution: 'class Item {}\nclass Book extends Item {}\nconst book = new Book();\nconsole.log(book instanceof Book);\nconsole.log(book instanceof Item);\nconsole.log(new Item() instanceof Book);',
      },
      {
        id: 'oop-inheritance-complete', stage: 'Lengkapi', mode: 'script', title: 'Pesanan ekspres',
        instruction: 'Lengkapi ExpressOrder: panggil constructor induk dan override shippingCost() menjadi dua kali biaya dasar.',
        starter: 'class Order {\n  constructor(total) { this.total = total; }\n  shippingCost() { return this.total >= 100 ? 0 : 10; }\n}\nclass ExpressOrder extends Order {\n  constructor(total) {\n    // Panggil induk\n  }\n  shippingCost() {\n    // Gunakan hasil method induk\n  }\n}', probe: '[new ExpressOrder(50).shippingCost(), new ExpressOrder(120).shippingCost()]',
        tests: [{ name: 'Biaya ekspres', inputs: {}, expected: [20, 0] }],
        hints: ['Constructor cukup memanggil super(total).', 'Kembalikan super.shippingCost() * 2.'],
        solution: 'class Order {\n  constructor(total) { this.total = total; }\n  shippingCost() { return this.total >= 100 ? 0 : 10; }\n}\nclass ExpressOrder extends Order {\n  constructor(total) { super(total); }\n  shippingCost() { return super.shippingCost() * 2; }\n}',
      },
      {
        id: 'oop-inheritance-build', stage: 'Bangun', mode: 'function', title: 'Tugas dengan batas waktu',
        instruction: 'Buat class Task dengan label dan method describe(). Buat TimedTask extends Task yang menerima label serta minutes dan mengembalikan "LABEL (MINUTES menit)" dari override describe().',
        starter: '// Buat Task dan TimedTask\n', probe: '(label, minutes) => { const task = new TimedTask(label, minutes); return [task.describe(), task instanceof TimedTask, task instanceof Task]; }',
        tests: [
          { name: 'Deskripsi turunan', inputs: {}, args: ['Latihan', 25], expected: ['Latihan (25 menit)', true, true] },
          { name: 'Nilai lain', inputs: {}, args: ['Baca', 10], expected: ['Baca (10 menit)', true, true] },
        ],
        hints: ['TimedTask constructor memanggil super(label).', 'Override dapat memakai super.describe().'],
        solution: 'class Task {\n  constructor(label) { this.label = label; }\n  describe() { return this.label; }\n}\nclass TimedTask extends Task {\n  constructor(label, minutes) {\n    super(label);\n    this.minutes = minutes;\n  }\n  describe() { return super.describe() + " (" + this.minutes + " menit)"; }\n}',
      },
    ],
  },
];
