import type { Part } from './chapter-one';

export const chapter = {
  id: 'functions',
  title: 'Fungsi',
  number: '03',
};

export const parts: Part[] = [
  {
    id: 'why-functions',
    title: 'Mengapa fungsi dibutuhkan?',
    description: 'Fungsi mengemas serangkaian langkah menjadi satu perilaku bernama yang dapat digunakan berkali-kali.',
    highlights: ['function', 'return', 'parameter', 'argumen', '()'],
    core: 'Deklarasi function greet(name) { ... } membuat fungsi bernama greet dengan parameter name. Fungsi belum berjalan saat dibuat. Ia berjalan ketika dipanggil dengan (), misalnya greet("Ayu"). Nilai "Ayu" yang dikirim saat pemanggilan disebut argumen.',
    model: ['argumen', 'fungsi memproses', 'hasil'],
    why: 'Fungsi mengurangi pengulangan dan memberi nama pada tujuan kode. Daripada menulis rumus yang sama di banyak tempat, kamu cukup memanggil satu fungsi yang sudah teruji.',
    example: 'function double(number) {\n  return number * 2;\n}\nconst result = double(6);\nconsole.log(result);',
    mistake: 'Menyebut nama fungsi tanpa () hanya merujuk pada fungsi tersebut; itu belum menjalankannya. double adalah fungsi, sedangkan double(6) adalah pemanggilan yang menghasilkan 12.',
    exercises: [
      {
        id: 'functions-purpose-predict', stage: 'Prediksi', mode: 'console', title: 'Panggil perilaku yang sama',
        instruction: 'Tentukan dua nilai yang ditampilkan setelah fungsi dipanggil dua kali.',
        starter: 'function double(number) {\n  return number * 2;\n}\nconsole.log(double(3));\nconsole.log(double(5));',
        options: ['6\n10', '3\n5', '8', 'undefined'], answer: '6\n10',
        explanation: 'Setiap pemanggilan memakai argumen yang berbeda. double(3) menghasilkan 6 dan double(5) menghasilkan 10.',
        tests: [{ name: 'Dua pemanggilan', inputs: {}, expected: '6\n10' }],
        hints: ['Masukkan setiap argumen ke posisi parameter number.', 'Kalikan 3 dan 5 masing-masing dengan 2.'],
        solution: 'function double(number) {\n  return number * 2;\n}\nconsole.log(double(3));\nconsole.log(double(5));',
      },
      {
        id: 'functions-purpose-complete', stage: 'Lengkapi', mode: 'function', title: 'Lengkapi fungsi kuadrat',
        instruction: 'Lengkapi square agar mengembalikan hasil perkalian number dengan dirinya sendiri.',
        starter: 'function square(number) {\n  // Kembalikan hasilnya\n}\n', probe: 'square',
        tests: [
          { name: 'Kuadrat empat', inputs: {}, args: [4], expected: 16 },
          { name: 'Kuadrat negatif', inputs: {}, args: [-3], expected: 9 },
        ],
        hints: ['Gunakan kata kunci return.', 'Ekspresinya adalah number * number.'],
        solution: 'function square(number) {\n  return number * number;\n}',
      },
      {
        id: 'functions-purpose-build', stage: 'Bangun', mode: 'function', title: 'Buat fungsi harga akhir',
        instruction: 'Buat fungsi finalPrice(price, discount) yang mengembalikan price dikurangi nilai discount. discount diberikan sebagai angka desimal, misalnya 0.2 berarti 20%.',
        starter: '// Buat fungsi finalPrice\n', probe: 'finalPrice',
        tests: [
          { name: 'Diskon dua puluh persen', inputs: {}, args: [100000, 0.2], expected: 80000 },
          { name: 'Tanpa diskon', inputs: {}, args: [75000, 0], expected: 75000 },
        ],
        hints: ['Nilai potongan adalah price * discount.', 'Kembalikan price - price * discount.'],
        solution: 'function finalPrice(price, discount) {\n  return price - price * discount;\n}',
      },
    ],
  },
  {
    id: 'parameters-return',
    title: 'Parameter dan return',
    description: 'Parameter menerima data dari luar fungsi, sedangkan return mengirimkan satu hasil kembali ke pemanggil.',
    highlights: ['parameter', 'argumen', 'return', 'undefined', ','],
    core: 'Pada function add(a, b), a dan b adalah parameter. Pada add(2, 3), 2 dan 3 adalah argumen. Parameter dipisahkan dengan ,. Saat return dijalankan, fungsi langsung berhenti dan menghasilkan nilai. Tanpa return, hasil pemanggilan adalah undefined.',
    model: ['add(2, 3)', 'a = 2 · b = 3', 'return 5'],
    why: 'Pemisahan input dan output membuat fungsi mudah diuji. Kamu bisa memberi beragam argumen dan memeriksa apakah return selalu mengikuti aturan yang sama.',
    example: 'function area(width, height) {\n  return width * height;\n}\nconsole.log(area(4, 3));',
    mistake: 'console.log menampilkan nilai, tetapi tidak otomatis mengembalikannya. Jika hasil fungsi perlu dipakai dalam perhitungan lain, gunakan return.',
    exercises: [
      {
        id: 'functions-return-predict', stage: 'Prediksi', mode: 'console', title: 'Kode setelah return',
        instruction: 'Pilih keluaran kode. Perhatikan kapan fungsi berhenti.',
        starter: 'function label(score) {\n  if (score >= 75) return "Lulus";\n  return "Coba lagi";\n}\nconsole.log(label(80));',
        options: ['Lulus', 'Coba lagi', 'true', 'undefined'], answer: 'Lulus',
        explanation: 'Kondisinya true, sehingga return "Lulus" langsung menghentikan fungsi. Baris return berikutnya tidak dijalankan.',
        tests: [{ name: 'Return pertama', inputs: {}, expected: 'Lulus' }],
        hints: ['Bandingkan 80 dengan 75.', 'return yang pertama dijalankan langsung mengakhiri fungsi.'],
        solution: 'function label(score) {\n  if (score >= 75) return "Lulus";\n  return "Coba lagi";\n}\nconsole.log(label(80));',
      },
      {
        id: 'functions-return-complete', stage: 'Lengkapi', mode: 'function', title: 'Hitung luas',
        instruction: 'Lengkapi rectangleArea agar mengembalikan width * height.',
        starter: 'function rectangleArea(width, height) {\n  return 0;\n}', probe: 'rectangleArea',
        tests: [
          { name: 'Persegi panjang', inputs: {}, args: [6, 4], expected: 24 },
          { name: 'Sisi desimal', inputs: {}, args: [2.5, 4], expected: 10 },
        ],
        hints: ['Kedua parameter sudah tersedia di dalam fungsi.', 'Ganti 0 dengan width * height.'],
        solution: 'function rectangleArea(width, height) {\n  return width * height;\n}',
      },
      {
        id: 'functions-return-build', stage: 'Bangun', mode: 'function', title: 'Tentukan sapaan',
        instruction: 'Buat greet(name, isMorning). Kembalikan "Selamat pagi, NAME" jika isMorning true, dan "Halo, NAME" jika false.',
        starter: '// Buat fungsi greet\n', probe: 'greet',
        tests: [
          { name: 'Sapaan pagi', inputs: {}, args: ['Rani', true], expected: 'Selamat pagi, Rani' },
          { name: 'Sapaan biasa', inputs: {}, args: ['Dimas', false], expected: 'Halo, Dimas' },
        ],
        hints: ['Gunakan if (isMorning) untuk memilih hasil pertama.', 'Gabungkan teks dengan name menggunakan +.'],
        solution: 'function greet(name, isMorning) {\n  if (isMorning) return "Selamat pagi, " + name;\n  return "Halo, " + name;\n}',
      },
    ],
  },
  {
    id: 'scope',
    title: 'Scope: batas sebuah nama',
    description: 'Scope menentukan bagian program yang dapat mengenali suatu variabel.',
    highlights: ['scope', 'lokal', 'global', '{', '}', 'const', 'let'],
    core: 'Variabel yang dibuat di dalam fungsi bersifat lokal: hanya dapat dipakai di fungsi itu. Variabel di luar fungsi memiliki scope lebih luas. Blok { dan } juga membatasi const dan let. Beberapa scope dapat memiliki nama yang sama tanpa menjadi variabel yang sama.',
    model: ['scope luar', 'fungsi → scope lokal', 'nama dicari dari dalam ke luar'],
    why: 'Scope mencegah satu bagian program tanpa sengaja mengubah data milik bagian lain. Fungsi yang memakai parameter dan variabel lokal biasanya lebih aman dan mudah dipahami.',
    example: 'const taxRate = 0.11;\nfunction totalWithTax(price) {\n  const tax = price * taxRate;\n  return price + tax;\n}\nconsole.log(totalWithTax(10000));',
    mistake: 'Variabel lokal tidak dapat dipakai setelah fungsi selesai. Jika sebuah nilai dibutuhkan di luar fungsi, kirimkan melalui return, bukan dengan mencoba membaca variabel lokalnya.',
    exercises: [
      {
        id: 'functions-scope-predict', stage: 'Prediksi', mode: 'console', title: 'Nama terdekat',
        instruction: 'Tentukan nilai yang digunakan di dalam fungsi.',
        starter: 'const message = "luar";\nfunction show() {\n  const message = "dalam";\n  console.log(message);\n}\nshow();',
        options: ['luar', 'dalam', 'undefined', 'error'], answer: 'dalam',
        explanation: 'Di dalam show terdapat variabel lokal message. Nama terdekat itulah yang digunakan.',
        tests: [{ name: 'Scope lokal', inputs: {}, expected: 'dalam' }],
        hints: ['Cari deklarasi message yang berada di dalam fungsi.', 'Nama lokal menutupi nama yang sama dari scope luar.'],
        solution: 'const message = "luar";\nfunction show() {\n  const message = "dalam";\n  console.log(message);\n}\nshow();',
      },
      {
        id: 'functions-scope-complete', stage: 'Lengkapi', mode: 'function', title: 'Gunakan variabel lokal',
        instruction: 'Di dalam calculateTotal, buat const tax dari price * 0.11 lalu kembalikan price + tax.',
        starter: 'function calculateTotal(price) {\n  // Buat tax hanya di dalam fungsi\n}\n', probe: 'calculateTotal',
        tests: [
          { name: 'Harga sepuluh ribu', inputs: {}, args: [10000], expected: 11100 },
          { name: 'Harga lima puluh ribu', inputs: {}, args: [50000], expected: 55500 },
        ],
        hints: ['Deklarasikan tax di antara { dan } milik fungsi.', 'Setelah membuat tax, return price + tax.'],
        solution: 'function calculateTotal(price) {\n  const tax = price * 0.11;\n  return price + tax;\n}',
      },
      {
        id: 'functions-scope-build', stage: 'Bangun', mode: 'function', title: 'Hindari ketergantungan global',
        instruction: 'Buat convertToRupiah(amount, rate). Hitung hasil hanya dari dua parameter dan kembalikan amount * rate.',
        starter: '// Buat fungsi yang mandiri\n', probe: 'convertToRupiah',
        tests: [
          { name: 'Konversi pertama', inputs: {}, args: [10, 16000], expected: 160000 },
          { name: 'Konversi kedua', inputs: {}, args: [25, 15500], expected: 387500 },
        ],
        hints: ['Semua data yang dibutuhkan sudah datang melalui parameter.', 'return amount * rate;.'],
        solution: 'function convertToRupiah(amount, rate) {\n  return amount * rate;\n}',
      },
    ],
  },
  {
    id: 'function-forms',
    title: 'Bentuk-bentuk fungsi',
    description: 'JavaScript menyediakan deklarasi fungsi, ekspresi fungsi, dan arrow function untuk membuat perilaku.',
    highlights: ['function', '=>', 'const', 'arrow function', 'ekspresi'],
    core: 'Deklarasi memakai function name() {}. Ekspresi fungsi menyimpan fungsi ke variabel: const name = function () {}. Arrow function memakai =>: const double = number => number * 2. Arrow singkat otomatis mengembalikan ekspresi setelah =>.',
    model: ['input', 'number => number * 2', 'output'],
    why: 'Ketiga bentuk dapat menerima parameter dan menghasilkan nilai. Untuk pemula, pilih bentuk yang paling mudah dibaca oleh tim; arrow singkat cocok untuk perilaku kecil.',
    example: 'function add(a, b) { return a + b; }\nconst subtract = function (a, b) { return a - b; };\nconst multiply = (a, b) => a * b;\nconsole.log(add(2, 3), subtract(5, 2), multiply(3, 4));',
    mistake: 'Arrow function dengan { } tidak otomatis mengembalikan nilai. Jika kamu menulis const f = x => { x * 2; }, hasilnya undefined. Tambahkan return di dalam blok.',
    exercises: [
      {
        id: 'functions-forms-predict', stage: 'Prediksi', mode: 'console', title: 'Arrow function singkat',
        instruction: 'Pilih hasil dari pemanggilan fungsi.',
        starter: 'const triple = number => number * 3;\nconsole.log(triple(4));',
        options: ['3', '4', '7', '12'], answer: '12',
        explanation: 'Arrow function menerima 4 sebagai number dan otomatis mengembalikan 4 * 3, yaitu 12.',
        tests: [{ name: 'Return implisit', inputs: {}, expected: '12' }],
        hints: ['Ekspresi setelah => menjadi hasil fungsi.', 'Ganti number dengan argumen 4.'],
        solution: 'const triple = number => number * 3;\nconsole.log(triple(4));',
      },
      {
        id: 'functions-forms-complete', stage: 'Lengkapi', mode: 'function', title: 'Lengkapi arrow function',
        instruction: 'Ganti 0 agar add mengembalikan jumlah a dan b dengan bentuk arrow singkat.',
        starter: 'const add = (a, b) => 0;', probe: 'add',
        tests: [
          { name: 'Dua angka positif', inputs: {}, args: [4, 7], expected: 11 },
          { name: 'Angka negatif', inputs: {}, args: [-3, 8], expected: 5 },
        ],
        hints: ['Tidak perlu menulis return pada bentuk singkat ini.', 'Ekspresi setelah => adalah a + b.'],
        solution: 'const add = (a, b) => a + b;',
      },
      {
        id: 'functions-forms-build', stage: 'Bangun', mode: 'function', title: 'Arrow dengan keputusan',
        instruction: 'Buat const isAdult sebagai arrow function yang menerima age dan mengembalikan true jika age >= 18.',
        starter: '// Buat arrow function isAdult\n', probe: 'isAdult',
        tests: [
          { name: 'Sudah dewasa', inputs: {}, args: [21], expected: true },
          { name: 'Tepat delapan belas', inputs: {}, args: [18], expected: true },
          { name: 'Belum dewasa', inputs: {}, args: [16], expected: false },
        ],
        hints: ['Perbandingan age >= 18 sudah menghasilkan boolean.', 'Gunakan const isAdult = age => age >= 18;.'],
        solution: 'const isAdult = age => age >= 18;',
      },
    ],
  },
  {
    id: 'call-stack',
    title: 'Urutan pemanggilan dan call stack',
    description: 'Saat satu fungsi memanggil fungsi lain, JavaScript mengingat fungsi mana yang harus dilanjutkan setelah pemanggilan selesai.',
    highlights: ['call stack', 'return', 'pemanggilan', 'fungsi'],
    core: 'Call stack dapat dibayangkan sebagai tumpukan pekerjaan. Pemanggilan terbaru berada di atas dan harus selesai lebih dahulu. Setelah fungsi itu return, JavaScript kembali ke pemanggil di bawahnya.',
    model: ['main()', '→ outer()', '→ inner() selesai → kembali'],
    why: 'Memahami urutan ini membantu menelusuri hasil kode dan membaca pesan error yang menunjukkan rangkaian pemanggilan fungsi.',
    example: 'function addOne(value) { return value + 1; }\nfunction doubleAfterAdd(value) {\n  return addOne(value) * 2;\n}\nconsole.log(doubleAfterAdd(4));',
    mistake: 'Fungsi yang dipanggil di bagian dalam harus menghasilkan nilai sebelum perhitungan di fungsi luar dapat dilanjutkan. Jangan menebak hasil fungsi luar sebelum menyelesaikan pemanggilan terdalam.',
    exercises: [
      {
        id: 'functions-stack-predict', stage: 'Prediksi', mode: 'console', title: 'Ikuti urutan fungsi',
        instruction: 'Hitung fungsi paling dalam terlebih dahulu, lalu pilih hasil akhirnya.',
        starter: 'function plusTwo(n) { return n + 2; }\nfunction timesThree(n) { return n * 3; }\nconsole.log(timesThree(plusTwo(4)));',
        options: ['12', '14', '18', '20'], answer: '18',
        explanation: 'plusTwo(4) selesai lebih dahulu dan menghasilkan 6. Nilai 6 menjadi argumen timesThree, sehingga hasilnya 18.',
        tests: [{ name: 'Pemanggilan bersarang', inputs: {}, expected: '18' }],
        hints: ['Mulai dari plusTwo(4).', 'Masukkan hasil fungsi dalam ke timesThree.'],
        solution: 'function plusTwo(n) { return n + 2; }\nfunction timesThree(n) { return n * 3; }\nconsole.log(timesThree(plusTwo(4)));',
      },
      {
        id: 'functions-stack-complete', stage: 'Lengkapi', mode: 'function', title: 'Rangkai dua fungsi',
        instruction: 'Lengkapi finalValue agar memanggil addFee(amount), lalu mengirim hasilnya ke applyDiscount(...).',
        starter: 'function addFee(amount) { return amount + 5000; }\nfunction applyDiscount(amount) { return amount * 0.9; }\nfunction finalValue(amount) {\n  return 0;\n}', probe: 'finalValue',
        tests: [
          { name: 'Nilai pertama', inputs: {}, args: [95000], expected: 90000 },
          { name: 'Nilai kedua', inputs: {}, args: [45000], expected: 45000 },
        ],
        hints: ['Pemanggilan terdalam adalah addFee(amount).', 'Kembalikan applyDiscount(addFee(amount)).'],
        solution: 'function addFee(amount) { return amount + 5000; }\nfunction applyDiscount(amount) { return amount * 0.9; }\nfunction finalValue(amount) {\n  return applyDiscount(addFee(amount));\n}',
      },
      {
        id: 'functions-stack-build', stage: 'Bangun', mode: 'function', title: 'Buat alur transformasi',
        instruction: 'Buat trimText(text) yang menghapus spasi tepi, makeUpper(text) yang membuat huruf besar, dan normalize(text) yang mengembalikan makeUpper(trimText(text)).',
        starter: '// Buat tiga fungsi\n', probe: 'normalize',
        tests: [
          { name: 'Teks dengan spasi', inputs: {}, args: ['  belajar js  '], expected: 'BELAJAR JS' },
          { name: 'Teks ringkas', inputs: {}, args: ['fungsi'], expected: 'FUNGSI' },
        ],
        hints: ['Gunakan text.trim() dan text.toUpperCase().', 'Di normalize, panggil trimText lebih dahulu.'],
        solution: 'function trimText(text) { return text.trim(); }\nfunction makeUpper(text) { return text.toUpperCase(); }\nfunction normalize(text) {\n  return makeUpper(trimText(text));\n}',
      },
    ],
  },
  {
    id: 'optional-default-parameters',
    title: 'Parameter opsional dan nilai default',
    description: 'Parameter yang tidak diberi argumen bernilai undefined, tetapi kita dapat menyediakan nilai default yang lebih berguna.',
    highlights: ['undefined', '=', 'default', 'parameter', 'argumen'],
    core: 'Pada function greet(name = "Teman"), nilai "Teman" digunakan jika argumen name tidak dikirim atau bernilai undefined. Parameter default ditulis dengan = di daftar parameter.',
    model: ['greet()', 'name tidak tersedia', 'default → "Teman"'],
    why: 'Nilai default membuat fungsi nyaman dipakai sekaligus menjelaskan perilaku saat data opsional tidak diberikan.',
    example: 'function greet(name = "Teman") {\n  return "Halo, " + name;\n}\nconsole.log(greet());\nconsole.log(greet("Sari"));',
    mistake: 'Nilai default tidak dipakai untuk null, 0, false, atau string kosong. Ia hanya aktif ketika argumen tidak ada atau bernilai undefined.',
    exercises: [
      {
        id: 'functions-default-predict', stage: 'Prediksi', mode: 'console', title: 'Argumen yang tidak dikirim',
        instruction: 'Pilih dua baris keluaran sesuai urutan pemanggilan.',
        starter: 'function power(base, exponent = 2) {\n  return base ** exponent;\n}\nconsole.log(power(3));\nconsole.log(power(3, 3));',
        options: ['6\n9', '9\n27', '9\n9', 'undefined\n27'], answer: '9\n27',
        explanation: 'Pemanggilan pertama memakai default exponent 2 sehingga 3² = 9. Pemanggilan kedua mengirim exponent 3 sehingga hasilnya 27.',
        tests: [{ name: 'Default dan argumen', inputs: {}, expected: '9\n27' }],
        hints: ['Pada power(3), exponent memakai nilai setelah =.', 'Pada power(3, 3), argumen kedua menggantikan default.'],
        solution: 'function power(base, exponent = 2) {\n  return base ** exponent;\n}\nconsole.log(power(3));\nconsole.log(power(3, 3));',
      },
      {
        id: 'functions-default-complete', stage: 'Lengkapi', mode: 'function', title: 'Satuan bawaan',
        instruction: 'Tambahkan nilai default "px" untuk parameter unit. Fungsi harus mengembalikan value diikuti unit.',
        starter: 'function formatSize(value, unit) {\n  return value + unit;\n}', probe: 'formatSize',
        tests: [
          { name: 'Memakai default', inputs: {}, args: [16], expected: '16px' },
          { name: 'Memakai argumen', inputs: {}, args: [2, 'rem'], expected: '2rem' },
        ],
        hints: ['Ubah daftar parameter menjadi value, unit = "px".', 'Bagian return tidak perlu diubah.'],
        solution: 'function formatSize(value, unit = "px") {\n  return value + unit;\n}',
      },
      {
        id: 'functions-default-build', stage: 'Bangun', mode: 'function', title: 'Pesan dengan tanda baca default',
        instruction: 'Buat announce(message, ending = "!") yang mengembalikan message diikuti ending.',
        starter: '// Buat fungsi announce\n', probe: 'announce',
        tests: [
          { name: 'Tanda bawaan', inputs: {}, args: ['Mulai'], expected: 'Mulai!' },
          { name: 'Tanda khusus', inputs: {}, args: ['Siap', '?'], expected: 'Siap?' },
        ],
        hints: ['Tulis default langsung setelah nama parameter ending.', 'Kembalikan message + ending.'],
        solution: 'function announce(message, ending = "!") {\n  return message + ending;\n}',
      },
    ],
  },
  {
    id: 'closures',
    title: 'Closure: fungsi yang mengingat',
    description: 'Closure terjadi ketika sebuah fungsi tetap dapat memakai variabel dari scope tempat fungsi itu dibuat.',
    highlights: ['closure', 'scope', 'return', 'fungsi', 'let'],
    core: 'Fungsi dapat mengembalikan fungsi lain. Fungsi di dalamnya tetap mengingat variabel dari pemanggilan luar, bahkan setelah fungsi luar selesai. Ingatan antara fungsi dan scope pembuatnya disebut closure.',
    model: ['buat scope', 'kembalikan fungsi', 'fungsi tetap mengingat data'],
    why: 'Closure memungkinkan kita membuat perilaku dengan keadaan pribadi, misalnya penghitung yang hanya dapat diubah melalui fungsi tertentu.',
    example: 'function makeMultiplier(factor) {\n  return number => number * factor;\n}\nconst double = makeMultiplier(2);\nconsole.log(double(5));',
    mistake: 'Setiap pemanggilan fungsi pembuat menghasilkan closure baru dengan ingatan tersendiri. Dua counter yang dibuat terpisah tidak berbagi nilai count.',
    exercises: [
      {
        id: 'functions-closure-predict', stage: 'Prediksi', mode: 'console', title: 'Nilai yang diingat',
        instruction: 'Tentukan nilai factor yang tetap diingat oleh fungsi double.',
        starter: 'function makeMultiplier(factor) {\n  return number => number * factor;\n}\nconst double = makeMultiplier(2);\nconsole.log(double(6));',
        options: ['2', '6', '8', '12'], answer: '12',
        explanation: 'double mengingat factor bernilai 2. Ketika dipanggil dengan 6, fungsi menghasilkan 6 * 2 = 12.',
        tests: [{ name: 'Closure faktor', inputs: {}, expected: '12' }],
        hints: ['makeMultiplier(2) menyimpan factor 2.', 'Kalikan argumen double dengan factor yang diingat.'],
        solution: 'function makeMultiplier(factor) {\n  return number => number * factor;\n}\nconst double = makeMultiplier(2);\nconsole.log(double(6));',
      },
      {
        id: 'functions-closure-complete', stage: 'Lengkapi', mode: 'script', title: 'Penghitung pribadi',
        instruction: 'Lengkapi createCounter agar fungsi yang dikembalikan menambah count lalu mengembalikan nilai terbarunya.',
        starter: 'function createCounter() {\n  let count = 0;\n  return function () {\n    // Tambah dan kembalikan count\n  };\n}', probe: '(() => { const counter = createCounter(); return [counter(), counter(), counter()]; })()',
        tests: [{ name: 'Tiga pemanggilan', inputs: {}, expected: [1, 2, 3] }],
        hints: ['count tetap tersedia karena dipakai fungsi di dalam.', 'Gunakan count++; lalu return count;.'],
        solution: 'function createCounter() {\n  let count = 0;\n  return function () {\n    count++;\n    return count;\n  };\n}',
      },
      {
        id: 'functions-closure-build', stage: 'Bangun', mode: 'script', title: 'Buat penambah khusus',
        instruction: 'Buat makeAdder(amount) yang mengembalikan fungsi. Fungsi di dalam menerima value dan mengembalikan value + amount.',
        starter: '// Buat fungsi makeAdder\n', probe: '(() => { const addTen = makeAdder(10); return [addTen(5), addTen(20)]; })()',
        tests: [{ name: 'Mengingat sepuluh', inputs: {}, expected: [15, 30] }],
        hints: ['Di dalam makeAdder, return sebuah function atau arrow function.', 'Fungsi yang dikembalikan dapat memakai parameter amount dari scope luar.'],
        solution: 'function makeAdder(amount) {\n  return function (value) {\n    return value + amount;\n  };\n}',
      },
    ],
  },
  {
    id: 'recursion',
    title: 'Rekursi',
    description: 'Fungsi rekursif menyelesaikan masalah dengan memanggil dirinya sendiri untuk versi masalah yang lebih kecil.',
    highlights: ['rekursi', 'base case', 'return', 'call stack', '-'],
    core: 'Rekursi membutuhkan base case, yaitu kondisi yang langsung menghasilkan jawaban dan menghentikan pemanggilan. Kasus lainnya harus bergerak mendekati base case, misalnya memanggil countdown(n - 1).',
    model: ['masalah n', 'masalah n - 1', 'base case → susun hasil kembali'],
    why: 'Rekursi cocok ketika data atau masalah memiliki bentuk berulang, tetapi setiap pemanggilan memakai ruang di call stack. Untuk hitungan sederhana, loop sering lebih efisien.',
    example: 'function factorial(n) {\n  if (n === 0) return 1;\n  return n * factorial(n - 1);\n}\nconsole.log(factorial(4));',
    mistake: 'Tanpa base case yang dapat dicapai, fungsi akan terus memanggil dirinya sendiri sampai call stack penuh. Pastikan input selalu bergerak menuju kondisi berhenti.',
    exercises: [
      {
        id: 'functions-recursion-predict', stage: 'Prediksi', mode: 'console', title: 'Uraikan pemanggilan',
        instruction: 'Ikuti fungsi sampai base case, lalu susun hasilnya kembali.',
        starter: 'function sumTo(n) {\n  if (n === 1) return 1;\n  return n + sumTo(n - 1);\n}\nconsole.log(sumTo(4));',
        options: ['4', '7', '10', '24'], answer: '10',
        explanation: 'sumTo(4) menjadi 4 + 3 + 2 + 1, sehingga hasilnya 10.',
        tests: [{ name: 'Rekursi penjumlahan', inputs: {}, expected: '10' }],
        hints: ['Terus kurangi n sampai bernilai 1.', 'Jumlahkan 4 + 3 + 2 + 1.'],
        solution: 'function sumTo(n) {\n  if (n === 1) return 1;\n  return n + sumTo(n - 1);\n}\nconsole.log(sumTo(4));',
      },
      {
        id: 'functions-recursion-complete', stage: 'Lengkapi', mode: 'function', title: 'Faktorial',
        instruction: 'Lengkapi factorial. Jika n === 0, kembalikan 1. Selain itu kembalikan n * factorial(n - 1).',
        starter: 'function factorial(n) {\n  // Tambahkan base case dan pemanggilan rekursif\n}\n', probe: 'factorial',
        tests: [
          { name: 'Base case', inputs: {}, args: [0], expected: 1 },
          { name: 'Faktorial empat', inputs: {}, args: [4], expected: 24 },
          { name: 'Faktorial lima', inputs: {}, args: [5], expected: 120 },
        ],
        hints: ['Tulis if (n === 0) return 1; terlebih dahulu.', 'Kasus lain mengalikan n dengan hasil untuk n - 1.'],
        solution: 'function factorial(n) {\n  if (n === 0) return 1;\n  return n * factorial(n - 1);\n}',
      },
      {
        id: 'functions-recursion-build', stage: 'Bangun', mode: 'function', title: 'Jumlah digit',
        instruction: 'Buat sumDigits(number). Jika number < 10, kembalikan number. Selain itu, jumlahkan number % 10 dengan sumDigits(Math.floor(number / 10)).',
        starter: '// Buat fungsi rekursif sumDigits\n', probe: 'sumDigits',
        tests: [
          { name: 'Satu digit', inputs: {}, args: [7], expected: 7 },
          { name: 'Tiga digit', inputs: {}, args: [246], expected: 12 },
          { name: 'Mengandung nol', inputs: {}, args: [105], expected: 6 },
        ],
        hints: ['Base case adalah angka yang hanya memiliki satu digit.', 'Ambil digit terakhir dengan % 10 dan sisanya dengan Math.floor(number / 10).'],
        solution: 'function sumDigits(number) {\n  if (number < 10) return number;\n  return number % 10 + sumDigits(Math.floor(number / 10));\n}',
      },
    ],
  },
  {
    id: 'designing-functions',
    title: 'Merancang fungsi yang jelas',
    description: 'Fungsi yang baik memiliki satu tujuan, nama yang menjelaskan tindakan, input yang jelas, dan hasil yang dapat diprediksi.',
    highlights: ['parameter', 'return', 'boolean', 'guard clause', 'fungsi'],
    core: 'Mulai dari kontrak sederhana: data apa yang masuk, aturan apa yang diproses, dan nilai apa yang keluar. Guard clause adalah pemeriksaan awal yang langsung return untuk kasus khusus atau data tidak valid.',
    model: ['tentukan kontrak', 'tangani kasus khusus', 'return hasil utama'],
    why: 'Fungsi kecil dengan satu tujuan lebih mudah dibaca, diuji, dan dipakai kembali. Nama seperti calculateShipping menjelaskan lebih banyak daripada process.',
    example: 'function calculateShipping(total) {\n  if (total < 0) return 0;\n  if (total >= 200000) return 0;\n  return 20000;\n}\nconsole.log(calculateShipping(150000));',
    mistake: 'Jangan membuat fungsi bergantung pada nilai tersembunyi jika nilai itu bisa menjadi parameter. Input eksplisit membuat perilaku fungsi lebih mudah ditebak dan diuji.',
    exercises: [
      {
        id: 'functions-design-predict', stage: 'Prediksi', mode: 'console', title: 'Guard clause lebih dahulu',
        instruction: 'Pilih hasil untuk input yang ditangani oleh pemeriksaan pertama.',
        starter: 'function safeDivide(a, b) {\n  if (b === 0) return "Tidak dapat dibagi";\n  return a / b;\n}\nconsole.log(safeDivide(10, 0));',
        options: ['0', '10', 'Infinity', 'Tidak dapat dibagi'], answer: 'Tidak dapat dibagi',
        explanation: 'Karena b === 0, guard clause langsung mengembalikan pesan dan pembagian tidak dilakukan.',
        tests: [{ name: 'Kasus khusus', inputs: {}, expected: 'Tidak dapat dibagi' }],
        hints: ['Periksa kondisi if sebelum melihat rumus.', 'return pertama menghentikan fungsi.'],
        solution: 'function safeDivide(a, b) {\n  if (b === 0) return "Tidak dapat dibagi";\n  return a / b;\n}\nconsole.log(safeDivide(10, 0));',
      },
      {
        id: 'functions-design-complete', stage: 'Lengkapi', mode: 'function', title: 'Validasi rentang nilai',
        instruction: 'Lengkapi isValidScore agar mengembalikan true hanya ketika score berada dari 0 sampai 100, termasuk kedua batas.',
        starter: 'function isValidScore(score) {\n  return false;\n}', probe: 'isValidScore',
        tests: [
          { name: 'Nilai valid', inputs: {}, args: [75], expected: true },
          { name: 'Batas bawah', inputs: {}, args: [0], expected: true },
          { name: 'Terlalu tinggi', inputs: {}, args: [101], expected: false },
          { name: 'Negatif', inputs: {}, args: [-1], expected: false },
        ],
        hints: ['Gunakan dua perbandingan yang dihubungkan &&.', 'Kembalikan score >= 0 && score <= 100.'],
        solution: 'function isValidScore(score) {\n  return score >= 0 && score <= 100;\n}',
      },
      {
        id: 'functions-design-build', stage: 'Bangun', mode: 'function', title: 'Rancang biaya pengiriman',
        instruction: 'Buat calculateShipping(total, isMember). Kembalikan 0 jika total < 0. Kembalikan 0 jika total >= 200000 atau isMember true. Selain itu kembalikan 20000.',
        starter: '// Buat fungsi dengan guard clause\n', probe: 'calculateShipping',
        tests: [
          { name: 'Data tidak valid', inputs: {}, args: [-5000, false], expected: 0 },
          { name: 'Gratis karena total', inputs: {}, args: [250000, false], expected: 0 },
          { name: 'Gratis untuk anggota', inputs: {}, args: [100000, true], expected: 0 },
          { name: 'Biaya normal', inputs: {}, args: [100000, false], expected: 20000 },
        ],
        hints: ['Tangani total negatif pada baris return pertama.', 'Gunakan || untuk kondisi total besar atau anggota.'],
        solution: 'function calculateShipping(total, isMember) {\n  if (total < 0) return 0;\n  if (total >= 200000 || isMember) return 0;\n  return 20000;\n}',
      },
    ],
  },
];
