import type { Part } from './chapter-one';

export const chapter = {
  id: 'regular-expressions',
  title: 'Ekspresi Reguler',
  number: '09',
};

export const parts: Part[] = [
  {
    id: 'pattern-values',
    title: 'Pola sebagai nilai',
    description: 'RegExp menyimpan aturan pencarian teks dan dapat dibuat sebagai literal atau dari string.',
    highlights: ['RegExp', 'literal', 'test', 'escape', 'pattern'],
    core: 'Ekspresi reguler adalah objek yang mendeskripsikan pola teks. Literal /kode/ cocok untuk pola tetap, sedangkan new RegExp(source) berguna saat pola dibentuk ketika program berjalan. Method test menghasilkan boolean berdasarkan ada atau tidaknya kecocokan.',
    model: ['teks masukan', 'uji dengan pola', 'true atau false'],
    why: 'Pola memungkinkan satu aturan ringkas dipakai untuk banyak teks. Namun karakter seperti titik, plus, dan kurung memiliki arti khusus sehingga karakter literal kadang harus diawali backslash.',
    example: 'const kode = /B-\\d{2}/;\nconsole.log(kode.test("Rak B-17"));\nconsole.log(kode.test("Rak B-X"));',
    mistake: 'Pola tanpa penanda batas mencari kecocokan di mana saja. Selain itu, backslash di dalam string konstruktor harus ditulis ganda, misalnya new RegExp("\\\\d+").',
    exercises: [
      {
        id: 'regex-values-predict', stage: 'Prediksi', mode: 'console', title: 'Uji pola pertama',
        instruction: 'Pilih dua baris keluaran dari pemanggilan test berikut.',
        starter: 'console.log(/B-\\d{2}/.test("Rak B-17"));\nconsole.log(/B-\\d{2}/.test("Rak B-X"));',
        options: ['true\nfalse', 'false\ntrue', 'true\ntrue', 'B-17\nB-X'], answer: 'true\nfalse',
        explanation: 'Pola meminta B- diikuti tepat dua digit. B-17 cocok, sedangkan B-X tidak.',
        tests: [{ name: 'Dua pengujian', inputs: {}, expected: 'true\nfalse' }],
        hints: ['\\d berarti digit.', '{2} meminta tepat dua kemunculan.'],
        solution: 'console.log(/B-\\d{2}/.test("Rak B-17"));\nconsole.log(/B-\\d{2}/.test("Rak B-X"));',
      },
      {
        id: 'regex-values-complete', stage: 'Lengkapi', mode: 'function', title: 'Kenali kode rak',
        instruction: 'Lengkapi isShelfCode(value) agar menerima tepat satu huruf kapital, tanda hubung, dan dua digit.',
        starter: 'function isShelfCode(value) {\n  return false;\n}', probe: 'isShelfCode',
        tests: [
          { name: 'Kode valid', inputs: {}, args: ['B-17'], expected: true },
          { name: 'Digit kurang', inputs: {}, args: ['B-7'], expected: false },
          { name: 'Teks berlebih', inputs: {}, args: ['Rak B-17'], expected: false },
        ],
        hints: ['Gunakan [A-Z] dan \\d{2}.', 'Tambahkan ^ dan $ agar seluruh teks diuji.'],
        solution: 'function isShelfCode(value) {\n  return /^[A-Z]-\\d{2}$/.test(value);\n}',
      },
      {
        id: 'regex-values-build', stage: 'Bangun', mode: 'function', title: 'Cari teks literal',
        instruction: 'Buat containsLiteral(text, query). Escape metakarakter query lalu uji apakah teks memuat query tersebut.',
        starter: '// Buat fungsi containsLiteral\n', probe: 'containsLiteral',
        tests: [
          { name: 'Plus dianggap literal', inputs: {}, args: ['Belajar C++ hari ini', 'C++'], expected: true },
          { name: 'Titik dianggap literal', inputs: {}, args: ['versi 4x0', '4.0'], expected: false },
          { name: 'Kurung ditemukan', inputs: {}, args: ['panggil fn()', 'fn()'], expected: true },
        ],
        hints: ['Ganti karakter \\ ^ $ . * + ? ( ) [ ] { } | dengan versi ber-backslash.', 'Buat new RegExp dari hasil escape.'],
        solution: 'function containsLiteral(text, query) {\n  const safe = query.replace(/[\\\\^$.*+?()[\\]{}|]/g, "\\\\$&");\n  return new RegExp(safe).test(text);\n}',
      },
    ],
  },
  {
    id: 'character-classes',
    title: 'Kelas karakter dan Unicode',
    description: 'Kelas karakter memilih satu karakter dari himpunan atau kategori yang ditentukan.',
    highlights: ['[]', '\\d', '\\s', '\\p{L}', 'u'],
    core: 'Kurung siku menyatakan pilihan satu karakter, tanda hubung membentuk rentang, dan ^ di awal kelas membalik pilihan. Shortcut seperti \\d dan \\s praktis, sedangkan properti Unicode seperti \\p{L} mengenali huruf dari banyak bahasa ketika flag u aktif.',
    model: ['satu posisi', 'kelas karakter', 'karakter cocok atau tidak'],
    why: 'Kategori Unicode lebih tepat untuk nama atau kata internasional daripada \\w yang terutama mengikuti definisi word character lama.',
    example: 'console.log(/^\\p{L}+$/u.test("José"));\nconsole.log(/^\\p{L}+$/u.test("R2D2"));',
    mistake: 'Jangan menganggap \\w berarti semua huruf manusia. Huruf beraksen dapat gagal; gunakan properti Unicode saat domain datanya lintas bahasa.',
    exercises: [
      {
        id: 'regex-class-predict', stage: 'Prediksi', mode: 'console', title: 'Bandingkan kelas huruf',
        instruction: 'Tentukan hasil pengujian kata beraksen dengan kelas lama dan properti Unicode.',
        starter: 'console.log(/^\\w+$/.test("éclair"));\nconsole.log(/^\\p{L}+$/u.test("éclair"));',
        options: ['false\ntrue', 'true\nfalse', 'true\ntrue', 'false\nfalse'], answer: 'false\ntrue',
        explanation: '\\w tidak mencakup é, sedangkan \\p{L} dengan flag u mengenalinya sebagai huruf.',
        tests: [{ name: 'Perbandingan Unicode', inputs: {}, expected: 'false\ntrue' }],
        hints: ['Perhatikan karakter é.', 'Flag u mengaktifkan properti Unicode.'],
        solution: 'console.log(/^\\w+$/.test("éclair"));\nconsole.log(/^\\p{L}+$/u.test("éclair"));',
      },
      {
        id: 'regex-class-complete', stage: 'Lengkapi', mode: 'function', title: 'Periksa digit heksadesimal',
        instruction: 'Lengkapi isHexDigit(char) agar menerima tepat satu karakter 0–9, a–f, atau A–F.',
        starter: 'function isHexDigit(char) {\n  return false;\n}', probe: 'isHexDigit',
        tests: [
          { name: 'Huruf kecil', inputs: {}, args: ['e'], expected: true },
          { name: 'Digit', inputs: {}, args: ['7'], expected: true },
          { name: 'Di luar rentang', inputs: {}, args: ['g'], expected: false },
          { name: 'Lebih dari satu', inputs: {}, args: ['af'], expected: false },
        ],
        hints: ['Gabungkan tiga rentang dalam satu kelas.', 'Gunakan batas awal dan akhir.'],
        solution: 'function isHexDigit(char) {\n  return /^[0-9a-fA-F]$/.test(char);\n}',
      },
      {
        id: 'regex-class-build', stage: 'Bangun', mode: 'function', title: 'Validasi nama',
        instruction: 'Buat isPersonName(text) yang menerima satu atau lebih huruf Unicode, dengan spasi tunggal di antara kata.',
        starter: '// Buat fungsi isPersonName\n', probe: 'isPersonName',
        tests: [
          { name: 'Nama Indonesia', inputs: {}, args: ['Dewi Lestari'], expected: true },
          { name: 'Nama beraksen', inputs: {}, args: ['José Álvarez'], expected: true },
          { name: 'Mengandung digit', inputs: {}, args: ['Ayu 2'], expected: false },
          { name: 'Spasi ganda', inputs: {}, args: ['Ayu  Putri'], expected: false },
        ],
        hints: ['Satu kata adalah \\p{L}+. ', 'Ulangi grup spasi lalu kata dengan (?: ... )*.'],
        solution: 'function isPersonName(text) {\n  return /^\\p{L}+(?: \\p{L}+)*$/u.test(text);\n}',
      },
    ],
  },
  {
    id: 'repetition-choice',
    title: 'Pengulangan, grup, dan pilihan',
    description: 'Quantifier mengatur jumlah kemunculan, sedangkan grup dan alternasi menyusun pola bercabang.',
    highlights: ['+', '*', '?', '{m,n}', '|', '(?:)'],
    core: 'Tanda + berarti satu atau lebih, * berarti nol atau lebih, dan ? membuat bagian opsional. Kurung memperlakukan beberapa token sebagai satu unit; (?:...) membuat grup tanpa menangkap. Tanda | memilih salah satu cabang.',
    model: ['elemen atau grup', 'aturan jumlah atau pilihan', 'pola gabungan'],
    why: 'Dengan kombinasi ini, aturan seperti beberapa jenis kupon atau format kode dapat dinyatakan tanpa membuat banyak pemeriksaan terpisah.',
    example: 'const coupon = /^(?:HEMAT|ONGKIR)-\\d{3}$/i;\nconsole.log(coupon.test("hemat-125"));',
    mistake: 'Alternasi memiliki cakupan lebar. /^ya|tidak$/ tidak membatasi kedua cabang secara utuh; gunakan /^(?:ya|tidak)$/.',
    exercises: [
      {
        id: 'regex-repeat-predict', stage: 'Prediksi', mode: 'console', title: 'Pilih cabang kupon',
        instruction: 'Tentukan keluaran saat pola memakai pilihan, tiga digit, dan flag tanpa peduli kapital.',
        starter: 'const coupon = /^(?:HEMAT|ONGKIR)-\\d{3}$/i;\nconsole.log(coupon.test("hemat-125"));\nconsole.log(coupon.test("HEMAT-12"));',
        options: ['true\nfalse', 'false\ntrue', 'true\ntrue', 'false\nfalse'], answer: 'true\nfalse',
        explanation: 'Flag i menerima kapital berbeda, tetapi {3} tetap meminta tepat tiga digit.',
        tests: [{ name: 'Dua kupon', inputs: {}, expected: 'true\nfalse' }],
        hints: ['i mengabaikan perbedaan kapital.', 'Hitung digit setelah tanda hubung.'],
        solution: 'const coupon = /^(?:HEMAT|ONGKIR)-\\d{3}$/i;\nconsole.log(coupon.test("hemat-125"));\nconsole.log(coupon.test("HEMAT-12"));',
      },
      {
        id: 'regex-repeat-complete', stage: 'Lengkapi', mode: 'function', title: 'Validasi nomor kursi',
        instruction: 'Lengkapi isSeat(value): satu huruf A–F, satu atau dua digit, lalu penanda jendela W yang opsional.',
        starter: 'function isSeat(value) {\n  return false;\n}', probe: 'isSeat',
        tests: [
          { name: 'Tanpa penanda', inputs: {}, args: ['C12'], expected: true },
          { name: 'Dengan penanda', inputs: {}, args: ['A7W'], expected: true },
          { name: 'Tiga digit', inputs: {}, args: ['B123'], expected: false },
          { name: 'Huruf salah', inputs: {}, args: ['G4'], expected: false },
        ],
        hints: ['Gunakan [A-F] dan \\d{1,2}.', 'W? membuat W opsional.'],
        solution: 'function isSeat(value) {\n  return /^[A-F]\\d{1,2}W?$/.test(value);\n}',
      },
      {
        id: 'regex-repeat-build', stage: 'Bangun', mode: 'function', title: 'Jam dua puluh empat jam',
        instruction: 'Buat isTime(value) untuk format HH:MM dari 00:00 sampai 23:59.',
        starter: '// Buat fungsi isTime\n', probe: 'isTime',
        tests: [
          { name: 'Awal hari', inputs: {}, args: ['00:00'], expected: true },
          { name: 'Akhir hari', inputs: {}, args: ['23:59'], expected: true },
          { name: 'Jam berlebih', inputs: {}, args: ['24:00'], expected: false },
          { name: 'Menit berlebih', inputs: {}, args: ['12:60'], expected: false },
        ],
        hints: ['Jam adalah [01]\\d atau 2[0-3].', 'Menit adalah [0-5]\\d.'],
        solution: 'function isTime(value) {\n  return /^(?:[01]\\d|2[0-3]):[0-5]\\d$/.test(value);\n}',
      },
    ],
  },
  {
    id: 'matches-groups',
    title: 'Kecocokan, posisi, dan tangkapan',
    description: 'Hasil exec dan match membawa teks yang cocok, grup tangkapan, dan lokasi awal.',
    highlights: ['exec', 'match', 'index', 'groups', 'capture'],
    core: 'test hanya menjawab ya atau tidak. exec mengembalikan null atau array: elemen pertama berisi seluruh kecocokan, diikuti isi setiap grup. Properti index menunjukkan lokasi kecocokan pertama.',
    model: ['pola dengan grup', 'exec pada teks', 'match, grup, index'],
    why: 'Grup tangkapan mengubah validator menjadi alat ekstraksi sehingga bagian tanggal, harga, atau koordinat dapat dipakai sebagai data terstruktur.',
    example: 'const found = /Rp(\\d+)/.exec("Total Rp25000");\nconsole.log(found[1], found.index);',
    mistake: 'Selalu periksa kemungkinan null sebelum membaca elemen hasil. Grup opsional yang tidak terpakai menghasilkan undefined.',
    exercises: [
      {
        id: 'regex-match-predict', stage: 'Prediksi', mode: 'console', title: 'Temukan harga pertama',
        instruction: 'Pilih keluaran nilai tangkapan dan indeks awal kecocokan.',
        starter: 'const found = /Rp(\\d+)/.exec("Bayar Rp7500");\nconsole.log(found[1]);\nconsole.log(found.index);',
        options: ['7500\n6', 'Rp7500\n6', '7500\n0', 'Rp7500\n0'], answer: '7500\n6',
        explanation: 'Grup pertama menangkap digit saja. Huruf R pada kecocokan dimulai di indeks 6.',
        tests: [{ name: 'Nilai dan posisi', inputs: {}, expected: '7500\n6' }],
        hints: ['Elemen [1] adalah isi grup pertama.', 'Hitung karakter sebelum R pada Rp7500.'],
        solution: 'const found = /Rp(\\d+)/.exec("Bayar Rp7500");\nconsole.log(found[1]);\nconsole.log(found.index);',
      },
      {
        id: 'regex-match-complete', stage: 'Lengkapi', mode: 'function', title: 'Urai tanggal ISO sederhana',
        instruction: 'Lengkapi parseDate(value) agar mengembalikan objek angka {year, month, day}, atau null jika format bukan YYYY-MM-DD.',
        starter: 'function parseDate(value) {\n  const match = null;\n  return match;\n}', probe: 'parseDate',
        tests: [
          { name: 'Tanggal berformat benar', inputs: {}, args: ['2025-08-17'], expected: { year: 2025, month: 8, day: 17 } },
          { name: 'Format salah', inputs: {}, args: ['17/08/2025'], expected: null },
        ],
        hints: ['Tangkap tiga bagian dengan kurung.', 'Jika match ada, ubah match[1], match[2], dan match[3] memakai Number.'],
        solution: 'function parseDate(value) {\n  const match = /^(\\d{4})-(\\d{2})-(\\d{2})$/.exec(value);\n  if (!match) return null;\n  return { year: Number(match[1]), month: Number(match[2]), day: Number(match[3]) };\n}',
      },
      {
        id: 'regex-match-build', stage: 'Bangun', mode: 'function', title: 'Urai koordinat',
        instruction: 'Buat parseCoordinate(value) yang menerima dua bilangan desimal bertanda opsional, dipisah koma dan spasi opsional. Kembalikan {lat, lon} atau null.',
        starter: '// Buat fungsi parseCoordinate\n', probe: 'parseCoordinate',
        tests: [
          { name: 'Koordinat negatif dan positif', inputs: {}, args: ['-6.20, 106.82'], expected: { lat: -6.2, lon: 106.82 } },
          { name: 'Tanpa spasi', inputs: {}, args: ['1,2.5'], expected: { lat: 1, lon: 2.5 } },
          { name: 'Data tidak lengkap', inputs: {}, args: ['-6.2,'], expected: null },
        ],
        hints: ['Bilangan dapat ditulis [+-]?\\d+(?:\\.\\d+)?.', 'Tangkap kedua bilangan dan ubah dengan Number.'],
        solution: 'function parseCoordinate(value) {\n  const match = /^([+-]?\\d+(?:\\.\\d+)?),\\s*([+-]?\\d+(?:\\.\\d+)?)$/.exec(value);\n  if (!match) return null;\n  return { lat: Number(match[1]), lon: Number(match[2]) };\n}',
      },
    ],
  },
  {
    id: 'boundaries-lookahead',
    title: 'Batas dan lookahead',
    description: 'Penanda posisi memastikan kecocokan berada di lokasi yang tepat tanpa mengambil karakter tambahan.',
    highlights: ['^', '$', 'lookahead', '(?=)', '(?!)'],
    core: '^ menandai awal input dan $ menandai akhir, sehingga keduanya cocok untuk validasi seluruh nilai. Lookahead positif (?=...) meminta pola berikutnya ada, sedangkan lookahead negatif (?!...) meminta pola berikutnya tidak ada.',
    model: ['posisi saat ini', 'uji kondisi sekitar', 'lanjut tanpa konsumsi'],
    why: 'Batas membedakan pencarian dari validasi. Lookahead berguna ketika beberapa syarat harus diterapkan pada teks yang sama.',
    example: 'console.log(/^\\d{5}$/.test("40123"));\nconsole.log(/^(?=.*[A-Za-z])(?=.*\\d).{8,16}$/.test("kelas2025"));',
    mistake: 'Lookahead tidak memindahkan posisi. Pola sesudahnya tetap harus mengonsumsi isi. Batasi panjang masukan dan hindari tumpukan quantifier ambigu.',
    exercises: [
      {
        id: 'regex-boundary-predict', stage: 'Prediksi', mode: 'console', title: 'Cari atau validasi',
        instruction: 'Tentukan perbedaan pola tanpa dan dengan batas pada teks yang memiliki awalan.',
        starter: 'console.log(/\\d{5}/.test("ID:40123"));\nconsole.log(/^\\d{5}$/.test("ID:40123"));',
        options: ['true\nfalse', 'false\ntrue', 'true\ntrue', 'false\nfalse'], answer: 'true\nfalse',
        explanation: 'Pola pertama boleh menemukan lima digit di tengah teks. Pola kedua meminta seluruh teks hanya lima digit.',
        tests: [{ name: 'Pencarian dan validasi', inputs: {}, expected: 'true\nfalse' }],
        hints: ['Pola pertama tidak memiliki batas.', '^ meminta kecocokan mulai pada karakter pertama.'],
        solution: 'console.log(/\\d{5}/.test("ID:40123"));\nconsole.log(/^\\d{5}$/.test("ID:40123"));',
      },
      {
        id: 'regex-boundary-complete', stage: 'Lengkapi', mode: 'function', title: 'PIN enam digit',
        instruction: 'Lengkapi isPin(value) agar hanya menerima string berisi tepat enam digit.',
        starter: 'function isPin(value) {\n  return /\\d{6}/.test(value);\n}', probe: 'isPin',
        tests: [
          { name: 'PIN valid', inputs: {}, args: ['083421'], expected: true },
          { name: 'Ada spasi', inputs: {}, args: ['083421 '], expected: false },
          { name: 'Terlalu panjang', inputs: {}, args: ['1083421'], expected: false },
        ],
        hints: ['Pola jumlah digit sudah ada.', 'Tambahkan ^ di depan dan $ di belakang.'],
        solution: 'function isPin(value) {\n  return /^\\d{6}$/.test(value);\n}',
      },
      {
        id: 'regex-boundary-build', stage: 'Bangun', mode: 'function', title: 'Syarat kata sandi',
        instruction: 'Buat isPassword(value): panjang 8–16 karakter, setidaknya satu huruf ASCII dan satu digit, serta tanpa spasi.',
        starter: '// Buat fungsi isPassword\n', probe: 'isPassword',
        tests: [
          { name: 'Valid', inputs: {}, args: ['kelas2025'], expected: true },
          { name: 'Tanpa digit', inputs: {}, args: ['kelaspagi'], expected: false },
          { name: 'Memiliki spasi', inputs: {}, args: ['kelas 2025'], expected: false },
          { name: 'Terlalu pendek', inputs: {}, args: ['a1b2'], expected: false },
        ],
        hints: ['Gunakan lookahead untuk huruf dan digit.', 'Bagian akhir dapat memakai [^\\s]{8,16}.'],
        solution: 'function isPassword(value) {\n  return /^(?=.*[A-Za-z])(?=.*\\d)[^\\s]{8,16}$/.test(value);\n}',
      },
    ],
  },
  {
    id: 'replace-greed',
    title: 'Penggantian dan kerakusan',
    description: 'replace mengubah kecocokan dengan teks atau callback; quantifier nonrakus mengambil rentang minimum.',
    highlights: ['replace', 'g', '$1', 'callback', '*?'],
    core: 'String.replace dapat menerima regex dan teks pengganti. Flag g mengganti semua kecocokan. Grup dapat dirujuk sebagai $1 dan seterusnya, sedangkan callback menghitung pengganti dari setiap kecocokan. Quantifier rakus mencoba mengambil sebanyak mungkin; tanda ? setelahnya membuatnya nonrakus.',
    model: ['temukan match', 'buat pengganti', 'hasilkan string baru'],
    why: 'Penggantian berbasis pola cocok untuk menata ulang teks atau menyensor bagian tertentu tanpa memecah string secara manual.',
    example: 'console.log("Lestari, Dewi".replace(/(\\w+), (\\w+)/, "$2 $1"));',
    mistake: 'Pola <.*> dapat menelan beberapa tag sekaligus. Untuk data pendek yang sederhana gunakan <.*?>; regex bukan parser HTML umum.',
    exercises: [
      {
        id: 'regex-replace-predict', stage: 'Prediksi', mode: 'console', title: 'Rakus atau minimum',
        instruction: 'Pilih dua hasil penghapusan tag dengan quantifier rakus dan nonrakus.',
        starter: 'const text = "A<x>B<y>C";\nconsole.log(text.replace(/<.*>/g, ""));\nconsole.log(text.replace(/<.*?>/g, ""));',
        options: ['AC\nABC', 'ABC\nAC', 'A<x>B<y>C\nABC', 'A\nABC'], answer: 'AC\nABC',
        explanation: '.* mengambil dari tanda < pertama sampai > terakhir. .*? berhenti pada penutup terdekat untuk setiap tag.',
        tests: [{ name: 'Dua jenis quantifier', inputs: {}, expected: 'AC\nABC' }],
        hints: ['Pola rakus mencoba rentang terpanjang.', 'Flag g mengulangi penggantian nonrakus.'],
        solution: 'const text = "A<x>B<y>C";\nconsole.log(text.replace(/<.*>/g, ""));\nconsole.log(text.replace(/<.*?>/g, ""));',
      },
      {
        id: 'regex-replace-complete', stage: 'Lengkapi', mode: 'function', title: 'Balik urutan nama',
        instruction: 'Lengkapi swapName(value) untuk mengubah format "Belakang, Depan" menjadi "Depan Belakang" menggunakan grup pengganti.',
        starter: 'function swapName(value) {\n  return value.replace(/^(\\p{L}+), (\\p{L}+)$/u, "$1 $2");\n}', probe: 'swapName',
        tests: [
          { name: 'Nama biasa', inputs: {}, args: ['Lestari, Dewi'], expected: 'Dewi Lestari' },
          { name: 'Nama Unicode', inputs: {}, args: ['Álvarez, José'], expected: 'José Álvarez' },
        ],
        hints: ['Grup pertama adalah nama belakang.', 'Tukar menjadi $2 lalu $1.'],
        solution: 'function swapName(value) {\n  return value.replace(/^(\\p{L}+), (\\p{L}+)$/u, "$2 $1");\n}',
      },
      {
        id: 'regex-replace-build', stage: 'Bangun', mode: 'function', title: 'Sensor nomor panjang',
        instruction: 'Buat maskNumber(value). Hapus karakter nondigit untuk pemrosesan, lalu ganti setiap digit yang masih memiliki empat digit di kanannya dengan *.',
        starter: '// Buat fungsi maskNumber\n', probe: 'maskNumber',
        tests: [
          { name: 'Enam digit', inputs: {}, args: ['123456'], expected: '**3456' },
          { name: 'Dengan pemisah', inputs: {}, args: ['12-34 5678'], expected: '****5678' },
          { name: 'Empat digit', inputs: {}, args: ['9876'], expected: '9876' },
        ],
        hints: ['Buat digits dengan value.replace(/\\D/g, "").', 'Gunakan /\\d(?=\\d{4})/g untuk digit yang harus disamarkan.'],
        solution: 'function maskNumber(value) {\n  const digits = value.replace(/\\D/g, "");\n  return digits.replace(/\\d(?=\\d{4})/g, "*");\n}',
      },
    ],
  },
  {
    id: 'global-state',
    title: 'Banyak kecocokan dan state',
    description: 'Regex global dapat menyimpan posisi pencarian; matchAll mengumpulkan kecocokan beserta lokasinya.',
    highlights: ['g', 'lastIndex', 'exec', 'matchAll', 'index'],
    core: 'Dengan flag g atau y, exec membaca dan memperbarui lastIndex. Kecocokan sukses memindahkannya ke akhir match, sedangkan kegagalan meresetnya. matchAll dengan regex global menyediakan iterator seluruh hasil tanpa loop exec manual.',
    model: ['lastIndex awal', 'exec atau matchAll', 'hasil dan posisi berikutnya'],
    why: 'Memahami state mencegah regex global yang dipakai ulang melewatkan data. matchAll cocok saat setiap match dan indeksnya diperlukan.',
    example: 'const found = [..."A12 B7".matchAll(/\\d+/g)];\nconsole.log(found.map(item => [item[0], item.index]));',
    mistake: 'Memanggil test berulang pada regex global yang sama dapat bergantian true dan false karena lastIndex berubah. Gunakan regex tanpa g untuk pemeriksaan independen.',
    exercises: [
      {
        id: 'regex-state-predict', stage: 'Prediksi', mode: 'console', title: 'Lacak lastIndex',
        instruction: 'Tentukan tiga nilai lastIndex setelah dua kecocokan dan satu kegagalan.',
        starter: 'const digits = /\\d/g;\ndigits.exec("A1B2"); console.log(digits.lastIndex);\ndigits.exec("A1B2"); console.log(digits.lastIndex);\ndigits.exec("A1B2"); console.log(digits.lastIndex);',
        options: ['2\n4\n0', '1\n2\n3', '2\n4\n4', '0\n0\n0'], answer: '2\n4\n0',
        explanation: 'Dua match berakhir di indeks 2 dan 4. Pencarian ketiga gagal lalu mereset lastIndex ke 0.',
        tests: [{ name: 'Perubahan state', inputs: {}, expected: '2\n4\n0' }],
        hints: ['lastIndex menunjuk sesudah karakter yang cocok.', 'Kegagalan regex global mereset posisi.'],
        solution: 'const digits = /\\d/g;\ndigits.exec("A1B2"); console.log(digits.lastIndex);\ndigits.exec("A1B2"); console.log(digits.lastIndex);\ndigits.exec("A1B2"); console.log(digits.lastIndex);',
      },
      {
        id: 'regex-state-complete', stage: 'Lengkapi', mode: 'function', title: 'Kumpulkan persentase',
        instruction: 'Lengkapi findPercentages(text) agar mengembalikan array objek {value, index} untuk semua angka yang diikuti %. value harus number.',
        starter: 'function findPercentages(text) {\n  const result = [];\n  return result;\n}', probe: 'findPercentages',
        tests: [
          { name: 'Dua nilai', inputs: {}, args: ['Naik 12%, lalu turun 3%.'], expected: [{ value: 12, index: 5 }, { value: 3, index: 21 }] },
          { name: 'Tidak ada', inputs: {}, args: ['Tidak berubah'], expected: [] },
        ],
        hints: ['Loop melalui text.matchAll(/(\\d+)%/g).', 'match.index adalah posisi awal dan match[1] adalah digit.'],
        solution: 'function findPercentages(text) {\n  const result = [];\n  for (const match of text.matchAll(/(\\d+)%/g)) {\n    result.push({ value: Number(match[1]), index: match.index });\n  }\n  return result;\n}',
      },
      {
        id: 'regex-state-build', stage: 'Bangun', mode: 'function', title: 'Indeks hashtag',
        instruction: 'Buat findHashtags(text) yang mengembalikan semua hashtag ASCII sebagai {tag, index}; tag tidak menyertakan #.',
        starter: '// Buat fungsi findHashtags\n', probe: 'findHashtags',
        tests: [
          { name: 'Dua tag', inputs: {}, args: ['Belajar #js dan #regex!'], expected: [{ tag: 'js', index: 8 }, { tag: 'regex', index: 16 }] },
          { name: 'Tanpa tag', inputs: {}, args: ['teks biasa'], expected: [] },
        ],
        hints: ['Gunakan /#([A-Za-z0-9_]+)/g.', 'matchAll memberi match[1] dan match.index.'],
        solution: 'function findHashtags(text) {\n  return [...text.matchAll(/#([A-Za-z0-9_]+)/g)].map(match => ({ tag: match[1], index: match.index }));\n}',
      },
    ],
  },
  {
    id: 'dynamic-parser',
    title: 'Pola dinamis dan parser mini',
    description: 'Regex bekerja baik sebagai pengenal bagian kecil di dalam parser yang tetap mengendalikan alur.',
    highlights: ['RegExp', 'escape', 'split', 'parser', 'Error'],
    core: 'Input pengguna harus di-escape sebelum menjadi bagian pola dinamis. Untuk format berbaris, gunakan regex kecil untuk mengenali tiap jenis baris lalu bangun hasil dengan logika JavaScript biasa.',
    model: ['pecah menjadi baris', 'klasifikasikan baris', 'bangun objek atau tolak'],
    why: 'Pembagian tugas ini menjaga pola tetap terbaca. Regex mengenali bentuk lokal, sedangkan program menangani state bagian dan pesan kesalahan.',
    example: 'for (const line of source.split(/\\r?\\n/)) {\n  if (/^;/.test(line)) continue;\n  // kenali baris lain\n}',
    mistake: 'Jangan memasukkan teks mentah ke new RegExp dan jangan memaksa satu regex besar mem-parsing format bertingkat. Keduanya rawan bug dan sulit dirawat.',
    exercises: [
      {
        id: 'regex-parser-predict', stage: 'Prediksi', mode: 'console', title: 'Escape pencarian dinamis',
        instruction: 'Tentukan hasil ketika tanda plus di query sudah di-escape sebelum pola dibuat.',
        starter: 'const query = "C++";\nconst safe = query.replace(/[\\\\^$.*+?()[\\]{}|]/g, "\\\\$&");\nconsole.log(new RegExp(safe).test("Kelas C++"));\nconsole.log(safe);',
        options: ['true\nC\\+\\+', 'false\nC++', 'true\nC++', 'false\nC\\+\\+'], answer: 'true\nC\\+\\+',
        explanation: 'Kedua plus diubah menjadi token literal sehingga pola dapat menemukan teks C++.',
        tests: [{ name: 'Pola aman', inputs: {}, expected: 'true\nC\\+\\+' }],
        hints: ['$& adalah seluruh karakter yang cocok.', 'Backslash membuat plus kehilangan arti quantifier.'],
        solution: 'const query = "C++";\nconst safe = query.replace(/[\\\\^$.*+?()[\\]{}|]/g, "\\\\$&");\nconsole.log(new RegExp(safe).test("Kelas C++"));\nconsole.log(safe);',
      },
      {
        id: 'regex-parser-complete', stage: 'Lengkapi', mode: 'function', title: 'Escape metakarakter',
        instruction: 'Lengkapi escapeRegExp(text) agar teks hasil dapat dipakai sebagai pola literal pada new RegExp.',
        starter: 'function escapeRegExp(text) {\n  return text;\n}', probe: 'escapeRegExp',
        tests: [
          { name: 'Tanda plus', inputs: {}, args: ['C++'], expected: 'C\\+\\+' },
          { name: 'Titik dan kurung', inputs: {}, args: ['a.(b)'], expected: 'a\\.\\(b\\)' },
          { name: 'Teks biasa', inputs: {}, args: ['halo'], expected: 'halo' },
        ],
        hints: ['Cari semua karakter dalam kelas [\\\\^$.*+?()[\\]{}|].', 'Ganti dengan "\\\\$&" memakai flag g.'],
        solution: 'function escapeRegExp(text) {\n  return text.replace(/[\\\\^$.*+?()[\\]{}|]/g, "\\\\$&");\n}',
      },
      {
        id: 'regex-parser-build', stage: 'Bangun', mode: 'function', title: 'Parser agenda berbagian',
        instruction: 'Buat parseAgenda(source). Abaikan baris kosong/komentar ;, simpan key=value, dan buat objek baru untuk [bagian]. Lempar Error untuk baris lain.',
        starter: '// Buat fungsi parseAgenda\n', probe: 'parseAgenda',
        tests: [
          { name: 'Data berbagian', inputs: {}, args: ['judul=Rapat\n; catatan\n[acara]\ntempat=Aula\njam=09:00'], expected: { judul: 'Rapat', acara: { tempat: 'Aula', jam: '09:00' } } },
          { name: 'Baris Windows', inputs: {}, args: ['nama=Kelas\r\n[info]\r\nruang=B2'], expected: { nama: 'Kelas', info: { ruang: 'B2' } } },
        ],
        hints: ['Gunakan source.split(/\\r?\\n/).', 'Cocokkan /^([^=]+)=(.*)$/ dan /^\\[([^\\]]+)\\]$/.'],
        solution: 'function parseAgenda(source) {\n  const result = {};\n  let section = result;\n  for (const line of source.split(/\\r?\\n/)) {\n    let match;\n    if (/^\\s*(?:;.*)?$/.test(line)) continue;\n    if ((match = /^([^=]+)=(.*)$/.exec(line))) {\n      section[match[1]] = match[2];\n    } else if ((match = /^\\[([^\\]]+)\\]$/.exec(line))) {\n      section = result[match[1]] = {};\n    } else {\n      throw new Error("Baris tidak valid: " + line);\n    }\n  }\n  return result;\n}',
      },
    ],
  },
];
